// src/components/BlockNameDisplay.vue
<template>
  <div class="pos-abs">
    <template v-if="worldView.hoveredEntity">
      <h2 class="hovered-block-text">Last clicked entity:</h2>
      <h2 class="hovered-block-text">{{ worldView.hoveredEntity.name }}</h2>
      <h2 class="hovered-block-text">{{ worldView.hoveredEntity.id }}</h2>
      <h2 class="hovered-block-text" v-if="worldView.hoveredEntity.worldPos">
        {{ worldView.hoveredEntity.worldPos.x.toFixed(1) }},
        {{ worldView.hoveredEntity.worldPos.y.toFixed(1) }},
        {{ worldView.hoveredEntity.worldPos.z.toFixed(1) }}
      </h2>
    </template>
    <template v-else>
      <h2 class="hovered-block-text">Last clicked block:</h2>
      <h2 class="hovered-block-text" v-if="worldView.hoveredBlock">
        {{ worldView.hoveredBlock.name }}:{{ worldView.hoveredBlock.metadata }}
      </h2>
      <h2 class="hovered-block-text" v-if="worldView.hoveredBlockPos">
        {{ worldView.hoveredBlockPos.x }}:{{ worldView.hoveredBlockPos.y }}:{{ worldView.hoveredBlockPos.z }}
      </h2>
    </template>
  </div>
</template>

<style scoped>

.hovered-block-text {
    color: lightgray;
    user-select: none;
    white-space: nowrap;
}
.pos-abs {
  position: fixed;
  top: 10px;
  right: 10px;
  background: rgb(30, 30, 30);
  border: 1px solid rgb(70, 70, 70);
  border-radius: 6px;
  padding: 8px 12px;
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import { useWorldViewStore } from "../store/useWorldView";

export default defineComponent({
  setup() {
    const worldView = useWorldViewStore();
    return { worldView };
  },
});
</script>

// components/staticGui/BlockNameDisplay.tsx
'use client'

import { useWorldViewStore } from '@/store/useWorldView'

export default function BlockNameDisplay() {
  const hoveredBlock = useWorldViewStore(s => s.hoveredBlock)
  const hoveredBlockPos = useWorldViewStore(s => s.hoveredBlockPos)
  const hoveredEntity = useWorldViewStore(s => s.hoveredEntity)
  const lockBlockInfo = useWorldViewStore(s => s.lockBlockInfo)

  return (
    <div style={{ position: 'fixed', top: 10, right: 10, background: 'rgb(30,30,30)', border: '1px solid rgb(70,70,70)', borderRadius: 6, padding: '8px 12px', display: 'flex', flexDirection: 'column', gap: 4 }}>
      <h2 style={{ ...h2Style, color: 'gray', fontSize: '0.75em', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
        {hoveredEntity ? 'Entity' : lockBlockInfo ? 'Last clicked block' : 'Hovered block'}
      </h2>
      {hoveredEntity ? (
        <>
          <h2 style={h2Style}>{hoveredEntity.name}</h2>
          <h2 style={h2Style}>{hoveredEntity.id}</h2>
          {hoveredEntity.worldPos && (
            <h2 style={h2Style}>
              {hoveredEntity.worldPos.x.toFixed(1)}, {hoveredEntity.worldPos.y.toFixed(1)}, {hoveredEntity.worldPos.z.toFixed(1)}
            </h2>
          )}
        </>
      ) : (
        <>
          {hoveredBlock && <h2 style={h2Style}>{hoveredBlock.name}:{hoveredBlock.metadata}</h2>}
          {hoveredBlockPos && <h2 style={h2Style}>{hoveredBlockPos.x}, {hoveredBlockPos.y}, {hoveredBlockPos.z}</h2>}
        </>
      )}
    </div>
  )
}

const h2Style: React.CSSProperties = { color: 'lightgray', userSelect: 'none', whiteSpace: 'nowrap', margin: 0, fontSize: '1em', fontWeight: 'normal' }
