// src/components/CCRemoteController.vue
<template>
  <div class="hud">
    <h1 v-if="world.isLoading" class="centered">
      LOADING ... (depending on the number of blocks this might take some
      seconds)
    </h1>
    <div class="hud-panel">
      <div class="panel-left">
        <a class="home-link" href="/api/home">← turkeyblock.org</a>
        <div class="modem-status" :class="world.modemServerId !== null ? 'modem-online' : 'modem-offline'">
          📡 Modem: {{ world.modemServerId !== null ? `online (id ${world.modemServerId})` : 'offline' }}
        </div>
        <select v-model="worldView.selectedComputerId" @change="worldView.followComputer(worldView.selectedComputerId)">
          <option :value="-1">[None]</option>
          <option v-for="id in world.getComputerIds" :key="id" :value="id">
            {{ world.computers[id].type === 'minecart' ? 'Minecart' : world.computers[id].type === 'modem' ? 'Modem' : 'Turtle' }} {{ id }}{{ world.computers[id].type === 'modem' ? (world.modemServerId !== null ? ' [online]' : ' [offline]') : ((world.computers[id].via_modem ? ' 📡' : '') + (world.computers[id].sleep_mode ? ' 💤' : '') + (isStale(world.computers[id]) ? ' [offline]' : ' [online]')) }} : {{ world.computers[id].label }}
          </option>
        </select>
        <div v-if="worldView.selectedComputerId === -1" class="manual-center">
          <span class="manual-center-label">Center</span>
          <input type="number" v-model.number="manualX" placeholder="X" class="coord-input" @change="applyManualCenter" />
          <input type="number" v-model.number="manualZ" placeholder="Z" class="coord-input" @change="applyManualCenter" />
        </div>
        <TurtlePanel
          v-if="Number(worldView.selectedComputerId) != -1"
          :computerId="Number(worldView.selectedComputerId)"
        />
      </div>
      <div class="panel-right">
        <RenderFilters ref="renderFilters" @opened="closeOtherPanels('renderFilters')" />
        <BlockTransparency ref="blockTransparency" @opened="closeOtherPanels('blockTransparency')" />
        <div v-if="isGuest" class="guest-controls">
          <a href="/api/signin" class="guest-signin">Sign in</a>
          <button
            class="guest-refresh-btn"
            :disabled="guestRefreshDisabled"
            @click="guestRefresh"
          >{{ guestRefreshDisabled ? 'Refreshed ✓' : 'Refresh' }}</button>
        </div>
        <span v-if="user.loaded && user.isOperator && !user.isAdmin" class="operator-badge">Operator</span>
        <OperatorRequest v-if="user.loaded && !user.isOperator && !isGuest" />
        <AdminPanel v-if="user.isAdmin" ref="adminPanel" @opened="closeOtherPanels('adminPanel')" />
      </div>
    </div>
    <Inventory
      v-if="worldView.selectedInventory"
      :inventory="worldView.selectedInventory"
      :inventorySize="worldView.selectedInventorySize"
      style="grid-column: 2; pointer-events: auto"
    />
    <Scene />
    <KeyboardBindings />
    <BlockNameDisplay />
  </div>
</template>

<style scoped>
.hud {
  position: absolute;
  display: grid;
  user-select: none;
  pointer-events: none;
}
.centered {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.hud-panel {
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  gap: 8px;
  padding: 10px;
  pointer-events: auto;
}

.panel-left {
  display: flex;
  flex-direction: column;
  gap: 6px;
  min-width: 240px;
  background: rgb(30, 30, 30);
  border: 1px solid rgb(70, 70, 70);
  border-radius: 6px;
  padding: 8px 12px;
}

.panel-right {
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  gap: 6px;
}

.home-link {
  color: darkgray;
  font-size: 0.85em;
  text-decoration: none;
}

.home-link:hover {
  color: white;
}

.operator-badge {
  font-size: 0.75em;
  color: rgb(80, 180, 80);
  letter-spacing: 0.05em;
  text-transform: uppercase;
}

.manual-center {
  display: flex;
  align-items: center;
  gap: 4px;
}

.manual-center-label {
  font-size: 0.75em;
  color: gray;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  flex-shrink: 0;
}

.coord-input {
  width: 64px;
  padding: 2px 4px;
  border-radius: 4px;
  border: 1px solid rgb(70, 70, 70);
  background: rgb(40, 40, 40);
  color: darkgray;
  font-size: 0.85em;
  text-align: center;
}

.coord-input:focus {
  outline: none;
  border-color: rgb(100, 100, 100);
}

.guest-controls {
  display: flex;
  align-items: center;
  gap: 6px;
  background: rgb(30, 30, 30);
  border: 1px solid rgb(70, 70, 70);
  border-radius: 6px;
  padding: 6px 10px;
}

.guest-signin {
  color: darkgray;
  font-size: 0.85em;
  text-decoration: none;
}

.guest-signin:hover {
  color: white;
}

.guest-refresh-btn {
  padding: 3px 10px;
  border-radius: 4px;
  border: none;
  background: rgb(52, 52, 52);
  color: darkgray;
  cursor: pointer;
  font-size: 0.85em;
}

.guest-refresh-btn:hover:not(:disabled) {
  background: rgb(70, 70, 70);
  color: white;
}

.guest-refresh-btn:disabled {
  opacity: 0.5;
  cursor: default;
}

select {
  padding: 4px;
  border-radius: 4px;
  background-color: rgb(52, 52, 52);
  color: darkgray;
  font-weight: bold;
}

.modem-status {
  font-size: 0.75em;
  letter-spacing: 0.03em;
}
.modem-online { color: rgb(80, 200, 80); }
.modem-offline { color: rgb(120, 120, 120); }
</style>

<script lang="ts">
import { defineComponent } from "vue";
import * as THREE from "three";

import { useWorldStore } from "../store/useWorld";
import { isStale } from "../utils/stale";
import { useWorldViewStore } from "../store/useWorldView";
import { useUserStore } from "../store/useUser";
import TurtlePanel from "./TurtlePanel.vue";
import Inventory from "./Inventory.vue";
import BlockNameDisplay from "./BlockNameDisplay.vue";
import Scene from "./Scene.vue";
import KeyboardBindings from "./KeyboardBindings.vue";
import AdminPanel from "./AdminPanel.vue";
import OperatorRequest from "./OperatorRequest.vue";
import BlockTransparency from "./BlockTransparency.vue";
import RenderFilters from "./RenderFilters.vue";

export default defineComponent({
  setup() {
    const world = useWorldStore();
    const worldView = useWorldViewStore();
    const user = useUserStore();
    return { world, worldView, user };
  },
  data() {
    return {
      computerId: -1 as Number,
      manualX: null as number | null,
      manualZ: null as number | null,
      _ws: null as WebSocket | null,
      _wsBackoff: 1000 as number,
      _wsReconnectTimeout: null as ReturnType<typeof setTimeout> | null,
      _cmdResultInterval: null as ReturnType<typeof setInterval> | null,
      _modemStatusInterval: null as ReturnType<typeof setInterval> | null,
      isGuest: false,
      guestRefreshDisabled: false,
      _guestRefreshTimer: null as ReturnType<typeof setTimeout> | null,
    };
  },
  watch: {
    'worldView.selectedComputerId'(id: number) {
      if (id === -1) return;
      this.worldView.manualCenter = null;
      // Only rebuild the scene when a range filter is active — that's the only
      // case where the visible block set actually changes with the computer.
      // Otherwise just reposition the camera.
      if (this.worldView.computerRangeXZ !== null) {
        this.worldView.regenerateSceneFromBlocks();
      } else {
        this.worldView.focusOnComputer(id);
      }
    },
  },
  components: {
    TurtlePanel,
    Scene,
    BlockNameDisplay,
    Inventory,
    KeyboardBindings,
    AdminPanel,
    OperatorRequest,
    BlockTransparency,
    RenderFilters,
  },
  methods: {
    applyManualCenter() {
      if (this.manualX !== null && this.manualZ !== null) {
        this.worldView.manualCenter = { x: this.manualX, z: this.manualZ };
        this.worldView.setCameraFocus(new THREE.Vector3(this.manualX, 64, this.manualZ));
      } else {
        this.worldView.manualCenter = null;
      }
      this.worldView.regenerateSceneFromBlocks();
    },
    closeOtherPanels(except: string) {
      (['renderFilters', 'blockTransparency', 'adminPanel'] as const).forEach(name => {
        if (name !== except) {
          const ref = this.$refs[name] as any;
          if (ref) ref.open = false;
        }
      });
    },
    connectWebSocket() {
      const world = useWorldStore();
      const worldView = useWorldViewStore();

      const wsUrl = world.URL
        ? world.URL.replace(/^http/, 'ws')
        : `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}`;

      const ws = new WebSocket(wsUrl);
      this._ws = ws;

      ws.onopen = () => {
        this._wsBackoff = 1000;
      };

      ws.onmessage = (event) => {
        const data = JSON.parse(event.data);
        if (data.state) {
          const alreadyCurrent = data.state.lastTransactionId === world.lastTransactionId;
          world.setComputerStatus(data.state.computers);
          world.blocks = data.state.world.blocks;
          world.lastTransactionId = data.state.lastTransactionId;
          if (!alreadyCurrent) {
            if (!world.computers[worldView.selectedComputerId]?.loc) {
              const entry = Object.entries(world.computers).find(([, c]) => c.loc);
              if (entry) worldView.selectedComputerId = Number(entry[0]);
            }
            worldView.regenerateSceneFromBlocks();
          }
        } else {
          world.applyTransactions(data.transactions);
        }
        worldView.render();
        world.isLoading = false;
      };

      ws.onclose = (event) => {
        if (event.code === 4401) {
          this.isGuest = true;
          if (this._cmdResultInterval) { clearInterval(this._cmdResultInterval); this._cmdResultInterval = null; }
          this.loadGuestState();
          return;
        }
        const delay = this._wsBackoff;
        this._wsBackoff = Math.min(this._wsBackoff * 2, 10000);
        this._wsReconnectTimeout = setTimeout(() => this.connectWebSocket(), delay);
      };

      ws.onerror = () => ws.close();
    },
    async pollModemStatus() {
      const world = useWorldStore();
      const res = await fetch(world.apiURL + 'modem/id').catch(() => null);
      if (!res || !res.ok) return;
      const data = await res.json().catch(() => null);
      if (data) world.modemServerId = data.id ?? null;
    },
    pollCommandResult() {
      const world = useWorldStore();
      const worldView = useWorldViewStore();
      if (worldView.selectedComputerId === -1) return;
      fetch(world.apiURL + "getCommandResult", {
        method: "POST",
        mode: "cors",
        headers: {
          "Access-Control-Allow-Origin": "*",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          computerId: worldView.selectedComputerId,
          getOnlyLatest: true,
        }),
      })
        .then((res) => res.json())
        .then((data) => {
          if (data.result) {
            world.commandResult[data.computerId] = data.result.ret;
          }
        });
    },
    async loadGuestState() {
      const world = useWorldStore();
      const worldView = useWorldViewStore();
      const res = await fetch('/api/state').catch(() => null);
      if (!res) return;
      if (res.status === 429) {
        const data = await res.json().catch(() => ({}));
        this.startGuestCooldown(data.retryAfter ?? 30);
        return;
      }
      const data = await res.json().catch(() => null);
      if (!data) return;
      world.setComputerStatus(data.computers);
      world.blocks = data.world.blocks;
      if (!world.computers[worldView.selectedComputerId]?.loc) {
        const entry = Object.entries(world.computers).find(([, c]) => c.loc);
        if (entry) worldView.selectedComputerId = Number(entry[0]);
      }
      worldView.regenerateSceneFromBlocks();
      worldView.render();
      world.isLoading = false;
      this.startGuestCooldown(30);
    },
    guestRefresh() {
      if (this.guestRefreshDisabled) return;
      this.loadGuestState();
    },
    startGuestCooldown(seconds: number) {
      this.guestRefreshDisabled = true;
      if (this._guestRefreshTimer) clearTimeout(this._guestRefreshTimer);
      this._guestRefreshTimer = setTimeout(() => {
        this.guestRefreshDisabled = false;
        this._guestRefreshTimer = null;
      }, seconds * 1000);
    },
    isStale,
  },
  mounted() {
    useUserStore().startPolling();
    this.connectWebSocket();
    this._cmdResultInterval = setInterval(() => this.pollCommandResult(), 400);
    this.pollModemStatus();
    this._modemStatusInterval = setInterval(() => this.pollModemStatus(), 15000);
  },
  beforeUnmount() {
    useUserStore().stopPolling();
    if (this._ws) { this._ws.onclose = null; this._ws.close(); }
    if (this._wsReconnectTimeout) clearTimeout(this._wsReconnectTimeout);
    if (this._cmdResultInterval) clearInterval(this._cmdResultInterval);
    if (this._modemStatusInterval) clearInterval(this._modemStatusInterval);
    if (this._guestRefreshTimer) clearTimeout(this._guestRefreshTimer);
  },
});
</script>

// components/CCRemoteController.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import * as THREE from 'three'
import { useWorldStore } from '@/store/useWorld'
import { useWorldViewStore } from '@/store/useWorldView'
import { useUserStore } from '@/store/useUser'
import ComputerPanel from './computers/ComputerPanel'
import InventoryView from './Inventory'
import BlockNameDisplay from './staticGui/BlockNameDisplay'
import Scene from './Scene'
import KeyboardBindings from './computers/turtles/KeyboardBindings'
import AdminPanel from './staticGui/AdminPanel'
import OperatorRequest from './staticGui/OperatorRequest'
import BlockTransparency from './staticGui/BlockTransparency'
import RenderFilters from './staticGui/RenderFilters'

interface FloatingPanel { id: number; x: number; y: number }

export default function CCRemoteController() {
  const isLoading = useWorldStore(s => s.isLoading)
  const computers = useWorldStore(s => s.computers)
  const modemServerId = useWorldStore(s => s.modemServerId)
  const onlineStatus = useWorldStore(s => s.onlineStatus)
  const selectedInventory = useWorldViewStore(s => s.selectedInventory)
  const selectedInventorySize = useWorldViewStore(s => s.selectedInventorySize)
  const selectedInventoryPos = useWorldViewStore(s => s.selectedInventoryPos)
  const computerRangeXZ = useWorldViewStore(s => s.computerRangeXZ)
  const userLoaded = useUserStore(s => s.loaded)
  const isOperator = useUserStore(s => s.isOperator)
  const isAdmin = useUserStore(s => s.isAdmin)

  const [manualX, setManualX] = useState<number | null>(null)
  const [manualZ, setManualZ] = useState<number | null>(null)
  const [isGuest, setIsGuest] = useState(false)
  const [guestRefreshDisabled, setGuestRefreshDisabled] = useState(false)

  const [tabOrder, setTabOrder] = useState<number[]>([])
  const [floatingPanels, setFloatingPanels] = useState<FloatingPanel[]>([])
  const [panelZIndexes, setPanelZIndexes] = useState<Record<number, number>>({})
  const topZRef = useRef(200)
  const draggedIdxRef = useRef<number | null>(null)
  const [addOpen, setAddOpen] = useState(false)
  const [addSearch, setAddSearch] = useState('')
  const addRef = useRef<HTMLDivElement>(null)
  const [contextMenu, setContextMenu] = useState<{ id: number; x: number; y: number } | null>(null)
  const contextMenuRef = useRef<HTMLDivElement>(null)

  const wsRef = useRef<WebSocket | null>(null)
  const wsBackoffRef = useRef(1000)
  const wsReconnectRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const wsInitialStateLoadedRef = useRef(false)
  const cmdResultIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const modemStatusIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const guestRefreshTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const renderFiltersRef = useRef<{ setOpen: (v: boolean) => void } | null>(null)
  const blockTransparencyRef = useRef<{ setOpen: (v: boolean) => void } | null>(null)
  const adminPanelRef = useRef<{ setOpen: (v: boolean) => void } | null>(null)

  const selectedComputerId = useWorldViewStore(s => s.selectedComputerId)
  const prevSelectedIdRef = useRef(selectedComputerId)
  useEffect(() => {
    if (selectedComputerId === prevSelectedIdRef.current) return
    prevSelectedIdRef.current = selectedComputerId
    if (selectedComputerId === -1) return
    useWorldViewStore.setState({ manualCenter: null })
    const wv = useWorldViewStore.getState()
    if (computerRangeXZ !== null) {
      wv.regenerateSceneFromBlocks()
    } else {
      wv.focusOnComputer(selectedComputerId)
    }
  }, [selectedComputerId, computerRangeXZ]) // eslint-disable-line react-hooks/exhaustive-deps

  const computerIds = Object.keys(computers).map(Number).sort((a, b) => a - b)

  // Keep tabOrder in sync with computerIds: remove stale only, never auto-add
  useEffect(() => {
    const currSet = new Set(computerIds)
    setTabOrder(prev => prev.filter(id => currSet.has(id)))
    setFloatingPanels(prev => prev.filter(p => computerIds.includes(p.id)))
  }, [JSON.stringify(computerIds)]) // eslint-disable-line react-hooks/exhaustive-deps

  // Close add-dropdown on outside click
  useEffect(() => {
    if (!addOpen) return
    function handleClick(e: MouseEvent) {
      if (addRef.current && !addRef.current.contains(e.target as Node)) {
        setAddOpen(false)
        setAddSearch('')
      }
    }
    window.addEventListener('mousedown', handleClick)
    return () => window.removeEventListener('mousedown', handleClick)
  }, [addOpen])

  // Close context menu on outside click or Escape
  useEffect(() => {
    if (!contextMenu) return
    function handleClick(e: MouseEvent) {
      if (contextMenuRef.current && !contextMenuRef.current.contains(e.target as Node))
        setContextMenu(null)
    }
    function handleKey(e: KeyboardEvent) {
      if (e.key === 'Escape') setContextMenu(null)
    }
    window.addEventListener('mousedown', handleClick)
    window.addEventListener('keydown', handleKey)
    return () => {
      window.removeEventListener('mousedown', handleClick)
      window.removeEventListener('keydown', handleKey)
    }
  }, [contextMenu])

  function onTabDragStart(idx: number) {
    draggedIdxRef.current = idx
  }

  function onTabDragOver(e: React.DragEvent, idx: number) {
    e.preventDefault()
    if (draggedIdxRef.current === null || draggedIdxRef.current === idx) return
    setTabOrder(prev => {
      const next = [...prev]
      const [removed] = next.splice(draggedIdxRef.current!, 1)
      next.splice(idx, 0, removed)
      draggedIdxRef.current = idx
      return next
    })
  }

  function onTabDragEnd() {
    draggedIdxRef.current = null
  }

  function detachTab(id: number) {
    setFloatingPanels(prev => {
      if (prev.some(p => p.id === id)) return prev
      const offset = prev.length * 24
      return [...prev, { id, x: 320 + offset, y: 60 + offset }]
    })
    topZRef.current += 1
    setPanelZIndexes(prev => ({ ...prev, [id]: topZRef.current }))
    if (selectedComputerId === id) {
      useWorldViewStore.setState({ selectedComputerId: -1 })
    }
  }

  function dockPanel(id: number) {
    setFloatingPanels(prev => prev.filter(p => p.id !== id))
  }

  function bringToFront(id: number) {
    topZRef.current += 1
    setPanelZIndexes(prev => ({ ...prev, [id]: topZRef.current }))
    useWorldViewStore.setState({ selectedComputerId: id })
  }

  function addTab(id: number) {
    setTabOrder(prev => prev.includes(id) ? prev : [...prev, id])
    setAddOpen(false)
    setAddSearch('')
    useWorldViewStore.setState({ selectedComputerId: id })
  }

  function closeTab(id: number) {
    setTabOrder(prev => prev.filter(t => t !== id))
    setFloatingPanels(prev => prev.filter(p => p.id !== id))
    if (selectedComputerId === id) useWorldViewStore.setState({ selectedComputerId: -1 })
  }

  function startPanelDrag(e: React.MouseEvent, panelId: number) {
    e.preventDefault()
    const startX = e.clientX
    const startY = e.clientY
    const panel = floatingPanels.find(p => p.id === panelId)
    if (!panel) return
    const initX = panel.x
    const initY = panel.y
    function onMove(ev: MouseEvent) {
      setFloatingPanels(prev => prev.map(p =>
        p.id === panelId ? { ...p, x: initX + ev.clientX - startX, y: initY + ev.clientY - startY } : p
      ))
    }
    function onUp() {
      window.removeEventListener('mousemove', onMove)
      window.removeEventListener('mouseup', onUp)
    }
    window.addEventListener('mousemove', onMove)
    window.addEventListener('mouseup', onUp)
  }

  function applyManualCenter() {
    const wv = useWorldViewStore.getState()
    if (manualX !== null && manualZ !== null) {
      useWorldViewStore.setState({ manualCenter: { x: manualX, z: manualZ } })
      wv.setCameraFocus(new THREE.Vector3(manualX, 64, manualZ))
    } else {
      useWorldViewStore.setState({ manualCenter: null })
    }
    wv.regenerateSceneFromBlocks()
  }

  function pollCommandResult() {
    const view = useWorldViewStore.getState()
    const w = useWorldStore.getState()
    if (view.selectedComputerId === -1) return
    fetch(w.apiURL + 'getCommandResult', {
      method: 'POST',
      mode: 'cors',
      headers: { 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json' },
      body: JSON.stringify({ computerId: view.selectedComputerId, getOnlyLatest: true }),
    })
      .then(res => res.json())
      .then(data => {
        if (data.result) {
          const existing = useWorldStore.getState().commandResult[data.computerId]
          if (existing !== data.result.ret) {
            useWorldStore.setState(s => ({ commandResult: { ...s.commandResult, [data.computerId]: data.result.ret } }))
          }
        }
      })
      .catch(() => {})
  }

  async function pollModemStatus() {
    const w = useWorldStore.getState()
    const res = await fetch(w.apiURL + 'modem/id').catch(() => null)
    if (!res || !res.ok) return
    const data = await res.json().catch(() => null)
    if (data) {
      const newId = data.id ?? null
      if (useWorldStore.getState().modemServerId !== newId) useWorldStore.setState({ modemServerId: newId })
    }
  }

  function startGuestCooldown(seconds: number) {
    setGuestRefreshDisabled(true)
    if (guestRefreshTimerRef.current) clearTimeout(guestRefreshTimerRef.current)
    guestRefreshTimerRef.current = setTimeout(() => {
      setGuestRefreshDisabled(false)
      guestRefreshTimerRef.current = null
    }, seconds * 1000)
  }

  async function loadGuestState() {
    const w = useWorldStore.getState()
    const res = await fetch('/api/state').catch(() => null)
    if (!res) return
    if (res.status === 429) {
      const data = await res.json().catch(() => ({}))
      startGuestCooldown(data.retryAfter ?? 30)
      return
    }
    const data = await res.json().catch(() => null)
    if (!data) return
    w.setComputerStatus(data.computers)
    useWorldStore.setState({ blocks: data.world.blocks })
    const freshComputers = useWorldStore.getState().computers
    const selId = useWorldViewStore.getState().selectedComputerId
    const hasCoords = (c: { loc?: { x?: unknown; y?: unknown; z?: unknown } | null } | undefined) =>
      c?.loc != null && c.loc.x != null && c.loc.y != null && c.loc.z != null
    if (!hasCoords(freshComputers[selId])) {
      const entry = Object.entries(freshComputers).find(([, c]) => hasCoords(c))
      if (entry) {
        const autoId = Number(entry[0])
        useWorldViewStore.setState({ selectedComputerId: autoId })
        setTabOrder(prev => prev.includes(autoId) ? prev : [...prev, autoId])
      }
    }
    // Get a fresh reference so we call the real Scene callbacks, not the initial no-ops.
    const view = useWorldViewStore.getState()
    view.regenerateSceneFromBlocks()
    view.render()
    useWorldStore.setState({ isLoading: false })
    startGuestCooldown(30)
  }

  function connectWebSocket() {
    const w = useWorldStore.getState()
    const wsUrl = w.URL
      ? w.URL.replace(/^http/, 'ws')
      : `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}/ws`

    const ws = new WebSocket(wsUrl)
    wsRef.current = ws

    ws.onopen = () => {
      wsBackoffRef.current = 1000
      console.log('[ws] WebSocket connected to', wsUrl)
      if (!wsInitialStateLoadedRef.current) {
        wsInitialStateLoadedRef.current = true
        loadGuestState()
      }
    }

    ws.onmessage = (event) => {
      const data = JSON.parse(event.data)
      const w = useWorldStore.getState()
      const view = useWorldViewStore.getState()
      if (data.onlineStatus) {
        const current = useWorldStore.getState().onlineStatus
        const updates: Record<string, boolean> = {}
        for (const [id, online] of Object.entries(data.onlineStatus as Record<string, boolean>)) {
          if (current[id] !== online) updates[id] = online
        }
        if (Object.keys(updates).length > 0)
          useWorldStore.setState(s => ({ onlineStatus: { ...s.onlineStatus, ...updates } }))
      }
      if (data.state) {
        const alreadyCurrent = data.state.lastTransactionId === w.lastTransactionId
        if (!alreadyCurrent) {
          w.setComputerStatus(data.state.computers)
          useWorldStore.setState({ blocks: data.state.world.blocks, lastTransactionId: data.state.lastTransactionId })
          const freshComputers = useWorldStore.getState().computers
          const hasCoords = (c: { loc?: { x?: unknown; y?: unknown; z?: unknown } | null } | undefined) =>
            c?.loc != null && c.loc.x != null && c.loc.y != null && c.loc.z != null
          if (!hasCoords(freshComputers[view.selectedComputerId])) {
            const entry = Object.entries(freshComputers).find(([, c]) => hasCoords(c))
            if (entry) {
        const autoId = Number(entry[0])
        useWorldViewStore.setState({ selectedComputerId: autoId })
        setTabOrder(prev => prev.includes(autoId) ? prev : [...prev, autoId])
      }
          }
          view.regenerateSceneFromBlocks()
        }
      } else if (data.transactions) {
        w.applyTransactions(data.transactions)
      }
      view.render()
      if (w.isLoading) useWorldStore.setState({ isLoading: false })
    }

    ws.onclose = (event) => {
      console.log(`[ws] WebSocket closed — code: ${event.code}, reason: '${event.reason}', wasClean: ${event.wasClean}`)
      if (event.code === 4401) {
        console.log("Guest Mode");
        setIsGuest(true)
        if (cmdResultIntervalRef.current) { clearInterval(cmdResultIntervalRef.current); cmdResultIntervalRef.current = null }
        loadGuestState()
        return
      }
      const delay = wsBackoffRef.current
      wsBackoffRef.current = Math.min(wsBackoffRef.current * 2, 10000)
      wsReconnectRef.current = setTimeout(connectWebSocket, delay)
    }

    ws.onerror = () => ws.close()
  }

  useEffect(() => {
    useUserStore.getState().startPolling()
    connectWebSocket()
    cmdResultIntervalRef.current = setInterval(pollCommandResult, 1000)
    pollModemStatus()
    modemStatusIntervalRef.current = setInterval(pollModemStatus, 15000)
    return () => {
      useUserStore.getState().stopPolling()
      if (wsRef.current) { wsRef.current.onclose = null; wsRef.current.close() }
      if (wsReconnectRef.current) clearTimeout(wsReconnectRef.current)
      if (cmdResultIntervalRef.current) clearInterval(cmdResultIntervalRef.current)
      if (modemStatusIntervalRef.current) clearInterval(modemStatusIntervalRef.current)
      if (guestRefreshTimerRef.current) clearTimeout(guestRefreshTimerRef.current)
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const modemOnline = modemServerId !== null

  function computerLabel(id: number) {
    const c = computers[id]
    if (!c) return String(id)
    const typeLabel = c.type === 'minecart' ? 'Minecart' : c.type === 'modem' ? 'Modem' : 'Turtle'
    const modemSuffix = c.type === 'modem' ? (modemOnline ? ' [online]' : ' [offline]') : ''
    const statusSuffix = c.type !== 'modem' ? `${c.via_modem ? ' 📡' : ''}${c.sleep_mode ? ' 💤' : ''}${onlineStatus[id] ? ' [online]' : ' [offline]'}` : ''
    return `${typeLabel} ${id}${modemSuffix}${statusSuffix} : ${c.label ?? ''}`
  }

  function tabLabel(id: number) {
    const c = computers[id]
    if (!c) return `#${id}`
    const typeLabel = c.type === 'minecart' ? 'MC' : c.type === 'modem' ? 'Mdm' : 'T'
    const online = c.type === 'modem' ? modemOnline : !!onlineStatus[id]
    const statusDot = online ? '●' : '○'
    const name = c.label ? ` ${c.label}` : ` #${id}`
    return `${statusDot} ${typeLabel}${name}`
  }

  const floatingIds = new Set(floatingPanels.map(p => p.id))
  const dockedSelectedId = floatingIds.has(selectedComputerId) ? -1 : selectedComputerId

  return (
    <div style={{ position: 'absolute', display: 'grid', userSelect: 'none', pointerEvents: 'none' }}>
      {isLoading && (
        <h1 style={{ position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%,-50%)', color: 'white' }}>
          LOADING ... (depending on the number of blocks this might take some seconds)
        </h1>
      )}

      <div style={{ display: 'flex', flexDirection: 'row', alignItems: 'flex-start', gap: 8, padding: 10, position: 'relative', zIndex: 1 }}>
        {/* Panel Left */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 6, minWidth: 240, background: 'rgb(30,30,30)', border: '1px solid rgb(70,70,70)', borderRadius: 6, padding: '8px 12px', pointerEvents: 'auto' }}>
          <a href="/api/home" style={{ color: 'darkgray', fontSize: '0.85em', textDecoration: 'none' }}>← turkeyblock.org</a>
          <div style={{ fontSize: '0.75em', letterSpacing: '0.03em', color: modemOnline ? 'rgb(80,200,80)' : 'rgb(120,120,120)' }}>
            📡 Modem: {modemOnline ? `online (id ${modemServerId})` : 'offline'}
          </div>

          {/* Tab strip */}
          <div style={{ display: 'flex', flexDirection: 'row', flexWrap: 'wrap', gap: 2, marginBottom: 2, alignItems: 'flex-start' }}>
            {tabOrder.map((id, idx) => {
              const isFloating = floatingIds.has(id)
              const isSelected = selectedComputerId === id && !isFloating
              return (
                <div
                  key={id}
                  draggable
                  onDragStart={() => onTabDragStart(idx)}
                  onDragOver={e => onTabDragOver(e, idx)}
                  onDragEnd={onTabDragEnd}
                  onClick={() => {
                    if (isFloating) {
                      bringToFront(id)
                    } else {
                      useWorldViewStore.setState({ selectedComputerId: isSelected ? -1 : id })
                    }
                  }}
                  onContextMenu={e => { e.preventDefault(); setContextMenu({ id, x: e.clientX, y: e.clientY }) }}
                  title={computerLabel(id)}
                  style={{
                    display: 'flex', alignItems: 'center', gap: 3,
                    padding: '0 7px', borderRadius: 4, height: 22, boxSizing: 'border-box',
                    background: isSelected ? 'rgb(60,60,60)' : isFloating ? 'rgb(35,45,55)' : 'rgb(42,42,42)',
                    border: isSelected
                      ? '1px solid rgb(100,100,100)'
                      : isFloating
                        ? '1px solid rgb(60,90,120)'
                        : '1px solid rgb(58,58,58)',
                    cursor: 'pointer', fontSize: '0.72em',
                    color: isSelected ? 'rgb(220,220,220)' : isFloating ? 'rgb(100,150,200)' : 'rgb(140,140,140)',
                    whiteSpace: 'nowrap', userSelect: 'none',
                    maxWidth: 160, overflow: 'hidden', textOverflow: 'ellipsis',
                  }}
                >
                  <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', flex: 1 }}>{tabLabel(id)}</span>
                  {isFloating && <span style={{ flexShrink: 0, opacity: 0.7, fontSize: '0.85em' }}>↗</span>}
                </div>
              )
            })}

            {/* Add-tab button + searchable dropdown */}
            {(() => {
              const tabSet = new Set(tabOrder)
              const available = computerIds.filter(id => !tabSet.has(id))
              const filtered = available.filter(id => {
                if (!addSearch) return true
                return computerLabel(id).toLowerCase().includes(addSearch.toLowerCase()) || String(id).includes(addSearch)
              })
              return (
                <div ref={addRef} style={{ position: 'relative', flexShrink: 0 }}>
                  <div
                    onClick={() => setAddOpen(o => !o)}
                    style={{
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      width: 22, height: 22, boxSizing: 'border-box', borderRadius: 4,
                      background: addOpen ? 'rgb(55,55,55)' : 'rgb(42,42,42)',
                      border: '1px solid rgb(58,58,58)',
                      cursor: 'pointer', fontSize: '1em', color: 'rgb(140,140,140)', userSelect: 'none',
                    }}
                    title="Add computer tab"
                  >+</div>
                  {addOpen && (
                    <div style={{
                      position: 'absolute', top: '100%', left: 0, marginTop: 2,
                      background: 'rgb(35,35,35)', border: '1px solid rgb(70,70,70)',
                      borderRadius: 4, zIndex: 500, minWidth: 210,
                      boxShadow: '0 4px 12px rgba(0,0,0,0.5)',
                    }}>
                      <input
                        autoFocus
                        value={addSearch}
                        onChange={e => setAddSearch(e.target.value)}
                        placeholder="Search computers..."
                        style={{
                          width: '100%', padding: '5px 8px', boxSizing: 'border-box',
                          background: 'rgb(42,42,42)', border: 'none',
                          borderBottom: '1px solid rgb(55,55,55)',
                          color: 'darkgray', fontSize: '0.78em', outline: 'none',
                          borderRadius: '4px 4px 0 0',
                        }}
                      />
                      <div style={{ maxHeight: 200, overflowY: 'auto' }}>
                        {filtered.length === 0 && (
                          <div style={{ padding: '6px 8px', fontSize: '0.75em', color: 'gray' }}>
                            {available.length === 0 ? 'All computers added' : 'No matches'}
                          </div>
                        )}
                        {filtered.map(id => (
                          <div
                            key={id}
                            onClick={() => addTab(id)}
                            style={{ padding: '5px 8px', fontSize: '0.78em', color: 'darkgray', cursor: 'pointer', borderBottom: '1px solid rgb(45,45,45)' }}
                            onMouseOver={e => (e.currentTarget.style.background = 'rgb(50,50,50)')}
                            onMouseOut={e => (e.currentTarget.style.background = '')}
                          >{computerLabel(id)}</div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )
            })()}
          </div>

          {dockedSelectedId === -1 && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
              <span style={{ fontSize: '0.75em', color: 'gray', textTransform: 'uppercase', letterSpacing: '0.04em', flexShrink: 0 }}>Center</span>
              <input type="number" placeholder="X" value={manualX ?? ''} onChange={e => setManualX(e.target.value ? Number(e.target.value) : null)} onBlur={applyManualCenter}
                style={{ width: 64, padding: '2px 4px', borderRadius: 4, border: '1px solid rgb(70,70,70)', background: 'rgb(40,40,40)', color: 'darkgray', fontSize: '0.85em', textAlign: 'center' }} />
              <input type="number" placeholder="Z" value={manualZ ?? ''} onChange={e => setManualZ(e.target.value ? Number(e.target.value) : null)} onBlur={applyManualCenter}
                style={{ width: 64, padding: '2px 4px', borderRadius: 4, border: '1px solid rgb(70,70,70)', background: 'rgb(40,40,40)', color: 'darkgray', fontSize: '0.85em', textAlign: 'center' }} />
            </div>
          )}

          {dockedSelectedId !== -1 && <ComputerPanel computerId={dockedSelectedId} />}
        </div>

        {/* Panel Right */}
        <div style={{ display: 'flex', flexDirection: 'row', alignItems: 'flex-start', gap: 6 }}>
          <RenderFilters ref={renderFiltersRef} onOpened={() => { blockTransparencyRef.current?.setOpen(false); adminPanelRef.current?.setOpen(false) }} />
          <BlockTransparency ref={blockTransparencyRef} onOpened={() => { renderFiltersRef.current?.setOpen(false); adminPanelRef.current?.setOpen(false) }} />
          {isGuest && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'rgb(30,30,30)', border: '1px solid rgb(70,70,70)', borderRadius: 6, padding: '6px 10px' }}>
              <a href="/api/signin" style={{ color: 'darkgray', fontSize: '0.85em', textDecoration: 'none' }}>Sign in</a>
              <button
                disabled={guestRefreshDisabled}
                onClick={() => !guestRefreshDisabled && loadGuestState()}
                style={{ padding: '3px 10px', borderRadius: 4, border: 'none', background: 'rgb(52,52,52)', color: 'darkgray', cursor: 'pointer', fontSize: '0.85em', opacity: guestRefreshDisabled ? 0.5 : 1 }}
              >
                {guestRefreshDisabled ? 'Refreshed ✓' : 'Refresh'}
              </button>
            </div>
          )}
          {userLoaded && isOperator && !isAdmin && (
            <span style={{ fontSize: '0.75em', color: 'rgb(80,180,80)', letterSpacing: '0.05em', textTransform: 'uppercase' }}>Operator</span>
          )}
          {userLoaded && !isOperator && !isGuest && <OperatorRequest />}
          {isAdmin && <AdminPanel ref={adminPanelRef} onOpened={() => { renderFiltersRef.current?.setOpen(false); blockTransparencyRef.current?.setOpen(false) }} />}
        </div>
      </div>

      {selectedInventory && (
        <div>
          <InventoryView
            inventory={selectedInventory}
            inventorySize={selectedInventorySize}
            computerId={selectedComputerId}
            blockPos={selectedInventoryPos}
          />
        </div>
      )}

      <Scene />
      <KeyboardBindings />
      <BlockNameDisplay />

      {/* Tab right-click context menu */}
      {contextMenu && (
        <div
          ref={contextMenuRef}
          style={{
            position: 'fixed', left: contextMenu.x, top: contextMenu.y,
            background: 'rgb(35,35,35)', border: '1px solid rgb(70,70,70)',
            borderRadius: 4, zIndex: 1000, minWidth: 150,
            boxShadow: '0 4px 12px rgba(0,0,0,0.5)', pointerEvents: 'auto',
          }}
        >
          {(() => {
            const isFloating = floatingIds.has(contextMenu.id)
            const menuItem = (label: string, onClick: () => void, danger = false) => (
              <div
                onClick={onClick}
                style={{ padding: '6px 10px', fontSize: '0.78em', cursor: 'pointer', color: danger ? 'rgb(200,100,100)' : 'darkgray', borderBottom: '1px solid rgb(45,45,45)' }}
                onMouseOver={e => (e.currentTarget.style.background = 'rgb(50,50,50)')}
                onMouseOut={e => (e.currentTarget.style.background = '')}
              >{label}</div>
            )
            return <>
              {!isFloating && menuItem('↗ Detach to float', () => { detachTab(contextMenu.id); setContextMenu(null) })}
              {isFloating && menuItem('↙ Dock panel', () => { dockPanel(contextMenu.id); setContextMenu(null) })}
              {menuItem('× Close tab', () => { closeTab(contextMenu.id); setContextMenu(null) }, true)}
            </>
          })()}
        </div>
      )}

      {/* Floating panels */}
      {floatingPanels.map(panel => (
        <div
          key={panel.id}
          onMouseDown={() => bringToFront(panel.id)}
          style={{
            position: 'fixed', left: panel.x, top: panel.y,
            background: 'rgb(30,30,30)', border: '1px solid rgb(70,70,70)',
            borderRadius: 6, padding: '0 12px 10px',
            zIndex: panelZIndexes[panel.id] ?? 200,
            pointerEvents: 'auto', userSelect: 'none',
            minWidth: 240, maxHeight: '90vh', overflowY: 'auto',
            boxShadow: '0 4px 24px rgba(0,0,0,0.6)',
          }}
        >
          {/* Drag handle / title bar */}
          <div
            onMouseDown={e => startPanelDrag(e, panel.id)}
            style={{
              display: 'flex', justifyContent: 'space-between', alignItems: 'center',
              padding: '8px 0 6px', marginBottom: 6,
              borderBottom: '1px solid rgb(50,50,50)',
              cursor: 'grab',
            }}
          >
            <span style={{ fontSize: '0.75em', color: 'darkgray', fontWeight: 'bold', pointerEvents: 'none' }}>
              {computerLabel(panel.id)}
            </span>
            <span
              onMouseDown={e => e.stopPropagation()}
              onClick={() => dockPanel(panel.id)}
              title="Dock (close floating panel)"
              style={{ fontSize: '1.1em', color: 'gray', cursor: 'pointer', lineHeight: 1, paddingLeft: 10, flexShrink: 0 }}
            >×</span>
          </div>
          <ComputerPanel computerId={panel.id} />
        </div>
      ))}
    </div>
  )
}
