// src/components/PlayerPanel.vue
<template>
  <div class="panel">
    <div v-if="computer.loc" class="location">
      📍 {{ computer.loc.x }}, {{ computer.loc.y }}, {{ computer.loc.z }}
    </div>
    <div v-else class="location no-gps">GPS unavailable</div>
    <div class="actions">
      <button
        :class="{ missing: computer.peripherals && !computer.peripherals.includes('plethora:scanner') }"
        @click="world.sendCommand(computerId, 'return papi.scan()')"
      >Block Scan</button>
      <button @click="worldView.focusOnComputer(computerId)">Focus Camera</button>
      <button
        :class="{ active: worldView.followedComputer.computerId === computerId }"
        @click="worldView.followComputer(computerId)"
      >Toggle Follow</button>
      <button @click="world.sendStopSignal(computerId)">🛑 Stop 🛑</button>
    </div>

    <div v-if="computer.entities && computer.entities.length > 0" class="section">
      <div class="section-title">Nearby Entities ({{ computer.entities.length }})</div>
      <div class="entity-list">
        <div v-for="e in computer.entities" :key="e.id" class="entity-row">
          <span class="entity-name">{{ e.name }}</span>
          <span class="entity-pos">{{ e.x.toFixed(1) }}, {{ e.y.toFixed(1) }}, {{ e.z.toFixed(1) }}</span>
        </div>
      </div>
    </div>

    <LuaTerminal :computerId="computerId" />
  </div>
</template>

<style scoped>
.panel {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.location {
  font-size: 0.85em;
  color: darkgray;
  padding: 2px 4px;
}
.no-gps {
  color: rgb(160, 100, 100);
  font-style: italic;
}
.actions {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 2px;
}
button {
  padding: 8px 0;
  border-radius: 4px;
  background-color: #383e42;
  color: darkgray;
}
button.active {
  background-color: rgb(50, 100, 50);
  color: rgb(150, 220, 150);
}
button.missing {
  background-color: rgba(140, 30, 30, 0.6);
  color: rgb(255, 110, 110);
}
.section {
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.section-title {
  font-size: 0.75em;
  color: gray;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}
.entity-list {
  display: flex;
  flex-direction: column;
  gap: 2px;
  max-height: 120px;
  overflow-y: auto;
}
.entity-row {
  display: flex;
  justify-content: space-between;
  font-size: 0.8em;
  color: darkgray;
  gap: 8px;
}
.entity-name {
  color: rgb(180, 180, 220);
  white-space: nowrap;
}
.entity-pos {
  color: gray;
  font-size: 0.9em;
}
</style>

<script lang="ts">
import { defineComponent, computed } from "vue";
import { useWorldStore } from "../store/useWorld";
import { useWorldViewStore } from "../store/useWorldView";
import LuaTerminal from "./LuaTerminal.vue";

export default defineComponent({
  components: { LuaTerminal },
  props: {
    computerId: {
      required: true,
      type: Number,
    },
  },
  setup(props) {
    const world = useWorldStore();
    const worldView = useWorldViewStore();
    const computer = computed(() => world.computers[props.computerId]);
    return { world, worldView, computer };
  },
});
</script>

// components/computers/player/PlayerPanel.tsx
'use client'

import { useWorldStore } from '@/store/useWorld'
import { useWorldViewStore } from '@/store/useWorldView'
import LuaTerminal from '../LuaTerminal'
import ComputerLocation from '../ComputerLocation'
import ButtonGrid from '../ButtonGrid'
import ScrollList from '../ScrollList'
import { btn, activeBtn, missingBtn, colors } from '../computerStyles'

interface Props { computerId: number }

export default function PlayerPanel({ computerId }: Props) {
  const computer = useWorldStore(s => s.computers[computerId])
  const sendCommand = useWorldStore(s => s.sendCommand)
  const sendStopSignal = useWorldStore(s => s.sendStopSignal)
  const focusOnComputer = useWorldViewStore(s => s.focusOnComputer)
  const followComputer = useWorldViewStore(s => s.followComputer)
  const followedComputer = useWorldViewStore(s => s.followedComputer)

  if (!computer) return null

  const hasScanner = computer.peripherals?.includes('plethora:scanner')
  const isFollowing = followedComputer.computerId === computerId

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
      <ComputerLocation loc={computer.loc ?? null} showUnavailable />
      <ButtonGrid>
        <button style={hasScanner ? btn : missingBtn} onClick={() => sendCommand(computerId, 'return papi.scan()')}>Block Scan</button>
        <button style={btn} onClick={() => focusOnComputer(computerId)}>Focus Camera</button>
        <button style={isFollowing ? activeBtn : btn} onClick={() => followComputer(computerId)}>Toggle Follow</button>
        <button style={btn} onClick={() => sendStopSignal(computerId)}>🛑 Stop 🛑</button>
      </ButtonGrid>

      {computer.entities && computer.entities.length > 0 && (
        <ScrollList label="Nearby Entities" count={computer.entities.length}>
          {computer.entities.map(e => (
            <div key={e.id} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8em', color: colors.text, gap: 8 }}>
              <span style={{ color: colors.textName, whiteSpace: 'nowrap' }}>{e.name}</span>
              <span style={{ color: 'gray', fontSize: '0.9em' }}>{e.x.toFixed(1)}, {e.y.toFixed(1)}, {e.z.toFixed(1)}</span>
            </div>
          ))}
        </ScrollList>
      )}

      <LuaTerminal computerId={computerId} />
    </div>
  )
}
