// src/components/FuelGauge.vue
<template>
  <meter
    class="fuel-gauge"
    :value="world.computers[computerId].fuelLevel"
    :min="0"
    :max="world.computers[computerId].fuelLimit"
  >
    TEST
  </meter>
</template>

<style scoped>
meter {
  height: 20px;
  width: 100%;
}

meter::after {
  position: relative;
  content: attr(value);
  top: -18px;
  transform: translateX(-50%);
  transform: translateY(-50%);
  color: lime;
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import { useWorldStore } from "../store/useWorld";

export default defineComponent({
  setup() {
    const world = useWorldStore();
    return { world };
  },
  props: {
    computerId: {
      required: true,
      type: Number,
    },
  },
});
</script>

// components/computers/turtles/FuelGauge.tsx
'use client'

import { useWorldStore } from '@/store/useWorld'

interface Props { computerId: number }

export default function FuelGauge({ computerId }: Props) {
  const computer = useWorldStore(s => s.computers[computerId])
  if (!computer) return null
  return (
    <meter
      style={{ height: 20, width: '100%' }}
      value={computer.fuelLevel}
      min={0}
      max={computer.fuelLimit}
    />
  )
}
