// src/components/TurtlePanel.vue
<template>
  <div class="panel">
    <template v-if="world.computers[computerId]?.type === 'minecart'">
      <MinecartPanel :computerId="computerId" />
    </template>
    <template v-else>
      <TurtleInventory :computerId="computerId"/>
      <FuelGauge :computerId="computerId"/>
      <MovementControl :computerId="computerId"/>
      <LuaTerminal :computerId="computerId"/>
    </template>
  </div>
</template>

<style scoped>
.panel {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import MovementControl from "./MovementControl.vue";
import TurtleInventory from "./TurtleInventory.vue";
import LuaTerminal from "./LuaTerminal.vue"
import MinecartPanel from "./MinecartPanel.vue";
import { useWorldStore } from "../store/useWorld";
import FuelGauge from "./FuelGauge.vue";
import { useWorldViewStore } from "../store/useWorldView";

export default defineComponent({
  setup() {
    const world = useWorldStore();
    const worldView = useWorldViewStore();
    return { world, worldView }
  },
  components: { MovementControl, TurtleInventory, LuaTerminal, FuelGauge, MinecartPanel },
  props: {
    computerId: {
      required: true,
      type: Number
    },
  },
  mounted() {
    this.worldView.followComputer(this.computerId);
  },
});
</script>

// components/computers/turtles/TurtlePanel.tsx
'use client'

import { useWorldStore } from '@/store/useWorld'
import ComputerLocation from '../ComputerLocation'
import TurtleInventory from './TurtleInventory'
import FuelGauge from './FuelGauge'
import MovementControl from './MovementControl'
import LuaTerminal from '../LuaTerminal'

interface Props { computerId: number }

export default function TurtlePanel({ computerId }: Props) {
  const computer = useWorldStore(s => s.computers[computerId])

  return (
    <>
      <ComputerLocation loc={computer?.loc} />
      <TurtleInventory computerId={computerId} />
      <FuelGauge computerId={computerId} />
      <MovementControl computerId={computerId} />
      <LuaTerminal computerId={computerId} />
    </>
  )
}
