// components/staticGui/AdminPanel.tsx
'use client'

import { useState, useEffect, useRef, forwardRef, useImperativeHandle } from 'react'
import { useWorldStore } from '@/store/useWorld'
import { useUserStore } from '@/store/useUser'
import { isStale } from '@/utils/stale'

interface Props { onOpened?: () => void }
export interface PanelHandle { setOpen: (v: boolean) => void }

const AdminPanel = forwardRef<PanelHandle, Props>(function AdminPanel({ onOpened }, ref) {
  const [open, setOpen] = useState(false)
  useImperativeHandle(ref, () => ({ setOpen }), [])
  const [pending, setPending] = useState<string[]>([])
  const [approved, setApproved] = useState<string[]>([])
  const [pendingIds, setPendingIds] = useState<{ id: string; ip: string; requestedAt: number }[]>([])
  const [approvedIds, setApprovedIds] = useState<string[]>([])
  const [allowByIp, setAllowByIp] = useState(true)
  const [operatorRequests, setOperatorRequests] = useState<{ sub: string; email: string; requestedAt: number }[]>([])
  const [operators, setOperators] = useState<{ sub: string; email: string | null }[]>([])
  const [clearingWorld, setClearingWorld] = useState(false)
  const pollHandle = useRef<ReturnType<typeof setTimeout> | null>(null)
  const computers = useWorldStore(s => s.computers)
  const removeComputer = useWorldStore(s => s.removeComputer)
  const clearBlocks = useWorldStore(s => s.clearBlocks)

  async function fetchAll() {
    try {
      const [ips, ids, requests, ops] = await Promise.all([
        fetch('/api/admin/computerIps').then(r => r.ok ? r.json() : null).catch(() => null),
        fetch('/api/admin/computerIds').then(r => r.ok ? r.json() : null).catch(() => null),
        fetch('/api/admin/operatorRequests').then(r => r.ok ? r.json() : null).catch(() => null),
        fetch('/api/admin/operators').then(r => r.ok ? r.json() : null).catch(() => null),
      ])
      if (ips) { setPending(ips.pending); setApproved(ips.approved) }
      if (ids) { setPendingIds(ids.pending); setApprovedIds(ids.approved); setAllowByIp(ids.allowByIp) }
      if (requests) setOperatorRequests(requests)
      if (ops) setOperators(ops)
    } finally {
      pollHandle.current = setTimeout(fetchAll, 30000)
    }
  }

  useEffect(() => {
    fetchAll()
    return () => { if (pollHandle.current) clearTimeout(pollHandle.current) }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  function toggle() {
    const next = !open
    setOpen(next)
    if (next) onOpened?.()
  }

  async function post(url: string, body?: object) {
    await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined })
    await fetchAll()
  }

  async function handleSetAllowByIp(enabled: boolean) {
    await fetch('/api/admin/setAllowByIp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ enabled }) })
    await fetchAll()
  }

  async function handleApproveOperator(sub: string) {
    await fetch('/api/admin/approveOperator', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sub }) })
    await Promise.all([fetchAll(), useUserStore.getState().fetchMe()])
  }

  async function handleDenyOperator(sub: string) {
    await fetch('/api/admin/denyOperatorRequest', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sub }) })
    await Promise.all([fetchAll(), useUserStore.getState().fetchMe()])
  }

  async function handleRevokeOperator(sub: string) {
    await fetch('/api/admin/revokeOperator', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sub }) })
    await Promise.all([fetchAll(), useUserStore.getState().fetchMe()])
  }

  async function deleteComputer(id: string | number) {
    await fetch('/api/admin/deleteComputer', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) })
    removeComputer(id)
    await fetchAll()
  }

  async function handleClearWorld() {
    setClearingWorld(true)
    await Promise.all([
      fetch('/api/admin/clearWorld', { method: 'POST' }).then(() => clearBlocks()),
      new Promise(r => setTimeout(r, 500)),
    ])
    setClearingWorld(false)
  }

  const panelStyle: React.CSSProperties = { position: 'relative', background: 'rgb(30,30,30)', border: '1px solid rgb(70,70,70)', borderRadius: 6, padding: '8px 12px' }
  const dropdownStyle: React.CSSProperties = { position: 'absolute', top: '100%', left: 0, zIndex: 100, background: 'rgb(30,30,30)', border: '1px solid rgb(70,70,70)', borderRadius: 6, padding: '8px 12px', minWidth: 220, marginTop: 2 }
  const toggleBtnStyle: React.CSSProperties = { background: 'none', border: 'none', color: 'gray', cursor: 'pointer', fontSize: '0.85em', padding: 0, textTransform: 'uppercase', letterSpacing: '0.05em' }
  const approveBtnStyle: React.CSSProperties = { padding: '2px 8px', borderRadius: 4, border: 'none', background: 'rgb(60,120,60)', color: 'white', cursor: 'pointer', fontSize: '0.8em' }
  const revokeBtnStyle: React.CSSProperties = { ...approveBtnStyle, background: 'rgb(120,50,50)' }
  const ipRowStyle: React.CSSProperties = { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 4, fontSize: '0.85em', color: 'darkgray' }
  const sectionH3: React.CSSProperties = { margin: '0 0 6px 0', fontSize: '0.85em', color: 'darkgray', textTransform: 'uppercase', letterSpacing: '0.05em' }
  const divider: React.CSSProperties = { border: 'none', borderTop: '1px solid rgb(60,60,60)', margin: '10px 0' }

  return (
    <div style={panelStyle}>
      <button onClick={toggle} style={toggleBtnStyle}>{open ? '▾' : '▸'} Admin</button>
      {open && (
        <div style={dropdownStyle}>
          {pending.length > 0 ? (
            <div>
              <p style={{ margin: '0 0 4px 0', fontSize: '0.75em', color: 'gray' }}>Pending</p>
              {pending.map(ip => (
                <div key={ip} style={ipRowStyle}>
                  <span>{ip}</span>
                  <div style={{ display: 'flex', gap: 4 }}>
                    <button style={approveBtnStyle} onClick={() => post('/api/admin/approveComputer', { ip })}>Approve</button>
                    <button style={revokeBtnStyle} onClick={() => post('/api/admin/denyComputer', { ip })}>Deny</button>
                  </div>
                </div>
              ))}
            </div>
          ) : <p style={{ margin: 0, fontSize: '0.8em', color: 'gray' }}>No pending turtles.</p>}

          {approved.length > 0 && (
            <div style={{ marginTop: 8 }}>
              <p style={{ margin: '0 0 4px 0', fontSize: '0.75em', color: 'gray' }}>Approved IPs</p>
              {approved.map(ip => (
                <div key={ip} style={ipRowStyle}>
                  <span>{ip}</span>
                  <button style={revokeBtnStyle} onClick={() => post('/api/admin/revokeComputer', { ip })}>Revoke</button>
                </div>
              ))}
            </div>
          )}

          <div style={{ marginTop: 8 }}>
            <p style={{ margin: '0 0 4px 0', fontSize: '0.75em', color: 'gray' }}>Pending Turtle IDs</p>
            {pendingIds.length > 0 ? pendingIds.map(t => (
              <div key={t.id} style={ipRowStyle}>
                <span style={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                  <span style={{ color: 'darkgray' }}>ID {t.id}</span>
                  <span style={{ fontSize: '0.75em', color: 'gray' }}>from {t.ip}</span>
                </span>
                <div style={{ display: 'flex', gap: 4 }}>
                  <button style={approveBtnStyle} onClick={() => post('/api/admin/approveComputerId', { id: t.id })}>Approve</button>
                  <button style={revokeBtnStyle} onClick={() => post('/api/admin/denyComputerId', { id: t.id })}>Deny</button>
                </div>
              </div>
            )) : <p style={{ margin: 0, fontSize: '0.8em', color: 'gray' }}>No pending turtle IDs.</p>}
          </div>

          {approvedIds.length > 0 && (
            <div style={{ marginTop: 8 }}>
              <p style={{ margin: '0 0 4px 0', fontSize: '0.75em', color: 'gray' }}>Approved Turtle IDs</p>
              {approvedIds.map(id => (
                <div key={id} style={ipRowStyle}>
                  <span>ID {id}</span>
                  <button style={revokeBtnStyle} onClick={() => post('/api/admin/revokeComputerId', { id })}>Revoke</button>
                </div>
              ))}
            </div>
          )}

          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginTop: 10 }}>
            <label style={{ fontSize: '0.8em', color: 'rgb(220,160,40)', fontWeight: 'bold' }}>⚠ Allow by IP (override)</label>
            <input type="checkbox" checked={allowByIp} onChange={e => handleSetAllowByIp(e.target.checked)} />
          </div>
          {allowByIp && (
            <p style={{ fontSize: '0.75em', color: 'rgb(200,130,30)', margin: '4px 0 0 0', padding: '4px 6px', background: 'rgb(60,40,10)', border: '1px solid rgb(120,80,20)', borderRadius: 4 }}>
              Any turtle from an approved IP can connect without individual ID approval.
            </p>
          )}

          <hr style={divider} />
          <h3 style={sectionH3}>Operator Requests</h3>
          {operatorRequests.length > 0 ? operatorRequests.map(r => (
            <div key={r.sub} style={ipRowStyle}>
              <span style={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                <span style={{ color: 'darkgray' }}>{r.email}</span>
                <span style={{ fontSize: '0.75em', color: 'gray' }}>{r.sub}</span>
              </span>
              <div style={{ display: 'flex', gap: 4 }}>
                <button style={approveBtnStyle} onClick={() => handleApproveOperator(r.sub)}>Approve</button>
                <button style={revokeBtnStyle} onClick={() => handleDenyOperator(r.sub)}>Deny</button>
              </div>
            </div>
          )) : <p style={{ margin: 0, fontSize: '0.8em', color: 'gray' }}>No pending requests.</p>}

          {operators.length > 0 && (
            <div style={{ marginTop: 8 }}>
              <h3 style={sectionH3}>Operators</h3>
              {operators.map(op => (
                <div key={op.sub} style={ipRowStyle}>
                  <span style={{ display: 'flex', flexDirection: 'row', gap: 6, alignItems: 'center' }}>
                    <span style={{ color: 'darkgray' }}>{op.email ?? '—'}</span>
                    <span style={{ fontSize: '0.75em', color: 'gray' }}>{op.sub}</span>
                  </span>
                  <button style={revokeBtnStyle} onClick={() => handleRevokeOperator(op.sub)}>Revoke</button>
                </div>
              ))}
            </div>
          )}

          <hr style={divider} />
          <h3 style={sectionH3}>Turtles</h3>
          {Object.keys(computers).length > 0 ? Object.entries(computers).map(([id, turtle]) => (
            <div key={id} style={ipRowStyle}>
              <span style={isStale(turtle) ? { color: 'rgb(180,140,40)' } : {}}>
                #{id} {turtle.label ?? ''}
                {isStale(turtle) && <span style={{ fontSize: '0.75em', opacity: 0.8 }}> (stale)</span>}
              </span>
              <button style={revokeBtnStyle} onClick={() => deleteComputer(id)}>Delete</button>
            </div>
          )) : <p style={{ margin: 0, fontSize: '0.8em', color: 'gray' }}>No tracked turtles.</p>}

          <hr style={divider} />
          <button
            disabled={clearingWorld}
            onClick={handleClearWorld}
            style={{ padding: 4, width: '100%', marginTop: 4, borderRadius: 4, border: 'none', cursor: 'pointer', background: clearingWorld ? 'rgb(80,40,10)' : 'rgb(140,60,20)', color: 'white', fontSize: '0.85em' }}
          >
            {clearingWorld ? '⟳ Clearing...' : 'Clear World'}
          </button>
        </div>
      )}
    </div>
  )
})

export default AdminPanel

// src/components/AdminPanel.vue
<template>
  <div class="admin-panel">
    <button class="toggle" @click="toggleOpen">{{ open ? '▾' : '▸' }} Admin</button>
    <div v-if="open" class="dropdown">

    <div v-if="pending.length">
      <p class="section-label">Pending</p>
      <div v-for="ip in pending" :key="ip" class="ip-row">
        <span>{{ ip }}</span>
        <div class="btn-group">
          <button @click="approve(ip)">Approve</button>
          <button class="revoke" @click="deny(ip)">Deny</button>
        </div>
      </div>
    </div>
    <p v-else class="empty">No pending turtles.</p>

    <div v-if="approved.length" style="margin-top: 8px;">
      <p class="section-label">Approved IPs</p>
      <div v-for="ip in approved" :key="ip" class="ip-row">
        <span>{{ ip }}</span>
        <button class="revoke" @click="revoke(ip)">Revoke</button>
      </div>
    </div>

    <div style="margin-top: 8px;">
      <p class="section-label">Pending Turtle IDs</p>
      <div v-if="pendingIds.length">
        <div v-for="t in pendingIds" :key="t.id" class="ip-row">
          <span class="request-info">
            <span class="email">ID {{ t.id }}</span>
            <span class="sub">from {{ t.ip }}</span>
          </span>
          <div class="btn-group">
            <button @click="approveTurtleId(t.id)">Approve</button>
            <button class="revoke" @click="denyTurtleId(t.id)">Deny</button>
          </div>
        </div>
      </div>
      <p v-else class="empty">No pending turtle IDs.</p>
    </div>

    <div v-if="approvedIds.length" style="margin-top: 8px;">
      <p class="section-label">Approved Turtle IDs</p>
      <div v-for="id in approvedIds" :key="id" class="ip-row">
        <span>ID {{ id }}</span>
        <button class="revoke" @click="revokeTurtleId(id)">Revoke</button>
      </div>
    </div>

    <div class="allow-by-ip-row" style="margin-top: 10px;">
      <label class="warning-label">⚠ Allow by IP (override)</label>
      <input type="checkbox" :checked="allowByIp" @change="setAllowByIp(($event.target as HTMLInputElement).checked)" />
    </div>
    <p class="warning-text" v-if="allowByIp">
      Any turtle from an approved IP can connect without individual ID approval.
    </p>

    <hr class="divider" />

    <h3>Operator Requests</h3>
    <div v-if="operatorRequests.length">
      <div v-for="r in operatorRequests" :key="r.sub" class="ip-row">
        <span class="request-info">
          <span class="email">{{ r.email }}</span>
          <span class="sub">{{ r.sub }}</span>
        </span>
        <div class="btn-group">
          <button @click="approveOperator(r.sub)">Approve</button>
          <button class="revoke" @click="denyOperator(r.sub)">Deny</button>
        </div>
      </div>
    </div>
    <p v-else class="empty">No pending requests.</p>

    <div v-if="operators.length" style="margin-top: 8px;">
      <h3>Operators</h3>
      <div v-for="op in operators" :key="op.sub" class="ip-row">
        <span class="op-info">
          <span class="email">{{ op.email ?? '—' }}</span>
          <span class="sub">{{ op.sub }}</span>
        </span>
        <button class="revoke" @click="revokeOperator(op.sub)">Revoke</button>
      </div>
    </div>

    <hr class="divider" />

    <h3>Turtles</h3>
    <div v-if="Object.keys(world.computers).length">
      <div v-for="(turtle, id) in world.computers" :key="id" class="ip-row">
        <span :class="{ stale: isStale(turtle) }">
          #{{ id }} {{ turtle.label ?? '' }}
          <span v-if="isStale(turtle)" class="stale-label">(stale)</span>
        </span>
        <button class="revoke" @click="deleteComputer(id)">Delete</button>
      </div>
    </div>
    <p v-else class="empty">No tracked turtles.</p>

    <hr class="divider" />

    <button class="danger" @click="clearWorld" :disabled="clearingWorld">
      {{ clearingWorld ? '⟳ Clearing...' : 'Clear World' }}
    </button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useUserStore } from '../store/useUser';
import { useWorldStore } from '../store/useWorld';
import { isStale } from '../utils/stale';

export default defineComponent({
  setup() {
    const world = useWorldStore();
    return { world };
  },
  data() {
    return {
      open: false,
      pending: [] as string[],
      approved: [] as string[],
      pendingIds: [] as { id: string; ip: string; requestedAt: number }[],
      approvedIds: [] as string[],
      allowByIp: true,
      operatorRequests: [] as { sub: string; email: string; requestedAt: number }[],
      operators: [] as { sub: string; email: string | null }[],
      pollHandle: null as ReturnType<typeof setTimeout> | null,
      clearingWorld: false,
    };
  },
  emits: ['opened'],
  methods: {
    toggleOpen() {
      this.open = !this.open;
      if (this.open) this.$emit('opened');
    },
    async fetchAll() {
      try {
        const [ips, ids, requests, ops] = await Promise.all([
          fetch('/api/admin/turtleIps').then(r => r.ok ? r.json() : null).catch(() => null),
          fetch('/api/admin/computerIds').then(r => r.ok ? r.json() : null).catch(() => null),
          fetch('/api/admin/operatorRequests').then(r => r.ok ? r.json() : null).catch(() => null),
          fetch('/api/admin/operators').then(r => r.ok ? r.json() : null).catch(() => null),
        ]);
        if (ips) { this.pending = ips.pending; this.approved = ips.approved; }
        if (ids) { this.pendingIds = ids.pending; this.approvedIds = ids.approved; this.allowByIp = ids.allowByIp; }
        if (requests) this.operatorRequests = requests;
        if (ops) this.operators = ops;
      } finally {
        this.pollHandle = setTimeout(() => this.fetchAll(), 30000);
      }
    },
    async fetchIps() { return this.fetchAll(); },
    async approve(ip: string) {
      await fetch('/api/admin/approveTurtle', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ip }),
      });
      await this.fetchIps();
    },
    async deny(ip: string) {
      await fetch('/api/admin/denyTurtle', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ip }),
      });
      await this.fetchIps();
    },
    async revoke(ip: string) {
      await fetch('/api/admin/revokeTurtle', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ip }),
      });
      await this.fetchAll();
    },
    async approveTurtleId(id: string) {
      await fetch('/api/admin/approveTurtleId', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) });
      await this.fetchAll();
    },
    async denyTurtleId(id: string) {
      await fetch('/api/admin/denyTurtleId', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) });
      await this.fetchAll();
    },
    async revokeTurtleId(id: string) {
      await fetch('/api/admin/revokeTurtleId', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) });
      await this.fetchAll();
    },
    async setAllowByIp(enabled: boolean) {
      await fetch('/api/admin/setAllowByIp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ enabled }) });
      await this.fetchAll();
    },
    async approveOperator(sub: string) {
      await fetch('/api/admin/approveOperator', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sub }) });
      await Promise.all([this.fetchAll(), useUserStore().fetchMe()]);
    },
    async denyOperator(sub: string) {
      await fetch('/api/admin/denyOperatorRequest', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sub }) });
      await Promise.all([this.fetchAll(), useUserStore().fetchMe()]);
    },
    async revokeOperator(sub: string) {
      await fetch('/api/admin/revokeOperator', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sub }) });
      await Promise.all([this.fetchAll(), useUserStore().fetchMe()]);
    },
    isStale,
    async deleteComputer(id: string | number) {
      await fetch('/api/admin/deleteComputer', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) });
      this.world.removeComputer(id);
      await this.fetchAll();
    },
    async clearWorld() {
      this.clearingWorld = true;
      await Promise.all([
        fetch('/api/admin/clearWorld', { method: 'POST' }).then(() => this.world.clearBlocks()),
        new Promise(r => setTimeout(r, 500)),
      ]);
      this.clearingWorld = false;
    },

  },
  mounted() {
    this.fetchAll();
  },
  beforeUnmount() {
    if (this.pollHandle) clearTimeout(this.pollHandle);
  },

});
</script>

<style scoped>
.toggle {
  background: none;
  border: none;
  color: gray;
  cursor: pointer;
  font-size: 0.85em;
  padding: 0;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.toggle:hover {
  color: darkgray;
}

.admin-panel {
  position: relative;
  background: rgb(30, 30, 30);
  border: 1px solid rgb(70, 70, 70);
  border-radius: 6px;
  padding: 8px 12px;
}

.dropdown {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 100;
  background: rgb(30, 30, 30);
  border: 1px solid rgb(70, 70, 70);
  border-radius: 6px;
  padding: 8px 12px;
  min-width: 220px;
  margin-top: 2px;
}

h3 {
  margin: 0 0 6px 0;
  font-size: 0.85em;
  color: darkgray;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.section-label {
  margin: 0 0 4px 0;
  font-size: 0.75em;
  color: gray;
}

.ip-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  margin-bottom: 4px;
  font-size: 0.85em;
  color: darkgray;
}

.empty {
  font-size: 0.8em;
  color: gray;
  margin: 0;
}

button {
  padding: 2px 8px;
  border-radius: 4px;
  border: none;
  background: rgb(60, 120, 60);
  color: white;
  cursor: pointer;
  font-size: 0.8em;
}

button:hover {
  background: rgb(80, 150, 80);
}

.btn-group {
  display: flex;
  gap: 4px;
}

.divider {
  border: none;
  border-top: 1px solid rgb(60, 60, 60);
  margin: 10px 0;
}

.request-info {
  display: flex;
  flex-direction: column;
  gap: 1px;
}

.op-info {
  display: flex;
  flex-direction: row;
  gap: 6px;
  align-items: center;
}

.email {
  color: darkgray;
}

.sub {
  font-size: 0.75em;
  color: gray;
}

button.revoke {
  background: rgb(120, 50, 50);
}

button.revoke:hover {
  background: rgb(160, 60, 60);
}

button.danger {
  background: rgb(140, 60, 20);
  width: 100%;
  padding: 4px;
  margin-top: 4px;
}

button.danger:hover {
  background: rgb(180, 80, 30);
}

.stale {
  color: rgb(180, 140, 40);
}

.stale-label {
  font-size: 0.75em;
  opacity: 0.8;
}

.allow-by-ip-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
}

.warning-label {
  font-size: 0.8em;
  color: rgb(220, 160, 40);
  font-weight: bold;
}

.warning-text {
  font-size: 0.75em;
  color: rgb(200, 130, 30);
  margin: 4px 0 0 0;
  padding: 4px 6px;
  background: rgb(60, 40, 10);
  border: 1px solid rgb(120, 80, 20);
  border-radius: 4px;
}
</style>
