// components/overlay/BlockNameDisplay.tsx
'use client'

import { useWorldViewStore } from '@/store/useWorldView'

export default function BlockNameDisplay() {
  const hoveredBlock    = useWorldViewStore(s => s.hoveredBlock)
  const hoveredBlockPos = useWorldViewStore(s => s.hoveredBlockPos)
  const hoveredEntity   = useWorldViewStore(s => s.hoveredEntity)
  const lockBlockInfo   = useWorldViewStore(s => s.lockBlockInfo)

  const hasContent = hoveredEntity || hoveredBlock || hoveredBlockPos
  if (!hasContent) return null

  return (
    <div className="canvas-overlay" style={{ top: 12, right: 12 }}>
      <div className="overlay-title">
        {hoveredEntity ? 'Entity' : lockBlockInfo ? 'Last clicked block' : 'Hovered block'}
      </div>
      <div className="overlay-body">
        {hoveredEntity ? (
          <>
            <div className="overlay-value">{hoveredEntity.name}</div>
            <div className="overlay-value muted" style={{ fontSize: 11 }}>{hoveredEntity.id}</div>
            {hoveredEntity.worldPos && (
              <div className="overlay-value muted" style={{ marginTop: 2 }}>
                {hoveredEntity.worldPos.x.toFixed(1)}, {hoveredEntity.worldPos.y.toFixed(1)}, {hoveredEntity.worldPos.z.toFixed(1)}
              </div>
            )}
          </>
        ) : (
          <>
            {hoveredBlock && <div className="overlay-value">{hoveredBlock.name}:{hoveredBlock.metadata}</div>}
            {hoveredBlockPos && (
              <div className="overlay-value muted" style={{ marginTop: 2 }}>
                {hoveredBlockPos.x}, {hoveredBlockPos.y}, {hoveredBlockPos.z}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  )
}

// src/components/BlockNameDisplay.vue
<template>
  <div class="pos-abs">
    <template v-if="worldView.hoveredEntity">
      <h2 class="hovered-block-text">Last clicked entity:</h2>
      <h2 class="hovered-block-text">{{ worldView.hoveredEntity.name }}</h2>
      <h2 class="hovered-block-text">{{ worldView.hoveredEntity.id }}</h2>
      <h2 class="hovered-block-text" v-if="worldView.hoveredEntity.worldPos">
        {{ worldView.hoveredEntity.worldPos.x.toFixed(1) }},
        {{ worldView.hoveredEntity.worldPos.y.toFixed(1) }},
        {{ worldView.hoveredEntity.worldPos.z.toFixed(1) }}
      </h2>
    </template>
    <template v-else>
      <h2 class="hovered-block-text">Last clicked block:</h2>
      <h2 class="hovered-block-text" v-if="worldView.hoveredBlock">
        {{ worldView.hoveredBlock.name }}:{{ worldView.hoveredBlock.metadata }}
      </h2>
      <h2 class="hovered-block-text" v-if="worldView.hoveredBlockPos">
        {{ worldView.hoveredBlockPos.x }}:{{ worldView.hoveredBlockPos.y }}:{{ worldView.hoveredBlockPos.z }}
      </h2>
    </template>
  </div>
</template>

<style scoped>

.hovered-block-text {
    color: lightgray;
    user-select: none;
    white-space: nowrap;
}
.pos-abs {
  position: fixed;
  top: 10px;
  right: 10px;
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import { useWorldViewStore } from "../store/useWorldView";

export default defineComponent({
  setup() {
    const worldView = useWorldViewStore();
    return { worldView };
  },
});
</script>
