// src/components/CCRemoteController.tsx
'use client'

import { memo, useEffect, useMemo, useRef, useState } from 'react'
import * as THREE from 'three'
import { useStoreWithEqualityFn } from 'zustand/traditional'
import { useWorldStore, replaceWorldBlocks, worldBlocks } from '@/store/useWorld'
import { loadWorldFromCache } from '@/store/worldCache'
import { useWorldViewStore } from '@/store/useWorldView'
import { useUserStore } from '@/store/useUser'
import ComputerPanel from './computers/ComputerPanel'
import InventoryView from './inventory/Inventory'
import BlockNameDisplay from './overlay/BlockNameDisplay'
import Scene from './Scene'
import KeyboardBindings from './computers/turtles/KeyboardBindings'
import AdminPanel from './overlay/AdminPanel'
import OperatorRequest from './overlay/OperatorRequest'
import BlockTransparency from './overlay/BlockTransparency'
import RenderFilters from './overlay/RenderFilters'
import { Led } from './ui'
import { connLedKind } from './computers/PollTimers'
import { ServerMessage } from '@/types/wsMessages'
import type { Block } from '@/types/world'

const ComputerLed = memo(function ComputerLed({ computerId }: { computerId: number }) {
  const kind = useWorldStore(s => connLedKind(!!s.computers[computerId]?.ws_connected, s.computers[computerId]?.ws_request_at))
  return <Led kind={kind} />
})

interface FloatingPanel { id: number; x: number; y: number }

const TYPE_SHORT: Record<string, string> = {
  minecart: 'MC', turtle: 'T', player: 'Ply', stationary: 'Sta',
}

export default function CCRemoteController() {
  const isLoading = useWorldStore(s => s.isLoading)
  // Re-render only when fields the tab strip or inventory panel actually use change.
  // Volatile fields (loc, inv, rot, entities, chatLog, fuelLevel, selectedSlot)
  // are handled by child components with their own narrow subscriptions.
  const computers = useStoreWithEqualityFn(useWorldStore, s => s.computers, (prev, next) => {
    const prevIds = Object.keys(prev)
    const nextIds = Object.keys(next)
    if (prevIds.length !== nextIds.length) return false
    for (const id of nextIds) {
      if (!prev[id]) return false
      const p = prev[id], n = next[id]
      if (p.ws_connected !== n.ws_connected ||
          p.ws_request_at !== n.ws_request_at ||
          p.type !== n.type ||
          p.label !== n.label ||
          (p as any).adjacentInventory !== (n as any).adjacentInventory) return false
    }
    return true
  })
  const selectedInventoryPos = useWorldViewStore(s => s.selectedInventoryPos)
  // Derive inventory live from world state so it updates after suck/drop and auto-closes when removed
  const derivedInventory = useMemo(() => {
    if (!selectedInventoryPos) return null
    const locStr = `${selectedInventoryPos.x},${selectedInventoryPos.y},${selectedInventoryPos.z}`
    for (const [id, c] of Object.entries(computers)) {
      const entry = (c as any).adjacentInventory?.[locStr]
      if (entry) return { inventory: entry.inventory, inventorySize: entry.inventorySize, computerId: Number(id) }
    }
    return null
  }, [selectedInventoryPos, computers])
  const userLoaded = useUserStore(s => s.loaded)
  const isOperator = useUserStore(s => s.isOperator)
  const isAdmin = useUserStore(s => s.isAdmin)

  const [isGuest, setIsGuest] = useState(false)
  const [guestRefreshDisabled, setGuestRefreshDisabled] = useState(false)
  const [wsConnected, setWsConnected] = useState(false)
  const [dockCollapsed, setDockCollapsed] = useState(false)
  const [tabOrder, setTabOrder] = useState<number[]>([])
  const [floatingPanels, setFloatingPanels] = useState<FloatingPanel[]>([])
  const [panelZIndexes, setPanelZIndexes] = useState<Record<number, number>>({})
  const topZRef = useRef(200)
  const draggedIdxRef = useRef<number | null>(null)
  const [addOpen, setAddOpen] = useState(false)
  const [addSearch, setAddSearch] = useState('')
  const addRef = useRef<HTMLDivElement>(null)
  const addBtnRef = useRef<HTMLButtonElement>(null)
  const [addPos, setAddPos] = useState({ top: 0, left: 0 })
  const [contextMenu, setContextMenu] = useState<{ id: number; x: number; y: number } | null>(null)
  const contextMenuRef = useRef<HTMLDivElement>(null)

  const wsRef = useRef<WebSocket | null>(null)
  const wsBackoffRef = useRef(1000)
  const wsReconnectRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const wsInitialStateLoadedRef = useRef(false)
  const idbHydratedRef = useRef(false)
  const catchupLoggedRef = useRef(false)
  const cacheTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const cacheWorkerRef = useRef<Worker | null>(null)
  const guestRefreshTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const renderFiltersRef = useRef<{ setOpen: (v: boolean) => void } | null>(null)
  const blockTransparencyRef = useRef<{ setOpen: (v: boolean) => void } | null>(null)
  const adminPanelRef = useRef<{ setOpen: (v: boolean) => void } | null>(null)

  const selectedComputerId = useWorldViewStore(s => s.selectedComputerId)
  const prevSelectedIdRef = useRef(selectedComputerId)
  useEffect(() => {
    if (selectedComputerId === prevSelectedIdRef.current) return
    prevSelectedIdRef.current = selectedComputerId
    if (selectedComputerId === -1) return
    useWorldViewStore.getState().focusOnComputer(selectedComputerId)
  }, [selectedComputerId]) // eslint-disable-line react-hooks/exhaustive-deps

  // Auto-close chest inventory panel when the turtle moves away and data is gone
  useEffect(() => {
    if (selectedInventoryPos && !derivedInventory) {
      useWorldViewStore.setState({ selectedInventoryPos: null })
    }
  }, [derivedInventory, selectedInventoryPos])

  const computerIds = Object.keys(computers).map(Number).sort((a, b) => a - b)

  useEffect(() => {
    const currSet = new Set(computerIds)
    setTabOrder(prev => prev.filter(id => currSet.has(id)))
    setFloatingPanels(prev => prev.filter(p => computerIds.includes(p.id)))
  }, [JSON.stringify(computerIds)]) // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (!addOpen) return
    function handleClick(e: MouseEvent) {
      if (addRef.current && !addRef.current.contains(e.target as Node)) {
        setAddOpen(false); setAddSearch('')
      }
    }
    window.addEventListener('mousedown', handleClick)
    return () => window.removeEventListener('mousedown', handleClick)
  }, [addOpen])

  useEffect(() => {
    if (!contextMenu) return
    function handleClick(e: MouseEvent) {
      if (contextMenuRef.current && !contextMenuRef.current.contains(e.target as Node)) setContextMenu(null)
    }
    function handleKey(e: KeyboardEvent) { if (e.key === 'Escape') setContextMenu(null) }
    window.addEventListener('mousedown', handleClick)
    window.addEventListener('keydown', handleKey)
    return () => { window.removeEventListener('mousedown', handleClick); window.removeEventListener('keydown', handleKey) }
  }, [contextMenu])

  function onTabDragStart(idx: number) { draggedIdxRef.current = idx }
  function onTabDragOver(e: React.DragEvent, idx: number) {
    e.preventDefault()
    if (draggedIdxRef.current === null || draggedIdxRef.current === idx) return
    setTabOrder(prev => {
      const next = [...prev]
      const [removed] = next.splice(draggedIdxRef.current!, 1)
      next.splice(idx, 0, removed)
      draggedIdxRef.current = idx
      return next
    })
  }
  function onTabDragEnd() { draggedIdxRef.current = null }

  function detachTab(id: number) {
    setFloatingPanels(prev => {
      if (prev.some(p => p.id === id)) return prev
      const offset = prev.length * 24
      return [...prev, { id, x: 380 + offset, y: 60 + offset }]
    })
    topZRef.current += 1
    setPanelZIndexes(prev => ({ ...prev, [id]: topZRef.current }))
    if (selectedComputerId === id) useWorldViewStore.setState({ selectedComputerId: -1 })
  }

  function dockPanel(id: number) { setFloatingPanels(prev => prev.filter(p => p.id !== id)) }

  function bringToFront(id: number) {
    topZRef.current += 1
    setPanelZIndexes(prev => ({ ...prev, [id]: topZRef.current }))
    useWorldViewStore.setState({ selectedComputerId: id })
  }

  function addTab(id: number) {
    setTabOrder(prev => prev.includes(id) ? prev : [...prev, id])
    setAddOpen(false); setAddSearch('')
    useWorldViewStore.setState({ selectedComputerId: id })
  }

  function closeTab(id: number) {
    setTabOrder(prev => prev.filter(t => t !== id))
    setFloatingPanels(prev => prev.filter(p => p.id !== id))
    if (selectedComputerId === id) useWorldViewStore.setState({ selectedComputerId: -1 })
  }

  function startPanelDrag(e: React.MouseEvent, panelId: number) {
    e.preventDefault()
    const startX = e.clientX; const startY = e.clientY
    const panel = floatingPanels.find(p => p.id === panelId)
    if (!panel) return
    const initX = panel.x; const initY = panel.y
    function onMove(ev: MouseEvent) {
      setFloatingPanels(prev => prev.map(p =>
        p.id === panelId ? { ...p, x: initX + ev.clientX - startX, y: initY + ev.clientY - startY } : p
      ))
    }
    function onUp() { window.removeEventListener('mousemove', onMove); window.removeEventListener('mouseup', onUp) }
    window.addEventListener('mousemove', onMove); window.addEventListener('mouseup', onUp)
  }

  function startGuestCooldown(seconds: number) {
    setGuestRefreshDisabled(true)
    if (guestRefreshTimerRef.current) clearTimeout(guestRefreshTimerRef.current)
    guestRefreshTimerRef.current = setTimeout(() => { setGuestRefreshDisabled(false); guestRefreshTimerRef.current = null }, seconds * 1000)
  }

  async function loadGuestState() {
    const w = useWorldStore.getState()
    const res = await fetch('/api/state').catch(() => null)
    if (!res) return
    if (res.status === 429) {
      const data = await res.json().catch(() => ({}))
      startGuestCooldown(data.retryAfter ?? 30); return
    }
    const data = await res.json().catch(() => null)
    if (!data) return
    w.setComputerStatus(data.computers)
    replaceWorldBlocks(data.world.blocks)
    const freshComputers = useWorldStore.getState().computers
    const selId = useWorldViewStore.getState().selectedComputerId
    const hasCoords = (c: { loc?: { x?: unknown; y?: unknown; z?: unknown } | null } | undefined) =>
      c?.loc != null && c.loc.x != null && c.loc.y != null && c.loc.z != null
    if (!hasCoords(freshComputers[selId])) {
      const entry = Object.entries(freshComputers).find(([, c]) => hasCoords(c))
      if (entry) {
        const autoId = Number(entry[0])
        useWorldViewStore.setState({ selectedComputerId: autoId })
        setTabOrder(prev => prev.includes(autoId) ? prev : [...prev, autoId])
      }
    }
    const view = useWorldViewStore.getState()
    view.regenerateSceneFromBlocks(); view.render()
    useWorldStore.setState({ isLoading: false })
    startGuestCooldown(30)
  }

  function connectWebSocket() {
    const w = useWorldStore.getState()
    const base = w.URL
      ? w.URL.replace(/^http/, 'ws')
      : `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}/ws`
    const lastTx = w.lastTransactionId
    const wsUrl = lastTx >= 0 ? `${base}?lastTx=${lastTx}` : base
    const ws = new WebSocket(wsUrl)
    wsRef.current = ws

    ws.onopen = () => {
      wsBackoffRef.current = 1000
      setWsConnected(true)
      useWorldStore.setState({ wsSend: (msg: object) => ws.send(JSON.stringify(msg)) })
      if (!wsInitialStateLoadedRef.current) {
        wsInitialStateLoadedRef.current = true
        if (!idbHydratedRef.current) loadGuestState()
      }
    }

    ws.onmessage = (event) => {
      let raw: unknown
      try { raw = JSON.parse(event.data) } catch { return }

      const parsed = ServerMessage.safeParse(raw)
      if (!parsed.success) return
      const data = parsed.data

      const w = useWorldStore.getState()
      const view = useWorldViewStore.getState()

      if ('type' in data) {
        // ServerError
        useWorldStore.setState(s => ({ commandResult: { ...s.commandResult, [data.computerId]: data.message } }))
      } else if ('commandResult' in data) {
        // ServerCommandResult
        const { computerId, result } = data.commandResult
        useWorldStore.setState(s => ({ commandResult: { ...s.commandResult, [computerId]: result.ret } }))
      } else if ('state' in data) {
        // ServerState — initial full load
        if (idbHydratedRef.current && !catchupLoggedRef.current) {
          catchupLoggedRef.current = true
          console.log(`[cache] Server sent full state (cache txId=${w.lastTransactionId} too stale or unrecognised) — ${Object.keys(data.state.world.blocks ?? {}).length} blocks, txId=${data.state.lastTransactionId}`)
        }
        if (data.state.lastTransactionId !== w.lastTransactionId) {
          w.setComputerStatus(data.state.computers)
          replaceWorldBlocks(data.state.world.blocks as Record<string, Block>)
          useWorldStore.setState({ lastTransactionId: data.state.lastTransactionId })
          const freshComputers = useWorldStore.getState().computers
          const hasCoords = (c: { loc?: { x?: unknown; y?: unknown; z?: unknown } | null } | undefined) =>
            c?.loc != null && c.loc.x != null && c.loc.y != null && c.loc.z != null
          if (!hasCoords(freshComputers[view.selectedComputerId])) {
            const entry = Object.entries(freshComputers).find(([, c]) => hasCoords(c))
            if (entry) {
              const autoId = Number(entry[0])
              useWorldViewStore.setState({ selectedComputerId: autoId })
              setTabOrder(prev => prev.includes(autoId) ? prev : [...prev, autoId])
            }
          }
          view.regenerateSceneFromBlocks()
        }
      } else {
        // ServerTransactions
        if (idbHydratedRef.current && !catchupLoggedRef.current) {
          catchupLoggedRef.current = true
          const txList = Object.values(data.transactions) as Array<{ blocks?: Record<string, unknown>; computers?: Record<string, unknown> }>
          let blockAdds = 0, blockRemoves = 0, computerUpdates = 0
          for (const t of txList) {
            for (const v of Object.values(t.blocks ?? {})) { if (v) blockAdds++; else blockRemoves++ }
            computerUpdates += Object.keys(t.computers ?? {}).length
          }
          console.log(`[cache] Catchup: ${txList.length} transaction(s), +${blockAdds}/-${blockRemoves} blocks, ${computerUpdates} computer update(s), txId=${w.lastTransactionId} → ${Math.max(...Object.keys(data.transactions).map(Number))}`)
        }
        w.applyTransactions(data.transactions)
      }

      view.render()
      if (w.isLoading) useWorldStore.setState({ isLoading: false })
    }

    ws.onclose = (event) => {
      setWsConnected(false)
      useWorldStore.setState({ wsSend: null })
      if (event.code === 4401) {
        setIsGuest(true); useUserStore.getState().stopPolling(); loadGuestState(); return
      }
      const delay = wsBackoffRef.current
      wsBackoffRef.current = Math.min(wsBackoffRef.current * 2, 10000)
      wsReconnectRef.current = setTimeout(connectWebSocket, delay)
    }

    ws.onerror = () => ws.close()
  }

  function persistWorldToCache() {
    const w = useWorldStore.getState()
    if (w.lastTransactionId < 0) return
    cacheWorkerRef.current?.postMessage({ lastTransactionId: w.lastTransactionId, computers: w.computers, blocks: worldBlocks })
  }

  useEffect(() => {
    cacheWorkerRef.current = new Worker(new URL('../workers/worldCache.worker.ts', import.meta.url))
    useUserStore.getState().startPolling()

    let mounted = true
    loadWorldFromCache().then(cached => {
      if (!mounted) return
      if (cached) {
        console.log(`[cache] Loaded: ${Object.keys(cached.blocks).length} blocks, ${Object.keys(cached.computers).length} computers, txId=${cached.lastTransactionId}`)
        const w = useWorldStore.getState()
        w.setComputerStatus(cached.computers as Record<string, any>)
        replaceWorldBlocks(cached.blocks)
        useWorldStore.setState({ lastTransactionId: cached.lastTransactionId, isLoading: false })
        idbHydratedRef.current = true
        const view = useWorldViewStore.getState()
        view.regenerateSceneFromBlocks()
        view.render()
      } else {
        console.log('[cache] No cached world found — waiting for server state')
      }
    }).catch(() => {}).finally(() => {
      if (mounted) connectWebSocket()
    })

    cacheTimerRef.current = setInterval(persistWorldToCache, 60_000)
    function onHide() { if (document.visibilityState === 'hidden') persistWorldToCache() }
    document.addEventListener('visibilitychange', onHide)

    return () => {
      mounted = false
      useUserStore.getState().stopPolling()
      if (wsRef.current) { wsRef.current.onclose = null; wsRef.current.close() }
      if (wsReconnectRef.current) clearTimeout(wsReconnectRef.current)
      if (guestRefreshTimerRef.current) clearTimeout(guestRefreshTimerRef.current)
      if (cacheTimerRef.current) clearInterval(cacheTimerRef.current)
      cacheWorkerRef.current?.terminate()
      document.removeEventListener('visibilitychange', onHide)
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const floatingIds = new Set(floatingPanels.map(p => p.id))
  const dockedSelectedId = floatingIds.has(selectedComputerId) ? -1 : selectedComputerId
  function computerName(id: number) {
    const c = computers[id]
    return c?.label ? c.label : `#${id}`
  }

  function computerTitle(id: number) {
    const c = computers[id]
    if (!c) return `#${id}`
    const type = c.type ?? 'turtle'
    return `${type.charAt(0).toUpperCase()}${type.slice(1)} #${id}${c.label ? ` · ${c.label}` : ''}`
  }

  return (
    <div className="app">
      {/* ── Top bar ───────────────────────────────────────── */}
      <div className="panel topbar">
        <a className="brand" href="/api/home" title="turkeyblock.org">
          <span className="brand-mark">T</span>
          <span className="brand-text">
            <span className="brand-text-primary">turkeyblock.org</span>
            <span className="brand-text-secondary">CC Remote</span>
          </span>
        </a>

        <button
          onClick={() => setDockCollapsed(d => !d)}
          title={dockCollapsed ? 'Show sidebar' : 'Hide sidebar'}
          style={{
            background: 'none', border: 'none', borderRight: 'var(--border)',
            color: 'var(--fg-dim)', cursor: 'pointer', padding: '0 8px',
            fontSize: 13, lineHeight: 1, alignSelf: 'stretch',
            display: 'flex', alignItems: 'center',
          }}
        >{dockCollapsed ? '›' : '‹'}</button>

        <div className="topbar-section sys-stats">
          <div className="sys-stat">
            <Led kind={wsConnected ? 'on' : 'amber'} />
            <span className="sys-stat-k">WebSocket</span>
            <span className="sys-stat-v">{wsConnected ? 'connected' : 'reconnecting…'}</span>
          </div>
          {isGuest && (
            <div className="sys-stat">
              <Led kind="amber" />
              <span className="sys-stat-k">Guest</span>
              <a href="/api/signin" style={{ color: 'var(--accent)', fontSize: 12, textDecoration: 'none' }}>Sign in</a>
            </div>
          )}
          {userLoaded && isOperator && !isAdmin && (
            <div className="sys-stat">
              <Led kind="info" />
              <span className="sys-stat-v" style={{ color: 'var(--cyan)' }}>Operator</span>
            </div>
          )}
        </div>

        <div className="topbar-actions">
          {isGuest && (
            <button
              className={`btn btn-compact${guestRefreshDisabled ? ' btn-toggled' : ''}`}
              disabled={guestRefreshDisabled}
              onClick={() => !guestRefreshDisabled && loadGuestState()}
            >
              {guestRefreshDisabled ? 'Refreshed ✓' : 'Refresh'}
            </button>
          )}
          {userLoaded && !isOperator && !isGuest && <OperatorRequest />}
          <RenderFilters ref={renderFiltersRef} onOpened={() => { blockTransparencyRef.current?.setOpen(false); adminPanelRef.current?.setOpen(false) }} />
          <BlockTransparency ref={blockTransparencyRef} onOpened={() => { renderFiltersRef.current?.setOpen(false); adminPanelRef.current?.setOpen(false) }} />
          {isAdmin && <AdminPanel ref={adminPanelRef} onOpened={() => { renderFiltersRef.current?.setOpen(false); blockTransparencyRef.current?.setOpen(false) }} />}
        </div>
      </div>

      {/* ── Main ─────────────────────────────────────────── */}
      <div className="main" style={dockCollapsed ? { gridTemplateColumns: '0 1fr', columnGap: 0 } : undefined}>

        {/* Left dock */}
        <div className="dock" style={dockCollapsed ? { overflow: 'hidden', minWidth: 0 } : undefined}>
          {/* Connected computers panel */}
          <div className="panel">
            <div className="panel-header">
              <div className="panel-header-title">
                <Led kind="on" />
                <span>Connected Computers</span>
              </div>
              <span style={{ fontSize: 11, color: 'var(--fg-mute)' }}>{computerIds.length} online</span>
            </div>
            <div style={{ padding: 10, position: 'relative' }}>
              {/* Tab strip */}
              <div className="tab-strip">
                {tabOrder.map((id, idx) => {
                  const c = computers[id]
                  const isFloating = floatingIds.has(id)
                  const isSelected = selectedComputerId === id && !isFloating
                  return (
                    <div
                      key={id}
                      draggable
                      onDragStart={() => onTabDragStart(idx)}
                      onDragOver={e => onTabDragOver(e, idx)}
                      onDragEnd={onTabDragEnd}
                      className={`tab ${isSelected ? 'tab-active' : ''} ${isFloating ? 'tab-floating' : ''}`}
                      onClick={() => {
                        if (isFloating) { bringToFront(id) }
                        else { useWorldViewStore.setState({ selectedComputerId: isSelected ? -1 : id }) }
                      }}
                      onContextMenu={e => { e.preventDefault(); setContextMenu({ id, x: e.clientX, y: e.clientY }) }}
                      title={`${computerTitle(id)} · right-click for options`}
                    >
                      <ComputerLed computerId={id} />
                      <span className="tab-type">{TYPE_SHORT[c?.type ?? ''] ?? '?'}</span>
                      <span className="tab-label">{computerName(id)}</span>
                      {isFloating && <span className="tab-float-mark">↗</span>}
                    </div>
                  )
                })}

                {/* Add tab button */}
                <div ref={addRef} style={{ position: 'relative', flexShrink: 0 }}>
                  <button
                    ref={addBtnRef}
                    className="btn tab-add"
                    onClick={() => {
                      if (addBtnRef.current) {
                        const r = addBtnRef.current.getBoundingClientRect()
                        setAddPos({ top: r.bottom + 4, left: r.left })
                      }
                      setAddOpen(o => !o)
                    }}
                    title="Add computer tab"
                  >+</button>
                  {addOpen && (
                    <>
                      <div style={{ position: 'fixed', inset: 0, zIndex: 40 }} onClick={() => { setAddOpen(false); setAddSearch('') }} />
                      <div className="dropdown" style={{ position: 'fixed', top: addPos.top, left: addPos.left, minWidth: 220, zIndex: 500 }}>
                        <input
                          autoFocus
                          className="input input-mono"
                          style={{ fontSize: 12 }}
                          value={addSearch}
                          onChange={e => setAddSearch(e.target.value)}
                          placeholder="Search computers…"
                        />
                        <div style={{ maxHeight: 200, overflowY: 'auto' }}>
                          {(() => {
                            const tabSet = new Set(tabOrder)
                            const available = computerIds.filter(id => !tabSet.has(id))
                            const filtered = available.filter(id =>
                              !addSearch || computerTitle(id).toLowerCase().includes(addSearch.toLowerCase()) || String(id).includes(addSearch)
                            )
                            if (available.length === 0) return <div className="explainer" style={{ padding: '4px 0' }}>All computers added.</div>
                            if (filtered.length === 0) return <div className="explainer" style={{ padding: '4px 0' }}>No matches.</div>
                            return filtered.map(id => (
                              <div key={id} className="ctx-item" onClick={() => addTab(id)}>
                                <ComputerLed computerId={id} />
                                <span className="mono" style={{ color: 'var(--fg-mute)', fontSize: 11 }}>#{id}</span>
                                <span>{computerName(id)}</span>
                              </div>
                            ))
                          })()}
                        </div>
                      </div>
                    </>
                  )}
                </div>
              </div>

              <div className="explainer" style={{ marginTop: 8 }}>
                Click to view · <b>right-click</b> to detach or close.
              </div>
            </div>
          </div>

          {/* Active computer panel */}
          {dockedSelectedId !== -1 ? (
            <div className="panel">
              <div className="panel-header">
                <div className="panel-header-title">
                  <ComputerLed computerId={dockedSelectedId} />
                  <span>{computerTitle(dockedSelectedId)}</span>
                </div>
              </div>
              <div className="panel-body">
                <ComputerPanel computerId={dockedSelectedId} />
              </div>
            </div>
          ) : (
            <div className="panel" style={{ padding: 14, color: 'var(--fg-mute)', fontSize: 12 }}>
              Select a tab above to open its control panel.
            </div>
          )}
        </div>

        {/* World canvas */}
        <div className="panel canvas">
          <Scene />

          {/* Canvas overlays */}
          <div className="canvas-overlay" style={{ top: 12, left: 12 }}>
            <div className="overlay-title">Focus</div>
            <div className="overlay-body">
              <div className="overlay-value">
                {dockedSelectedId !== -1 ? computerTitle(dockedSelectedId) : '—'}
              </div>
            </div>
          </div>

          <BlockNameDisplay />

          {derivedInventory && selectedInventoryPos && (
            <div style={{ position: 'absolute', top: 12, left: '50%', transform: 'translateX(-50%)', zIndex: 5 }}>
              <InventoryView
                inventory={derivedInventory.inventory}
                inventorySize={derivedInventory.inventorySize}
                computerId={derivedInventory.computerId}
                blockPos={selectedInventoryPos}
              />
            </div>
          )}

          {isLoading && (
            <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.6)', zIndex: 20 }}>
              <div className="canvas-overlay" style={{ minWidth: 'unset', padding: '14px 24px' }}>
                <div className="overlay-value">Loading world…</div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ── Floating panels ───────────────────────────────── */}
      {floatingPanels.map(panel => {
        const c = computers[panel.id]
        if (!c) return null
        return (
          <div
            key={panel.id}
            className="floating-panel"
            style={{ left: panel.x, top: panel.y, zIndex: panelZIndexes[panel.id] ?? 200 }}
            onMouseDown={() => bringToFront(panel.id)}
          >
            <div className="floating-titlebar" onMouseDown={e => startPanelDrag(e, panel.id)}>
              <span className="floating-title">
                <ComputerLed computerId={panel.id} />
                {computerTitle(panel.id)}
              </span>
              <button className="floating-close" onMouseDown={e => e.stopPropagation()} onClick={() => dockPanel(panel.id)} title="Dock">×</button>
            </div>
            <div className="floating-body">
              <ComputerPanel computerId={panel.id} />
            </div>
          </div>
        )
      })}

      {/* ── Context menu ─────────────────────────────────── */}
      {contextMenu && (
        <div ref={contextMenuRef} className="ctx-menu" style={{ left: contextMenu.x, top: contextMenu.y }}>
          {floatingIds.has(contextMenu.id) ? (
            <div className="ctx-item" onClick={() => { dockPanel(contextMenu.id); setContextMenu(null) }}>
              ↙ Dock panel
            </div>
          ) : (
            <div className="ctx-item" onClick={() => { detachTab(contextMenu.id); setContextMenu(null) }}>
              ↗ Detach to float
            </div>
          )}
          <div className="ctx-item ctx-item-danger" onClick={() => { closeTab(contextMenu.id); setContextMenu(null) }}>
            × Close tab
          </div>
        </div>
      )}

      <KeyboardBindings />
    </div>
  )
}

// src/components/CCRemoteController.vue
<template>
  <div class="hud">
    <h1 v-if="world.isLoading" class="centered">
      LOADING ... (depending on the number of blocks this might take some
      seconds)
    </h1>
    <div class="hud-panel">
      <div class="panel-left">
        <a class="home-link" href="/api/home">← turkeyblock.org</a>
        <div class="modem-status" :class="world.modemServerId !== null ? 'modem-online' : 'modem-offline'">
          📡 Modem: {{ world.modemServerId !== null ? `online (id ${world.modemServerId})` : 'offline' }}
        </div>
        <select v-model="worldView.selectedComputerId" @change="worldView.followComputer(worldView.selectedComputerId)">
          <option :value="-1">[None]</option>
          <option v-for="id in world.getComputerIds" :key="id" :value="id">
            {{ world.computers[id].type === 'minecart' ? 'Minecart' : world.computers[id].type === 'modem' ? 'Modem' : 'Turtle' }} {{ id }}{{ world.computers[id].type === 'modem' ? (world.modemServerId !== null ? ' [online]' : ' [offline]') : ((world.computers[id].via_modem ? ' 📡' : '') + (world.computers[id].sleep_mode ? ' 💤' : '') + (isStale(world.computers[id]) ? ' [offline]' : ' [online]')) }} : {{ world.computers[id].label }}
          </option>
        </select>
        <div v-if="worldView.selectedComputerId === -1" class="manual-center">
          <span class="manual-center-label">Center</span>
          <input type="number" v-model.number="manualX" placeholder="X" class="coord-input" @change="applyManualCenter" />
          <input type="number" v-model.number="manualZ" placeholder="Z" class="coord-input" @change="applyManualCenter" />
        </div>
        <TurtlePanel
          v-if="Number(worldView.selectedComputerId) != -1"
          :computerId="Number(worldView.selectedComputerId)"
        />
      </div>
      <div class="panel-right">
        <RenderFilters ref="renderFilters" @opened="closeOtherPanels('renderFilters')" />
        <BlockTransparency ref="blockTransparency" @opened="closeOtherPanels('blockTransparency')" />
        <div v-if="isGuest" class="guest-controls">
          <a href="/api/signin" class="guest-signin">Sign in</a>
          <button
            class="guest-refresh-btn"
            :disabled="guestRefreshDisabled"
            @click="guestRefresh"
          >{{ guestRefreshDisabled ? 'Refreshed ✓' : 'Refresh' }}</button>
        </div>
        <span v-if="user.loaded && user.isOperator && !user.isAdmin" class="operator-badge">Operator</span>
        <OperatorRequest v-if="user.loaded && !user.isOperator && !isGuest" />
        <AdminPanel v-if="user.isAdmin" ref="adminPanel" @opened="closeOtherPanels('adminPanel')" />
      </div>
    </div>
    <Inventory
      v-if="worldView.selectedInventory"
      :inventory="worldView.selectedInventory"
      :inventorySize="worldView.selectedInventorySize"
      style="grid-column: 2; pointer-events: auto"
    />
    <Scene />
    <KeyboardBindings />
    <BlockNameDisplay />
  </div>
</template>

<style scoped>
.hud {
  position: absolute;
  display: grid;
  user-select: none;
  pointer-events: none;
}
.centered {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.hud-panel {
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  gap: 8px;
  padding: 10px;
  pointer-events: auto;
}

.panel-left {
  display: flex;
  flex-direction: column;
  gap: 6px;
  min-width: 240px;
  background: rgb(30, 30, 30);
  border: 1px solid rgb(70, 70, 70);
  border-radius: 6px;
  padding: 8px 12px;
}

.panel-right {
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  gap: 6px;
}

.home-link {
  color: darkgray;
  font-size: 0.85em;
  text-decoration: none;
}

.home-link:hover {
  color: white;
}

.operator-badge {
  font-size: 0.75em;
  color: rgb(80, 180, 80);
  letter-spacing: 0.05em;
  text-transform: uppercase;
}

.manual-center {
  display: flex;
  align-items: center;
  gap: 4px;
}

.manual-center-label {
  font-size: 0.75em;
  color: gray;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  flex-shrink: 0;
}

.coord-input {
  width: 64px;
  padding: 2px 4px;
  border-radius: 4px;
  border: 1px solid rgb(70, 70, 70);
  background: rgb(40, 40, 40);
  color: darkgray;
  font-size: 0.85em;
  text-align: center;
}

.coord-input:focus {
  outline: none;
  border-color: rgb(100, 100, 100);
}

.guest-controls {
  display: flex;
  align-items: center;
  gap: 6px;
  background: rgb(30, 30, 30);
  border: 1px solid rgb(70, 70, 70);
  border-radius: 6px;
  padding: 6px 10px;
}

.guest-signin {
  color: darkgray;
  font-size: 0.85em;
  text-decoration: none;
}

.guest-signin:hover {
  color: white;
}

.guest-refresh-btn {
  padding: 3px 10px;
  border-radius: 4px;
  border: none;
  background: rgb(52, 52, 52);
  color: darkgray;
  cursor: pointer;
  font-size: 0.85em;
}

.guest-refresh-btn:hover:not(:disabled) {
  background: rgb(70, 70, 70);
  color: white;
}

.guest-refresh-btn:disabled {
  opacity: 0.5;
  cursor: default;
}

select {
  padding: 4px;
  border-radius: 4px;
  background-color: rgb(52, 52, 52);
  color: darkgray;
  font-weight: bold;
}

.modem-status {
  font-size: 0.75em;
  letter-spacing: 0.03em;
}
.modem-online { color: rgb(80, 200, 80); }
.modem-offline { color: rgb(120, 120, 120); }
</style>

<script lang="ts">
import { defineComponent } from "vue";
import * as THREE from "three";

import { useWorldStore } from "../store/useWorld";
import { isStale } from "../utils/stale";
import { useWorldViewStore } from "../store/useWorldView";
import { useUserStore } from "../store/useUser";
import TurtlePanel from "./TurtlePanel.vue";
import Inventory from "./Inventory.vue";
import BlockNameDisplay from "./BlockNameDisplay.vue";
import Scene from "./Scene.vue";
import KeyboardBindings from "./KeyboardBindings.vue";
import AdminPanel from "./AdminPanel.vue";
import OperatorRequest from "./OperatorRequest.vue";
import BlockTransparency from "./BlockTransparency.vue";
import RenderFilters from "./RenderFilters.vue";

export default defineComponent({
  setup() {
    const world = useWorldStore();
    const worldView = useWorldViewStore();
    const user = useUserStore();
    return { world, worldView, user };
  },
  data() {
    return {
      computerId: -1 as Number,
      manualX: null as number | null,
      manualZ: null as number | null,
      _ws: null as WebSocket | null,
      _wsBackoff: 1000 as number,
      _wsReconnectTimeout: null as ReturnType<typeof setTimeout> | null,
      _cmdResultInterval: null as ReturnType<typeof setInterval> | null,
      _modemStatusInterval: null as ReturnType<typeof setInterval> | null,
      isGuest: false,
      guestRefreshDisabled: false,
      _guestRefreshTimer: null as ReturnType<typeof setTimeout> | null,
    };
  },
  watch: {
    'worldView.selectedComputerId'(id: number) {
      if (id === -1) return;
      this.worldView.manualCenter = null;
      // Only rebuild the scene when a range filter is active — that's the only
      // case where the visible block set actually changes with the computer.
      // Otherwise just reposition the camera.
      if (this.worldView.computerRangeXZ !== null) {
        this.worldView.regenerateSceneFromBlocks();
      } else {
        this.worldView.focusOnComputer(id);
      }
    },
  },
  components: {
    TurtlePanel,
    Scene,
    BlockNameDisplay,
    Inventory,
    KeyboardBindings,
    AdminPanel,
    OperatorRequest,
    BlockTransparency,
    RenderFilters,
  },
  methods: {
    applyManualCenter() {
      if (this.manualX !== null && this.manualZ !== null) {
        this.worldView.manualCenter = { x: this.manualX, z: this.manualZ };
        this.worldView.setCameraFocus(new THREE.Vector3(this.manualX, 64, this.manualZ));
      } else {
        this.worldView.manualCenter = null;
      }
      this.worldView.regenerateSceneFromBlocks();
    },
    closeOtherPanels(except: string) {
      (['renderFilters', 'blockTransparency', 'adminPanel'] as const).forEach(name => {
        if (name !== except) {
          const ref = this.$refs[name] as any;
          if (ref) ref.open = false;
        }
      });
    },
    connectWebSocket() {
      const world = useWorldStore();
      const worldView = useWorldViewStore();

      const wsUrl = world.URL
        ? world.URL.replace(/^http/, 'ws')
        : `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}`;

      const ws = new WebSocket(wsUrl);
      this._ws = ws;

      ws.onopen = () => {
        this._wsBackoff = 1000;
      };

      ws.onmessage = (event) => {
        const data = JSON.parse(event.data);
        if (data.state) {
          const alreadyCurrent = data.state.lastTransactionId === world.lastTransactionId;
          world.setComputerStatus(data.state.computers);
          world.blocks = data.state.world.blocks;
          world.lastTransactionId = data.state.lastTransactionId;
          if (!alreadyCurrent) {
            if (!world.computers[worldView.selectedComputerId]?.loc) {
              const entry = Object.entries(world.computers).find(([, c]) => c.loc);
              if (entry) worldView.selectedComputerId = Number(entry[0]);
            }
            worldView.regenerateSceneFromBlocks();
          }
        } else {
          world.applyTransactions(data.transactions);
        }
        worldView.render();
        world.isLoading = false;
      };

      ws.onclose = (event) => {
        if (event.code === 4401) {
          this.isGuest = true;
          if (this._cmdResultInterval) { clearInterval(this._cmdResultInterval); this._cmdResultInterval = null; }
          this.loadGuestState();
          return;
        }
        const delay = this._wsBackoff;
        this._wsBackoff = Math.min(this._wsBackoff * 2, 10000);
        this._wsReconnectTimeout = setTimeout(() => this.connectWebSocket(), delay);
      };

      ws.onerror = () => ws.close();
    },
    async pollModemStatus() {
      const world = useWorldStore();
      const res = await fetch(world.apiURL + 'modem/id').catch(() => null);
      if (!res || !res.ok) return;
      const data = await res.json().catch(() => null);
      if (data) world.modemServerId = data.id ?? null;
    },
    pollCommandResult() {
      const world = useWorldStore();
      const worldView = useWorldViewStore();
      if (worldView.selectedComputerId === -1) return;
      fetch(world.apiURL + "getCommandResult", {
        method: "POST",
        mode: "cors",
        headers: {
          "Access-Control-Allow-Origin": "*",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          computerId: worldView.selectedComputerId,
          getOnlyLatest: true,
        }),
      })
        .then((res) => res.json())
        .then((data) => {
          if (data.result) {
            world.commandResult[data.computerId] = data.result.ret;
          }
        });
    },
    async loadGuestState() {
      const world = useWorldStore();
      const worldView = useWorldViewStore();
      const res = await fetch('/api/state').catch(() => null);
      if (!res) return;
      if (res.status === 429) {
        const data = await res.json().catch(() => ({}));
        this.startGuestCooldown(data.retryAfter ?? 30);
        return;
      }
      const data = await res.json().catch(() => null);
      if (!data) return;
      world.setComputerStatus(data.computers);
      world.blocks = data.world.blocks;
      if (!world.computers[worldView.selectedComputerId]?.loc) {
        const entry = Object.entries(world.computers).find(([, c]) => c.loc);
        if (entry) worldView.selectedComputerId = Number(entry[0]);
      }
      worldView.regenerateSceneFromBlocks();
      worldView.render();
      world.isLoading = false;
      this.startGuestCooldown(30);
    },
    guestRefresh() {
      if (this.guestRefreshDisabled) return;
      this.loadGuestState();
    },
    startGuestCooldown(seconds: number) {
      this.guestRefreshDisabled = true;
      if (this._guestRefreshTimer) clearTimeout(this._guestRefreshTimer);
      this._guestRefreshTimer = setTimeout(() => {
        this.guestRefreshDisabled = false;
        this._guestRefreshTimer = null;
      }, seconds * 1000);
    },
    isStale,
  },
  mounted() {
    useUserStore().startPolling();
    this.connectWebSocket();
    this._cmdResultInterval = setInterval(() => this.pollCommandResult(), 400);
    this.pollModemStatus();
    this._modemStatusInterval = setInterval(() => this.pollModemStatus(), 15000);
  },
  beforeUnmount() {
    useUserStore().stopPolling();
    if (this._ws) { this._ws.onclose = null; this._ws.close(); }
    if (this._wsReconnectTimeout) clearTimeout(this._wsReconnectTimeout);
    if (this._cmdResultInterval) clearInterval(this._cmdResultInterval);
    if (this._modemStatusInterval) clearInterval(this._modemStatusInterval);
    if (this._guestRefreshTimer) clearTimeout(this._guestRefreshTimer);
  },
});
</script>
