// src/components/computers/turtles/FuelGauge.tsx
'use client'

import { useWorldStore } from '@/store/useWorld'

interface Props { computerId: number }

export default function FuelGauge({ computerId }: Props) {
  const fuelLevel = useWorldStore(s => (s.computers[computerId] as any)?.fuelLevel)
  const fuelLimit = useWorldStore(s => (s.computers[computerId] as any)?.fuelLimit)
  if (fuelLevel === undefined) return null
  const pct = (fuelLimit ?? 0) > 0 ? Math.min(100, (fuelLevel / fuelLimit!) * 100) : 0
  return (
    <div className="meter" style={{ height: 10 }}>
      <div className={pct < 20 ? 'meter-fill meter-fill-amber' : 'meter-fill'} style={{ width: `${pct}%` }} />
    </div>
  )
}

// src/components/FuelGauge.vue
<template>
  <meter
    class="fuel-gauge"
    :value="world.computers[computerId].fuelLevel"
    :min="0"
    :max="world.computers[computerId].fuelLimit"
  >
    TEST
  </meter>
</template>

<style scoped>
meter {
  height: 20px;
  width: 100%;
}

meter::after {
  position: relative;
  content: attr(value);
  top: -18px;
  transform: translateX(-50%);
  transform: translateY(-50%);
  color: lime;
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import { useWorldStore } from "../store/useWorld";

export default defineComponent({
  setup() {
    const world = useWorldStore();
    return { world };
  },
  props: {
    computerId: {
      required: true,
      type: Number,
    },
  },
});
</script>
