// src/components/inventory/Inventory.tsx
'use client'

import { useWorldStore, lookupBlock } from '@/store/useWorld'
import { useWorldViewStore } from '@/store/useWorldView'
import type { Inventory } from '@/types/world'
import GenericInventorySlot from './GenericInventorySlot'

interface Props {
  inventory: Inventory
  inventorySize: number
  computerId: number
  blockPos: { x: number; y: number; z: number } | null
}

export default function InventoryView({ inventory, inventorySize, computerId, blockPos }: Props) {
  const invokeCommand = useWorldStore(s => s.invokeCommand)
  const computers = useWorldStore(s => s.computers)
  const block = blockPos ? lookupBlock(`${blockPos.x},${blockPos.y},${blockPos.z}`) : null

  const normalized: Record<number, { name: string; count: number }> = {}
  if (inventory) {
    if (Array.isArray(inventory)) {
      for (let i = 0; i < (inventory as any[]).length; i++) {
        if ((inventory as any[])[i] != null && (inventory as any[])[i] !== false) normalized[i + 1] = (inventory as any[])[i]
      }
    } else {
      Object.assign(normalized, inventory)
    }
  }

  const turtleLoc = computers[computerId]?.loc
  let side: string | undefined
  let isAdjacent = false
  if (blockPos && turtleLoc) {
    const dx = Math.abs(blockPos.x - turtleLoc.x)
    const dy = blockPos.y - turtleLoc.y
    const dz = Math.abs(blockPos.z - turtleLoc.z)
    isAdjacent = dx + Math.abs(dy) + dz === 1
    side = dy > 0 ? 'top' : dy < 0 ? 'bottom' : 'front'
  }

  const blockName = block?.name
    ? block.name.split(':').pop()!.replace(/_/g, ' ')
    : 'Inventory'

  const itemCount = Object.values(normalized).reduce((sum, s) => sum + (s?.count ?? 0), 0)

  return (
    <div className="inv-chest-panel">
      <div className="inv-chest-header">
        <span className="inv-chest-header-name">{blockName}</span>
        <span className="inv-chest-header-slots">{inventorySize} slots · {itemCount} items</span>
        <button
          className="btn btn-compact"
          onClick={() => useWorldViewStore.setState({ selectedInventoryPos: null })}
          style={{ padding: '1px 7px', fontSize: 14, lineHeight: 1 }}
        >×</button>
      </div>
      <div className="inv-chest-body">
        <div className="inv-grid inv-grid-wide">
          {Array.from({ length: inventorySize }, (_, i) => i + 1).map(slotIdx => (
            <GenericInventorySlot
              key={`${slotIdx}`}
              invSlot={normalized[slotIdx]}
              slotNum={slotIdx}
              computerId={computerId}
              side={side}
              isAdjacent={isAdjacent}
              invokeCommand={invokeCommand}
            />
          ))}
        </div>
      </div>
    </div>
  )
}

// src/components/Inventory.vue
<template>
  <div class="panel">
    <div class="inventory-container">
      <GenericInventorySlot
        v-for="slotIdx in inventorySize"
        :key="`${normalizedInventory[slotIdx] && normalizedInventory[slotIdx].name}${normalizedInventory[slotIdx] && normalizedInventory[slotIdx].count}`"
        :computerId="-1"
        :invSlot="normalizedInventory[slotIdx]"
        :slotNum="slotIdx"
        :isSelected="false"
      />
    </div>
  </div>
</template>

<style scoped>
.inventory-container {
  height: px;
  width: 576px;
  display: grid;
  grid-template-columns: repeat(9, 1fr);
  /* grid-gap: 3%; */
  background-color: lightgray;
}

.panel {
  background-color: lightgray;
}
</style>

<script lang="ts">
import { defineComponent, PropType } from "vue";
import GenericInventorySlot from "./GenericInventorySlot.vue";
import { useWorldStore } from "../store/useWorld";
import { Inventory } from "../types/types";

export default defineComponent({
  setup() {
    const world = useWorldStore();
    return { world };
  },
  components: { GenericInventorySlot },
  props: {
    inventory: {
      required: true,
      type: Object as PropType<Inventory>,
    },
    inventorySize: {
      required: true,
      type: Number,
    }
  },
  computed: {
    normalizedInventory(): Record<number, { name: string; count: number }> {
      const inv = this.inventory as any;
      if (!inv) return {};
      // CC serializes a full (sequential) chest as a JSON array (0-indexed).
      // A sparse chest becomes a JSON object with 1-based string keys.
      // Normalise both to a 1-indexed object so the template can use slotIdx directly.
      if (Array.isArray(inv)) {
        const result: Record<number, any> = {};
        for (let i = 0; i < inv.length; i++) {
          if (inv[i] != null) result[i + 1] = inv[i];
        }
        return result;
      }
      return inv;
    },
  },
});
</script>
