// components/InventorySlot.tsx
'use client'

import { useWorldStore } from '@/store/useWorld'
import { useWorldViewStore } from '@/store/useWorldView'
import type { ItemStack } from '@/types/types'

interface Props {
  computerId: number
  invSlot?: ItemStack
  slotNum?: number
  isSelected: boolean
  onClick?: () => void
}

export default function InventorySlot({ computerId, invSlot, slotNum, isSelected, onClick }: Props) {
  const textureURL = useWorldStore(s => s.textureURL)
  const sendCommand = useWorldStore(s => s.sendCommand)
  const turtleLoc = useWorldStore(s => s.computers[computerId]?.loc)
  const selectedInventoryPos = useWorldViewStore(s => s.selectedInventoryPos)

  const isAdjacentToChest = !!(turtleLoc && selectedInventoryPos &&
    Math.abs(selectedInventoryPos.x - turtleLoc.x) +
    Math.abs(selectedInventoryPos.y - turtleLoc.y) +
    Math.abs(selectedInventoryPos.z - turtleLoc.z) === 1)

  const src = invSlot
    ? `${textureURL}items/${invSlot.name.replace(':', '/')}.png`
    : undefined

  function startDrag(e: React.DragEvent) {
    e.dataTransfer.dropEffect = 'move'
    e.dataTransfer.effectAllowed = 'move'
    e.dataTransfer.setData('slotFrom', String(slotNum))
  }

  function onDrop(e: React.DragEvent) {
    const chestItemData = e.dataTransfer.getData('chestItem')
    if (chestItemData) {
      if (!isAdjacentToChest) return
      const { itemName, side } = JSON.parse(chestItemData)
      sendCommand(computerId, `tapi.suckItem(${JSON.stringify(itemName)}, ${JSON.stringify(side)}, ${e.ctrlKey ? 1 : 64})`)
      return
    }
    const slotFrom = e.dataTransfer.getData('slotFrom')
    sendCommand(
      computerId,
      `local oldSelected = turtle.getSelectedSlot();
      tapi.select(${slotFrom});
      turtle.transferTo(${slotNum}, ${e.ctrlKey ? 64 : 1});
      tapi.select(oldSelected);
      tapi.send_status_update();`
    )
  }

  return (
    <div
      draggable
      onDragStart={startDrag}
      onDrop={onDrop}
      onDragOver={e => e.preventDefault()}
      onDragEnter={e => e.preventDefault()}
      onClick={onClick}
      title={invSlot?.name ?? ''}
      style={{
        backgroundColor: isSelected ? 'rgb(49,172,1)' : '#666666',
        color: 'darkgray',
        minWidth: 0,
        minHeight: 0,
        padding: '10%',
        display: 'block',
        position: 'relative',
        cursor: 'pointer',
      }}
    >
      {src && (
        <img
          style={{ maxWidth: '100%', width: '100%', imageRendering: 'pixelated' }}
          src={src}
          alt={invSlot?.name ?? ''}
          onError={e => { (e.target as HTMLImageElement).src = '/favicon-32x32.png' }}
        />
      )}
      {invSlot && (
        <div style={{
          position: 'absolute', bottom: '10%', right: '15%',
          fontWeight: 'bold', fontFamily: 'Segoe UI, Tahoma, Geneva, Verdana, sans-serif',
          userSelect: 'none',
        }}>
          {invSlot.count}
        </div>
      )}
    </div>
  )
}

// src/components/InventorySlot.vue
<template>
  <div
    draggable
    @drop="onDrop($event)"
    @dragstart="startDrag($event)"
    @dragover.prevent
    @dragenter.prevent
    :class="{ 'inventory-slot': true, 'inventory-selected-slot': isSelected }"
    :title="invSlot ? invSlot.name : ''"
  >
    <img
      class="item-icon"
      :src="
        invSlot
          ? world.textureURL + 'items/' + invSlot.name.replace(':', '/') + '.png'
          : 'https://dummyimage.com/64x64/383e42/383e42.jpg'
      "
      @error="getDefaultItemImage"
    />
    <div v-if="invSlot" class="caption BR">
      {{ invSlot ? invSlot.count : "" }}
    </div>
  </div>
</template>

<style scoped>
.inventory-slot { 
  background-color: #666666;
  color: darkgray;
  min-width: 0;
  min-height: 0;
  padding: 10%;

  display: block;
  position: relative;
  cursor: pointer;

  /* border-style: solid;
  border-width: 10%;
  border-right-color: lightgray;
  border-bottom-color: lightgray;
  vertical-align: middle;
  background-color: gray; */
}
.inventory-selected-slot {
  background-color: rgb(49, 172, 1);
}
.caption {
  font-size: 100%;
  font-weight: bolder;
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
  user-select: none;
}
.BR {
  position: absolute;
  bottom: 10%;
  right: 15%;
}

img.item-icon {
  max-width: 100%;
  width: 100%;
  /* IE, only works on <img> tags */
  -ms-interpolation-mode: nearest-neighbor;
  /* Firefox */
  image-rendering: crisp-edges;
  /* Chromium + Safari */
  image-rendering: pixelated;
}
</style>


<script lang="ts">
import { defineComponent, PropType } from "vue";
import { useWorldStore } from "../store/useWorld";
import { ItemStack } from "../types/types";

export default defineComponent({
  setup() {
    const world = useWorldStore();
    return { world };
  },
  props: {
    computerId: {
      required: true,
      type: Number,
    },
    isSelected: Boolean,
    invSlot: Object as PropType<ItemStack>,
    slotNum: Number,
  },
  methods: {
    startDrag(evt: any) {
      evt.dataTransfer.dropEffect = "move";
      evt.dataTransfer.effectAllowed = "move";
      evt.dataTransfer.setData("slotFrom", this.slotNum);
    },
    onDrop(evt: any) {
      const slotFrom = evt.dataTransfer.getData("slotFrom");
      console.log(`Transfer from slot ${slotFrom} to ${this.slotNum}`);
      this.world.sendCommand(
        this.computerId,
        `local oldSelected = turtle.getSelectedSlot();
        tapi.select(${slotFrom});
        turtle.transferTo(${this.slotNum}, ${evt.ctrlKey ? 64 : 1});
        tapi.select(oldSelected);
        tapi.send_status_update();`
      );
    },
    getDefaultItemImage(evt: any) {
      evt.target.src = "https://dummyimage.com/64x64/000/aaa.jpg&text=Item";
    },
  },
});
</script>
