// components/computers/turtles/KeyboardBindings.tsx
'use client'

import { useEffect } from 'react'
import { useWorldStore } from '@/store/useWorld'
import { useWorldViewStore } from '@/store/useWorldView'

export default function KeyboardBindings() {
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      const tag = (e.target as HTMLElement)?.tagName
      if (tag === 'INPUT' || tag === 'TEXTAREA' || (e.target as HTMLElement)?.isContentEditable) return

      const selectedId = useWorldViewStore.getState().selectedComputerId
      if (selectedId < 0) return

      const send = (cmd: string) => useWorldStore.getState().sendCommand(selectedId, cmd)
      const clear = () => useWorldStore.getState().clearCommandQueue(selectedId)

      switch (e.key) {
        case 'w': send('return tapi.forward()'); break
        case 's': send('return tapi.back()');    break
        case 'a': send('return tapi.left()');    break
        case 'd': send('return tapi.right()');   break
        case 'q': send('return tapi.down()');    break
        case 'e': send('return tapi.up()');      break
        case 'Delete': clear();                  break
      }
    }

    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [])

  return null
}

// src/components/KeyboardBindings.vue
<template>
  
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { useWorldStore } from "../store/useWorld";
import { useWorldViewStore } from "../store/useWorldView";

export default defineComponent({
  setup() {
    const world = useWorldStore();
    const worldView = useWorldViewStore();
    return { world, worldView };
  },
  methods: {
    addKeyboardBindings() {
      document.addEventListener("keydown", this.handleKeyDown);
    },
    handleKeyDown(keyEvent: KeyboardEvent) {
      const tag = (keyEvent.target as HTMLElement)?.tagName;
      if (tag === 'INPUT' || tag === 'TEXTAREA' || (keyEvent.target as HTMLElement)?.isContentEditable) return;
      console.log(keyEvent.key);
      switch(keyEvent.key) {
        case 'w':   this.sendTurtleCmd('return tapi.forward()'); break;
        case 's':   this.sendTurtleCmd('return tapi.back()');    break;
        case 'a':   this.sendTurtleCmd('return tapi.left()');    break;
        case 'd':   this.sendTurtleCmd('return tapi.right()');   break;
        case 'q':   this.sendTurtleCmd('return tapi.down()');    break;
        case 'e':   this.sendTurtleCmd('return tapi.up()');      break;
        case 'Delete': this.clearCmdQueue();              break;
      }
    },
    sendTurtleCmd(cmd: string) {
      if (this.worldView.selectedComputerId < 0) return;
      this.world.sendCommand(this.worldView.selectedComputerId, cmd);
    },
    clearCmdQueue() {
      if (this.worldView.selectedComputerId < 0) return;
      this.world.clearCommandQueue(this.worldView.selectedComputerId);
    },
  },
  mounted() {
    this.addKeyboardBindings();
  },
});
</script>
