// components/computers/LuaTerminal.tsx
'use client'

import { useState } from 'react'
import { useWorldStore } from '@/store/useWorld'
import { useWorldViewStore } from '@/store/useWorldView'

interface Props { computerId: number }

export default function LuaTerminal({ computerId }: Props) {
  const [cmd, setCmd] = useState('')
  const sendCommand = useWorldStore(s => s.sendCommand)
  const commandResult = useWorldStore(s => s.commandResult)
  const selectedComputerId = useWorldViewStore(s => s.selectedComputerId)

  return (
    <>
      <textarea
        style={{ height: 24, backgroundColor: '#383e42', color: 'darkgray', width: '100%', boxSizing: 'border-box' }}
        value={cmd}
        onChange={e => setCmd(e.target.value)}
        onKeyDown={e => e.stopPropagation()}
        placeholder="write lua code here, e.g. return 42"
      />
      <button
        style={{ backgroundColor: '#383e42', color: 'darkgray' }}
        onClick={() => sendCommand(computerId, cmd)}
      >
        Execute
      </button>
      <div style={{ backgroundColor: '#383e42', color: 'darkgray', wordWrap: 'break-word', width: 300 }}>
        {commandResult[selectedComputerId]}
      </div>
    </>
  )
}

// src/components/LuaTerminal.vue
<template>
  <textarea
    @keydown.stop
    class="lua-code"
    v-model="cmd"
    placeholder="write lua code here, e.g. return 42"
  ></textarea>
  <button id="execute" @click="world.sendCommand(computerId, cmd)">Execute</button>
  <div class="command-result">{{ world.commandResult[worldView.selectedComputerId] }}</div>
</template>

<style scoped>
.lua-code {
  height: 24px;
  background-color: #383e42;
  color: darkgray;
}
#execute {
  background-color: #383e42;
  color: darkgray;
}
.command-result {
  background-color: #383e42;
  color: darkgray;
  word-wrap: break-word;
  width: 300px;
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import { useWorldStore } from "../store/useWorld";
import { useWorldViewStore } from "../store/useWorldView";

export default defineComponent({
  setup() {
    let world = useWorldStore();
    let worldView = useWorldViewStore();
    let cmd: string = "";
    return { world, worldView, cmd };
  },
  data() {
    return {
      message: "" as String,
    };
  },
  props: {
    computerId: {
      required: true,
      type: Number,
    },
  },
});
</script>
