// components/computers/minecart/MinecartPanel.tsx
'use client'

import { useState } from 'react'
import { useWorldStore } from '@/store/useWorld'
import { useWorldViewStore } from '@/store/useWorldView'
import LuaTerminal from '../LuaTerminal'
import ComputerLocation from '../ComputerLocation'
import ButtonGrid from '../ButtonGrid'
import ScrollList from '../ScrollList'
import { btn, activeBtn, missingBtn, colors, inputStyle } from '../computerStyles'

interface Props { computerId: number }

export default function MinecartPanel({ computerId }: Props) {
  const computer = useWorldStore(s => s.computers[computerId])
  const sendCommand = useWorldStore(s => s.sendCommand)
  const sendSideCommand = useWorldStore(s => s.sendSideCommand)
  const sendStopSignal = useWorldStore(s => s.sendStopSignal)
  const focusOnComputer = useWorldViewStore(s => s.focusOnComputer)
  const followComputer = useWorldViewStore(s => s.followComputer)
  const followedComputer = useWorldViewStore(s => s.followedComputer)
  const [propelPower, setPropelPower] = useState(1)
  const [loopPropelActive, setLoopPropelActive] = useState(false)

  if (!computer) return null

  const hasKinetic = computer.peripherals?.includes('plethora:kinetic')
  const hasScanner = computer.peripherals?.includes('plethora:scanner')
  const hasSensor = computer.peripherals?.includes('plethora:sensor')
  const isFollowing = followedComputer.computerId === computerId

  function toggleLoopPropel() {
    if (loopPropelActive) {
      sendStopSignal(computerId)
      setLoopPropelActive(false)
    } else {
      sendCommand(computerId, `return capi.propel_loop(${propelPower})`)
      setLoopPropelActive(true)
    }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
      <ComputerLocation loc={computer.loc} />
      <ButtonGrid columns={3}>
        <input
          type="number" min={-2} max={2}
          value={propelPower}
          onChange={e => setPropelPower(Number(e.target.value))}
          style={{ ...inputStyle, padding: '8px 4px', textAlign: 'center' }}
        />
        <button style={hasKinetic ? btn : missingBtn} onClick={() => sendCommand(computerId, `return capi.propel(${propelPower})`)}>Propel</button>
        <button style={hasKinetic ? (loopPropelActive ? activeBtn : btn) : missingBtn} onClick={toggleLoopPropel}>
          Loop Propel: {loopPropelActive ? 'ON' : 'OFF'}
        </button>
        <button style={hasScanner ? btn : missingBtn} onClick={() => loopPropelActive ? sendSideCommand(computerId, 'return capi.scan()') : sendCommand(computerId, 'return capi.scan()')}>Block Scan</button>
        <button style={hasSensor ? btn : missingBtn} onClick={() => loopPropelActive ? sendSideCommand(computerId, 'return capi.sense()') : sendCommand(computerId, 'return capi.sense()')}>Entity Scan</button>
        <button style={btn} onClick={() => focusOnComputer(computerId)}>Focus Camera</button>
        <button style={isFollowing ? activeBtn : btn} onClick={() => followComputer(computerId)}>Toggle Follow</button>
        <button style={btn} onClick={() => sendStopSignal(computerId)}>🛑 Stop 🛑</button>
      </ButtonGrid>

      {computer.entities && computer.entities.length > 0 && (
        <ScrollList label="Nearby Entities" count={computer.entities.length}>
          {computer.entities.map(e => (
            <div key={e.id} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8em', color: colors.text, gap: 8 }}>
              <span style={{ color: colors.textName, whiteSpace: 'nowrap' }}>{e.name}</span>
              <span style={{ color: 'gray', fontSize: '0.9em' }}>{e.x.toFixed(1)}, {e.y.toFixed(1)}, {e.z.toFixed(1)}</span>
            </div>
          ))}
        </ScrollList>
      )}

      {computer.chatLog && computer.chatLog.length > 0 && (
        <ScrollList label="Chat Log">
          {[...computer.chatLog].reverse().slice(0, 20).map((msg, i) => (
            <div key={i} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8em', color: colors.text, gap: 8 }}>
              <span style={{ color: colors.textName, whiteSpace: 'nowrap' }}>{msg.player}:</span>
              <span style={{ color: colors.textLight, flex: 1 }}>{msg.message}</span>
            </div>
          ))}
        </ScrollList>
      )}

      <LuaTerminal computerId={computerId} />
    </div>
  )
}

// src/components/MinecartPanel.vue
<template>
  <div class="panel">
    <div class="location">
      📍 {{ computer.loc.x }}, {{ computer.loc.y }}, {{ computer.loc.z }}
    </div>
    <div class="actions">
      <div class="propel-row">
        <input
          v-model.number="propelPower"
          type="number"
          min="-2"
          max="2"
          class="propel-input"
        />
        <button
          :class="{ missing: computer.peripherals && !computer.peripherals.includes('plethora:kinetic') }"
          @click="world.sendCommand(computerId, `return capi.propel(${propelPower})`)"
        >Propel</button>
        <button
          :class="{ active: loopPropelActive, missing: computer.peripherals && !computer.peripherals.includes('plethora:kinetic') }"
          @click="toggleLoopPropel"
        >Loop Propel: {{ loopPropelActive ? 'ON' : 'OFF' }}</button>
      </div>
      <button
        :class="{ missing: computer.peripherals && !computer.peripherals.includes('plethora:scanner') }"
        @click="loopPropelActive ? world.sendSideCommand(computerId, 'return capi.scan()') : world.sendCommand(computerId, 'return capi.scan()')"
      >Block Scan</button>
      <button
        :class="{ missing: computer.peripherals && !computer.peripherals.includes('plethora:sensor') }"
        @click="loopPropelActive ? world.sendSideCommand(computerId, 'return capi.sense()') : world.sendCommand(computerId, 'return capi.sense()')"
      >Entity Scan</button>
      <button @click="worldView.focusOnComputer(computerId)">Focus Camera</button>
      <button
        :class="{ active: worldView.followedComputer.computerId === computerId }"
        @click="worldView.followComputer(computerId)"
      >Toggle Follow</button>
      <button @click="world.sendStopSignal(computerId)">🛑 Stop 🛑</button>
    </div>

    <div v-if="computer.entities && computer.entities.length > 0" class="section">
      <div class="section-title">Nearby Entities ({{ computer.entities.length }})</div>
      <div class="entity-list">
        <div v-for="e in computer.entities" :key="e.id" class="entity-row">
          <span class="entity-name">{{ e.name }}</span>
          <span class="entity-pos">{{ e.x.toFixed(1) }}, {{ e.y.toFixed(1) }}, {{ e.z.toFixed(1) }}</span>
        </div>
      </div>
    </div>

    <div v-if="computer.chatLog && computer.chatLog.length > 0" class="section">
      <div class="section-title">Chat Log</div>
      <div class="chat-log">
        <div v-for="(msg, i) in [...computer.chatLog].reverse().slice(0, 20)" :key="i" class="chat-row">
          <span class="chat-player">{{ msg.player }}:</span>
          <span class="chat-message">{{ msg.message }}</span>
        </div>
      </div>
    </div>

    <LuaTerminal :computerId="computerId" />
  </div>
</template>

<style scoped>
.panel {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.location {
  font-size: 0.85em;
  color: darkgray;
  padding: 2px 4px;
}
.actions {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 2px;
}
button {
  padding: 8px 0;
  border-radius: 4px;
  background-color: #383e42;
  color: darkgray;
}
.propel-row {
  display: contents;
}
.propel-input {
  padding: 8px 4px;
  border-radius: 4px;
  background-color: #2a2e32;
  color: lightgray;
  border: 1px solid #555;
  text-align: center;
  width: 100%;
}
button.active {
  background-color: rgb(50, 100, 50);
  color: rgb(150, 220, 150);
}
button.missing {
  background-color: rgba(140, 30, 30, 0.6);
  color: rgb(255, 110, 110);
}
.section {
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.section-title {
  font-size: 0.75em;
  color: gray;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}
.entity-list, .chat-log {
  display: flex;
  flex-direction: column;
  gap: 2px;
  max-height: 120px;
  overflow-y: auto;
}
.entity-row, .chat-row {
  display: flex;
  justify-content: space-between;
  font-size: 0.8em;
  color: darkgray;
  gap: 8px;
}
.entity-name, .chat-player {
  color: rgb(180, 180, 220);
  white-space: nowrap;
}
.entity-pos {
  color: gray;
  font-size: 0.9em;
}
.chat-message {
  color: lightgray;
  flex: 1;
}
</style>

<script lang="ts">
import { defineComponent, computed, ref } from "vue";
import { useWorldStore } from "../store/useWorld";
import { useWorldViewStore } from "../store/useWorldView";
import LuaTerminal from "./LuaTerminal.vue";

export default defineComponent({
  components: { LuaTerminal },
  props: {
    computerId: {
      required: true,
      type: Number,
    },
  },
  setup(props) {
    const world = useWorldStore();
    const worldView = useWorldViewStore();
    const computer = computed(() => world.computers[props.computerId]);
    const propelPower = ref(1);
    const loopPropelActive = ref(false);

    function toggleLoopPropel() {
      if (loopPropelActive.value) {
        world.sendStopSignal(props.computerId);
        loopPropelActive.value = false;
      } else {
        world.sendCommand(props.computerId, `return capi.propel_loop(${propelPower.value})`);
        loopPropelActive.value = true;
      }
    }

    return { world, worldView, computer, propelPower, loopPropelActive, toggleLoopPropel };
  },
});
</script>
