// components/Scene.tsx
'use client'

import { useEffect, useRef } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { CameraControls } from '@react-three/drei'
import * as THREE from 'three'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'
import type { Block } from '@/types/types'
import { useWorldStore } from '@/store/useWorld'
import { useWorldViewStore, clearMaterialsCache } from '@/store/useWorldView'
import { ChunkManager } from '@/utils/ChunkManager'
import { CHUNK_SIZE } from '@/utils/WorldChunk'

class TextureAnimator {
  texture: THREE.Texture
  tileDurationMillis: number
  tilesHorizontal: number
  tilesVertical: number
  numberOfTiles: number
  currentDisplayMillis = 0
  currentTile = 0
  forward = true

  constructor(texture: THREE.Texture, tileDurationMillis: number) {
    this.texture = texture
    this.tileDurationMillis = tileDurationMillis
    this.tilesHorizontal = 1
    this.tilesVertical = texture.image.height / texture.image.width
    this.numberOfTiles = this.tilesHorizontal * this.tilesVertical
    texture.wrapS = texture.wrapT = THREE.RepeatWrapping
    texture.repeat.set(1 / this.tilesHorizontal, 1 / this.tilesVertical)
  }

  update(milliSec: number) {
    this.currentDisplayMillis += milliSec
    while (this.currentDisplayMillis > this.tileDurationMillis) {
      this.currentDisplayMillis -= this.tileDurationMillis
      this.currentTile += this.forward ? 1 : -1
      if (this.currentTile === this.numberOfTiles - 1 || this.currentTile === 0)
        this.forward = !this.forward
      this.texture.offset.x = (this.currentTile % this.tilesHorizontal) / this.tilesHorizontal
      this.texture.offset.y = Math.floor(this.currentTile / this.tilesHorizontal) / this.tilesVertical
    }
  }
}

// ─── Inner component — runs inside the R3F Canvas context ─────────────────────

function SceneSetup() {
  const { scene, camera, gl, invalidate } = useThree()
  const controlsRef = useRef<any>(null)

  // Stable Three.js objects (not stored in Zustand — no re-render needed)
  const blocksGroup = useRef(new THREE.Group())
  const entitiesGroup = useRef(new THREE.Group())
  const invGroup = useRef(new THREE.Group())
  const orbitMarker = useRef(new THREE.AxesHelper(0.75))
  const chunkManager = useRef<ChunkManager | null>(null)
  const raycaster = useRef(new THREE.Raycaster())
  const animatedTextures = useRef<TextureAnimator[]>([])
  const invSprites = useRef(new Map<string, THREE.Sprite>())
  const entityMeshes = useRef<Record<string, THREE.Mesh>>({})
  const entityMats = useRef<Record<string, THREE.MeshPhongMaterial>>({})
  const turtleModel = useRef<THREE.Object3D | null>(null)
  const exclMat = useRef<THREE.SpriteMaterial | null>(null)
  const entityGeom = useRef(new THREE.OctahedronGeometry(0.35))
  const prevViewMatrix = useRef(new THREE.Matrix4())

  // ─── Camera / chunk helpers ────────────────────────────────────────────────

  function setCameraFocus(target: THREE.Vector3) {
    controlsRef.current?.moveTo(target.x, target.y, target.z, true)
  }

  function focusOnComputer(computerId: number) {
    const computer = useWorldStore.getState().computers[computerId]
    if (!computer?.loc) return
    setCameraFocus(new THREE.Vector3(computer.loc.x, computer.loc.y, computer.loc.z))
  }

  function updateChunkVisibility() {
    const cm = chunkManager.current
    const controls = controlsRef.current
    if (!cm || !controls) return
    const target = new THREE.Vector3()
    controls.getTarget(target)
    const wv = useWorldViewStore.getState()
    orbitMarker.current.position.copy(target)
    orbitMarker.current.visible = wv.showOrbitMarker
    cm.updateVisibility(
      camera as THREE.PerspectiveCamera,
      target,
      wv.renderDistance * CHUNK_SIZE,
      wv.lockChunks,
    )
  }

  // ─── Raycasting ───────────────────────────────────────────────────────────

  function getBlockPosFromHit(hit: THREE.Intersection): THREE.Vector3 {
    const worldNormal = hit.face!.normal.clone()
      .transformDirection(hit.object.matrixWorld)
      .round()
    const inside = hit.point.clone().addScaledVector(worldNormal, -0.5)
    return new THREE.Vector3(
      Math.floor(inside.x + 0.5),
      Math.floor(inside.y + 0.5),
      Math.floor(inside.z + 0.5),
    )
  }

  function getGotoBlockPosFromHit(hit: THREE.Intersection): THREE.Vector3 {
    const blockPos = getBlockPosFromHit(hit)
    const worldNormal = hit.face!.normal.clone()
      .transformDirection(hit.object.matrixWorld)
      .round()
    return blockPos.clone().add(worldNormal)
  }

  function raycast(e: MouseEvent) {
    const mouse = {
      x: (e.clientX / window.innerWidth) * 2 - 1,
      y: -(e.clientY / window.innerHeight) * 2 + 1,
    }
    raycaster.current.setFromCamera(mouse as any, camera)

    const entityHits = raycaster.current.intersectObjects(entitiesGroup.current.children, false)
    if (entityHits.length > 0) {
      const mesh = entityHits[0].object as THREE.Mesh
      useWorldViewStore.setState({
        hoveredEntity: (mesh as any).userData.entity,
        hoveredBlock: null,
        hoveredBlockPos: null,
        gotoBlockPos: null,
      })
      return
    }
    useWorldViewStore.setState({ hoveredEntity: null })

    const intersects = raycaster.current.intersectObjects(blocksGroup.current.children, false)
    for (const hit of intersects) {
      if (!hit.face) continue
      const blockPos = getBlockPosFromHit(hit)
      const locString = `${blockPos.x},${blockPos.y},${blockPos.z}`
      const block = useWorldStore.getState().blocks[locString]
      if (!block) continue
      useWorldViewStore.setState({
        hoveredBlock: block,
        hoveredBlockPos: blockPos,
        gotoBlockPos: getGotoBlockPosFromHit(hit),
      })
      return
    }
    useWorldViewStore.setState({ hoveredBlock: null, hoveredBlockPos: null, gotoBlockPos: null })
  }

  // ─── Inventory indicators ─────────────────────────────────────────────────

  function addInventoryIndicator(locString: string) {
    if (!exclMat.current || invSprites.current.has(locString)) return
    const [x, y, z] = locString.split(',').map(Number)
    const sprite = new THREE.Sprite(exclMat.current)
    sprite.position.set(x, y + 0.9, z)
    sprite.scale.set(0.5, 0.5, 0.5)
    invGroup.current.add(sprite)
    invSprites.current.set(locString, sprite)
  }

  function removeInventoryIndicator(locString: string) {
    const sprite = invSprites.current.get(locString)
    if (sprite) {
      invGroup.current.remove(sprite)
      invSprites.current.delete(locString)
    }
  }

  // ─── Block management ─────────────────────────────────────────────────────

  function addBlock(locString: string, block: Block) {
    if (!useWorldViewStore.getState().isBlockVisible(locString)) return
    chunkManager.current?.addBlock(locString, block)
    if (block.inventory) addInventoryIndicator(locString)
    else removeInventoryIndicator(locString)
  }

  function removeBlock(locString: string) {
    chunkManager.current?.removeBlock(locString)
    removeInventoryIndicator(locString)
  }

  function clearAllBlocks() {
    chunkManager.current?.clearAll()
  }

  // ─── Entity management ────────────────────────────────────────────────────

  function getEntityMaterial(name: string): THREE.MeshPhongMaterial {
    if (!entityMats.current[name]) {
      const mat = new THREE.MeshPhongMaterial({ color: 0xff8800 })
      entityMats.current[name] = mat
      const loader = new THREE.TextureLoader()
      loader.load(
        useWorldStore.getState().textureURL + `entities/${name.replace(':', '/')}.png`,
        (texture) => {
          texture.minFilter = THREE.NearestFilter
          texture.magFilter = THREE.NearestFilter
          mat.map = texture
          mat.color.setHex(0xffffff)
          mat.needsUpdate = true
        },
        undefined,
        () => { /* no texture — keep fallback orange */ }
      )
    }
    return entityMats.current[name]
  }

  function updateEntities(computerId: string) {
    const computer = useWorldStore.getState().computers[computerId]
    const prefix = `${computerId}:`

    // Remove stale meshes for this computer
    for (const key of Object.keys(entityMeshes.current)) {
      if (!key.startsWith(prefix)) continue
      const mesh = entityMeshes.current[key]
      if (mesh?.parent === entitiesGroup.current) entitiesGroup.current.remove(mesh)
      delete entityMeshes.current[key]
    }

    if (!computer?.entities || !computer.loc) return
    const { x: ox, y: oy, z: oz } = computer.loc
    for (const entity of computer.entities) {
      const mesh = new THREE.Mesh(entityGeom.current, getEntityMaterial(entity.name))
      const wx = ox + entity.x, wy = oy + entity.y, wz = oz + entity.z
      mesh.position.set(wx, wy, wz)
      ;(mesh as any).userData.entity = { ...entity, worldPos: new THREE.Vector3(wx, wy, wz) }
      entitiesGroup.current.add(mesh)
      entityMeshes.current[`${prefix}${entity.id}`] = mesh
    }
  }

  // ─── Computer model management ────────────────────────────────────────────

  function addComputer(computerId: string) {
    if (!turtleModel.current) return
    const computerData = useWorldStore.getState().computers[computerId]
    if (!computerData?.loc) return
    const model = turtleModel.current.clone()
    scene.add(model)
    const wv = useWorldViewStore.getState()
    useWorldViewStore.setState({ computerModels: { ...wv.computerModels, [computerId]: model } })
    const { x, y, z } = computerData.loc
    model.position.set(x, y, z)
    if (computerData.type === 'minecart') {
      model.rotation.set(0, 0, 0)
      chunkManager.current?.removeBlock(`${x},${y},${z}`)
    } else {
      model.rotation.set(Math.PI / 2, 0, ((computerData.rot + 1) * Math.PI) / 2)
    }
  }

  function updateComputer(computerId: string) {
    const wv = useWorldViewStore.getState()
    const model = wv.computerModels[computerId]
    if (!model) { addComputer(computerId); return }
    const computerData = useWorldStore.getState().computers[computerId]
    if (!computerData?.loc) return
    if (computerData.type === 'minecart') {
      const oldX = Math.round(model.position.x)
      const oldY = Math.round(model.position.y)
      const oldZ = Math.round(model.position.z)
      const { x: newX, y: newY, z: newZ } = computerData.loc
      if (oldX !== newX || oldY !== newY || oldZ !== newZ) {
        const oldLoc = `${oldX},${oldY},${oldZ}`
        const oldBlock = useWorldStore.getState().blocks[oldLoc]
        if (oldBlock && wv.isBlockVisible(oldLoc)) chunkManager.current?.addBlock(oldLoc, oldBlock)
        chunkManager.current?.removeBlock(`${newX},${newY},${newZ}`)
      }
      model.rotation.set(0, 0, 0)
    } else {
      model.rotation.set(Math.PI / 2, 0, ((computerData.rot + 1) * Math.PI) / 2)
    }
    model.position.set(computerData.loc.x, computerData.loc.y, computerData.loc.z)
    model.updateMatrix()
  }

  function removeComputerModel(computerId: string) {
    const wv = useWorldViewStore.getState()
    const model = wv.computerModels[computerId]
    if (!model) return
    scene.remove(model)
    const updated = { ...wv.computerModels }
    delete updated[computerId]
    useWorldViewStore.setState({ computerModels: updated })
  }

  // ─── Animated textures ────────────────────────────────────────────────────

  function addAnimatedTexture(texture: THREE.Texture) {
    animatedTextures.current.push(new TextureAnimator(texture, 1000 / 8))
  }

  // ─── Full scene regeneration ──────────────────────────────────────────────

  async function regenerateSceneFromBlocks() {
    // Yield before touching the scene so the browser can finish any in-progress
    // render frame before we start heavy synchronous work (scene clear, etc.).
    await new Promise<void>(r => setTimeout(r, 0))

    const world = useWorldStore.getState()
    const wv = useWorldViewStore.getState()

    // Snapshot children arrays before removal (live arrays shift during remove)
    scene.remove(...[...scene.children])
    blocksGroup.current.remove(...[...blocksGroup.current.children])
    entitiesGroup.current.remove(...[...entitiesGroup.current.children])
    invGroup.current.remove(...[...invGroup.current.children])
    invSprites.current.clear()
    entityMeshes.current = {}
    useWorldViewStore.setState({ computerModels: {} })

    // Lighting
    const dir1 = new THREE.DirectionalLight(0xffffff, 1.5)
    dir1.position.set(1, 2, 3)
    scene.add(dir1)
    const dir2 = new THREE.DirectionalLight(0x888888, 1)
    dir2.position.set(-1, -2, -3)
    scene.add(dir2)
    scene.add(new THREE.AmbientLight(0xffffff, 0.4))

    clearMaterialsCache()
    if (chunkManager.current) chunkManager.current.dispose()
    chunkManager.current = new ChunkManager(blocksGroup.current, wv.fastRender, () => invalidate())

    scene.add(blocksGroup.current)
    scene.add(entitiesGroup.current)
    scene.add(invGroup.current)
    scene.add(orbitMarker.current)

    if (wv.selectedComputerId !== -1) focusOnComputer(wv.selectedComputerId)

    // Build a fast visibility closure from a single state snapshot so bulkLoad
    // doesn't call getState()/require on every block in the world.
    const { yMin, yMax, transparencyList, computerRangeXZ, selectedComputerId, manualCenter } = wv
    const transparencySet = new Set(transparencyList)
    const minecartLocs = new Set<string>()
    for (const id in world.computers) {
      const c = world.computers[id]
      if (c.type === 'minecart' && c.loc) minecartLocs.add(`${c.loc.x},${c.loc.y},${c.loc.z}`)
    }
    let centerX: number | null = null, centerZ: number | null = null
    if (computerRangeXZ !== null) {
      if (selectedComputerId !== -1) {
        const turtle = world.computers[selectedComputerId]
        if (turtle?.loc) { centerX = turtle.loc.x; centerZ = turtle.loc.z }
      } else if (manualCenter) {
        centerX = manualCenter.x; centerZ = manualCenter.z
      }
    }
    const blockSnap = world.blocks
    const isVisible = (locString: string): boolean => {
      const c1 = locString.indexOf(',')
      const c2 = locString.indexOf(',', c1 + 1)
      const y = +locString.slice(c1 + 1, c2)
      if (y < yMin || y > yMax) return false
      if (transparencySet.has(blockSnap[locString]?.name)) return false
      if (minecartLocs.has(locString)) return false
      if (computerRangeXZ !== null && centerX !== null && centerZ !== null) {
        const x = +locString.slice(0, c1)
        const z = +locString.slice(c2 + 1)
        if (Math.abs(x - centerX) > computerRangeXZ || Math.abs(z - centerZ) > computerRangeXZ) return false
      }
      return true
    }

    await chunkManager.current.bulkLoad(world.blocks, isVisible, wv.skipLoadYield)

    updateChunkVisibility()

    for (const locString in world.blocks) {
      if (world.blocks[locString].inventory) addInventoryIndicator(locString)
    }

    for (const computerId in world.computers) {
      addComputer(computerId)
      updateEntities(computerId)
    }
  }

  // ─── Mount / unmount ───────────────────────────────────────────────────────

  useEffect(() => {
    // Load turtle model
    new GLTFLoader().load(
      'textures/turtle/CCTurtle_happy.glb',
      (gltf) => { turtleModel.current = gltf.scene },
      undefined,
      (e) => console.error(e),
    )

    // Build exclamation sprite material using canvas
    const exclCanvas = document.createElement('canvas')
    exclCanvas.width = 64; exclCanvas.height = 64
    const ctx = exclCanvas.getContext('2d')!
    ctx.fillStyle = 'rgba(0,0,0,0.55)'
    ctx.beginPath(); ctx.arc(32, 32, 28, 0, Math.PI * 2); ctx.fill()
    ctx.fillStyle = '#ffffff'
    ctx.font = 'bold 52px sans-serif'
    ctx.textAlign = 'center'
    ctx.textBaseline = 'middle'
    ctx.fillText('!', 32, 34)
    exclMat.current = new THREE.SpriteMaterial({
      map: new THREE.CanvasTexture(exclCanvas),
      depthTest: false,
    })

    orbitMarker.current.visible = false

    // DOM event listeners on the WebGL canvas
    const domEl = gl.domElement

    const handleClick = (e: MouseEvent) => {
      raycast(e)
      const wv = useWorldViewStore.getState()
      if (wv.hoveredEntity) {
        useWorldViewStore.setState({ selectedInventory: null, selectedInventorySize: 0 })
      } else if (wv.hoveredBlock?.inventory) {
        useWorldViewStore.setState({
          selectedInventory: wv.hoveredBlock.inventory,
          selectedInventorySize: wv.hoveredBlock.inventorySize as number,
          selectedInventoryPos: wv.hoveredBlockPos ? { x: wv.hoveredBlockPos.x, y: wv.hoveredBlockPos.y, z: wv.hoveredBlockPos.z } : null,
        })
      } else {
        useWorldViewStore.setState({ selectedInventory: null, selectedInventorySize: 0 })
      }
    }

    const handleDblClick = (e: MouseEvent) => {
      raycast(e)
      const wv = useWorldViewStore.getState()
      if (!wv.selectedComputerId || wv.selectedComputerId === -1 || !wv.gotoBlockPos) return
      const loc = wv.gotoBlockPos
      useWorldStore.getState().sendCommand(
        wv.selectedComputerId,
        `tapi.goTo(${loc.x},${loc.y},${loc.z})`,
      )
    }

    let lastMouseMove = 0
    const handleMouseMove = (e: MouseEvent) => {
      if (useWorldViewStore.getState().lockBlockInfo) return
      const now = performance.now()
      if (now - lastMouseMove < 33) return
      lastMouseMove = now
      raycast(e)
    }

    domEl.addEventListener('mousemove', handleMouseMove)
    domEl.addEventListener('click', handleClick)
    domEl.addEventListener('dblclick', handleDblClick)

    // Register all worldView store callbacks so other stores can drive the scene
    useWorldViewStore.setState({
      regenerateSceneFromBlocks,
      render: () => invalidate(),
      setCameraFocus,
      focusOnComputer,
      addBlock,
      removeBlock,
      clearAllBlocks,
      updateComputer,
      updateEntities,
      removeComputerModel,
      addAnimatedTexture,
      updateChunkVisibility,
    })

    return () => {
      domEl.removeEventListener('mousemove', handleMouseMove)
      domEl.removeEventListener('click', handleClick)
      domEl.removeEventListener('dblclick', handleDblClick)
      chunkManager.current?.dispose()
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  // ─── Animation loop ────────────────────────────────────────────────────────

  useFrame((state, delta) => {
    const wv = useWorldViewStore.getState()
    const computerId = wv.followedComputer.computerId
    if (computerId !== -1) {
      const currPos = useWorldStore.getState().computers[computerId]?.loc
      const lastPos = wv.followedComputer.lastPos
      if (currPos && lastPos &&
        (currPos.x !== lastPos.x || currPos.y !== lastPos.y || currPos.z !== lastPos.z)) {
        setCameraFocus(new THREE.Vector3(currPos.x, currPos.y, currPos.z))
        useWorldViewStore.setState(s => ({ followedComputer: { ...s.followedComputer, lastPos: currPos } }))
      }
    }

    if (animatedTextures.current.length > 0) {
      for (const anim of animatedTextures.current) {
        anim.update(delta * 1000)
      }
      state.invalidate()
    }

    // Only recalculate chunk visibility when the camera has actually moved.
    state.camera.updateMatrixWorld()
    if (!state.camera.matrixWorldInverse.equals(prevViewMatrix.current)) {
      prevViewMatrix.current.copy(state.camera.matrixWorldInverse)
      updateChunkVisibility()
    }
  })

  return (
    <>
      <color attach="background" args={['#111318']} />
      <CameraControls ref={controlsRef} makeDefault />
    </>
  )
}

// ─── Public export — renders the R3F Canvas ───────────────────────────────────

export default function Scene() {
  return (
    <Canvas
      frameloop="demand"
      style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, zIndex: 0 }}
      camera={{ fov: 45, near: 1, far: 10000, position: [-4, 5, -10] }}
    >
      <SceneSetup />
    </Canvas>
  )
}

// src/components/Scene.vue
<template>
  <div class="scene"></div>
</template>

<script lang="ts">
import { defineComponent, ref, toRaw } from "vue";
import { useWorldStore } from "../store/useWorld";
import { useWorldViewStore } from "../store/useWorldView";
import * as THREE from "three";
import CameraControls from "camera-controls";
import { PerspectiveCamera, Scene } from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { Block } from "../types/types";
import { ChunkManager } from "../utils/ChunkManager";
import { CHUNK_SIZE } from "../utils/WorldChunk";

CameraControls.install({ THREE: THREE });

var scene: Scene,
  camera: PerspectiveCamera,
  renderer: THREE.WebGLRenderer,
  cameraControls: CameraControls,
  blocks: THREE.Group,
  entities: THREE.Group,
  inventoryIndicators: THREE.Group,
  inventorySprites = new Map<string, THREE.Sprite>(),
  exclamationMaterial: THREE.SpriteMaterial,
  raycaster: THREE.Raycaster,
  clock: THREE.Clock,
  mouse = { x: 0, y: 0 },
  turtleModel: THREE.Object3D,
  chunkManager: ChunkManager,
  animatedTextures = [] as TextureAnimator[],
  entityGeometry: THREE.OctahedronGeometry,
  entityMaterials: { [name: string]: THREE.MeshPhongMaterial } = {},
  entityFallbackMaterial: THREE.MeshPhongMaterial,
  // Raw (non-reactive) store references for the animate() hot path.
  // toRaw() strips Vue's Proxy wrapper so repeated per-frame reads don't
  // pay the Reflect.get / reactive-tracking overhead on every access.
  rawWorld: ReturnType<typeof useWorldStore>,
  rawWorldView: ReturnType<typeof useWorldViewStore>;

class TextureAnimator {
  texture: THREE.Texture;
  tileDurationMillis: number;
  tilesHorizontal: number;
  tilesVertical: number;
  numberOfTiles: number;
  currentDisplayMillis: number;
  currentTile: number;
  forward: boolean;

  constructor(texture: THREE.Texture, tileDurationMillis: number) {
    this.texture = texture;
    this.tileDurationMillis = tileDurationMillis;
    this.tilesHorizontal = 1;
    this.tilesVertical = texture.image.height / texture.image.width;
    this.numberOfTiles = this.tilesHorizontal * this.tilesVertical;
    texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
    texture.repeat.set(1 / this.tilesHorizontal, 1 / this.tilesVertical);
    this.currentDisplayMillis = 0;
    this.currentTile = 0;
    this.forward = true;
  }

  update(milliSec: number) {
    this.currentDisplayMillis += milliSec;
    while (this.currentDisplayMillis > this.tileDurationMillis) {
      this.currentDisplayMillis -= this.tileDurationMillis;
      this.currentTile += this.forward ? 1 : -1;
      if (this.currentTile == this.numberOfTiles - 1 || this.currentTile == 0)
        this.forward = !this.forward;
      const currentColumn = this.currentTile % this.tilesHorizontal;
      const currentRow = Math.floor(this.currentTile / this.tilesHorizontal);
      this.texture.offset.x = currentColumn / this.tilesHorizontal;
      this.texture.offset.y = currentRow / this.tilesVertical;
    }
  }
}

export default defineComponent({
  setup() {
    const world = useWorldStore();
    const worldView = useWorldViewStore();
    const geometry = new THREE.BoxGeometry();

    rawWorld = toRaw(world);
    rawWorldView = toRaw(worldView);

    return { world, worldView, geometry };
  },
  methods: {
    onWindowResize() {
      camera.aspect = window.innerWidth / window.innerHeight;
      camera.updateProjectionMatrix();

      renderer.setSize(window.innerWidth, window.innerHeight);
      renderer.render(scene, camera);
    },
    initScene() {
      const loader = new GLTFLoader();

      loader.load(
        "textures/turtle/CCTurtle_happy.glb",
        (gltf) => (turtleModel = gltf.scene),
        undefined,
        (error) => console.error(error)
      );
      renderer = new THREE.WebGLRenderer();
      renderer.setSize(window.innerWidth, window.innerHeight);

      raycaster = new THREE.Raycaster();
      renderer.domElement.addEventListener(
        "dblclick",
        (e) => {
          this.raycast(e);
          if (
            isNaN(this.worldView.selectedComputerId) ||
            this.worldView.selectedComputerId == -1 ||
            this.worldView.gotoBlockPos == null
          )
            return;
          const hLoc = this.worldView.gotoBlockPos;
          this.world.sendCommand(
            this.worldView.selectedComputerId,
            "tapi.goTo(" + hLoc.x + "," + hLoc.y + "," + hLoc.z + ")"
          );
        },
        false
      );

      renderer.domElement.addEventListener(
        "click",
        (e) => {
          this.raycast(e);
          if (this.worldView.hoveredEntity) {
            // entity click — inventory display not applicable
            this.worldView.selectedInventory = null;
            this.worldView.selectedInventorySize = 0;
          } else if (
            this.worldView.hoveredBlock &&
            this.worldView.hoveredBlock.inventory
          ) {
            this.worldView.selectedInventory =
              this.worldView.hoveredBlock.inventory;
            this.worldView.selectedInventorySize = this.worldView.hoveredBlock
              .inventorySize as number;
          } else {
            this.worldView.selectedInventory = null;
            this.worldView.selectedInventorySize = 0;
          }
        },
        false
      );

      // renderer.domElement.addEventListener("mousemove", this.raycast, false);

      window.addEventListener("resize", this.onWindowResize, false);

      document.body.appendChild(renderer.domElement);

      clock = new THREE.Clock();

      camera = new THREE.PerspectiveCamera(
        45,
        window.innerWidth / window.innerHeight,
        1,
        10000
      );
      camera.position.set(-4, 5, -10);
      camera.lookAt(0, 0, 0);

      scene = new THREE.Scene();
      blocks = new THREE.Group();
      scene.add(blocks);
      entities = new THREE.Group();
      scene.add(entities);

      const exclCanvas = document.createElement('canvas');
      exclCanvas.width = 64;
      exclCanvas.height = 64;
      const exclCtx = exclCanvas.getContext('2d')!;
      exclCtx.fillStyle = 'rgba(0,0,0,0.55)';
      exclCtx.beginPath();
      exclCtx.arc(32, 32, 28, 0, Math.PI * 2);
      exclCtx.fill();
      exclCtx.fillStyle = '#ffffff';
      exclCtx.font = 'bold 52px sans-serif';
      exclCtx.textAlign = 'center';
      exclCtx.textBaseline = 'middle';
      exclCtx.fillText('!', 32, 34);
      exclamationMaterial = new THREE.SpriteMaterial({ map: new THREE.CanvasTexture(exclCanvas), depthTest: false });
      inventoryIndicators = new THREE.Group();
      scene.add(inventoryIndicators);

      entityGeometry = new THREE.OctahedronGeometry(0.35);
      entityFallbackMaterial = new THREE.MeshPhongMaterial({ color: 0xff8800 });

      cameraControls = new CameraControls(camera, renderer.domElement);

      // Re-evaluate chunk visibility whenever the camera moves or rotates.
      cameraControls.addEventListener('update', () => this.updateChunkVisibility());

      renderer.render(scene, camera);
    },
    /** Given a raycast hit on a merged chunk mesh, return the block integer coords. */
    getBlockPosFromHit(hit: THREE.Intersection): THREE.Vector3 {
      // Transform the face normal from local mesh space to world space.
      const worldNormal = hit.face!.normal.clone()
        .transformDirection(hit.object.matrixWorld)
        .round(); // snap to ±1 on one axis
      // Step inward from the hit surface by 0.5 to land inside the struck block.
      const inside = hit.point.clone().addScaledVector(worldNormal, -0.5);
      return new THREE.Vector3(
        Math.floor(inside.x + 0.5),
        Math.floor(inside.y + 0.5),
        Math.floor(inside.z + 0.5),
      );
    },
    /** Return the adjacent air block the player would place a block into (one step outward). */
    getGotoBlockPosFromHit(hit: THREE.Intersection): THREE.Vector3 {
      const blockPos = this.getBlockPosFromHit(hit);
      const worldNormal = hit.face!.normal.clone()
        .transformDirection(hit.object.matrixWorld)
        .round();
      return blockPos.clone().add(worldNormal);
    },
    animate() {
      const delta = clock.getDelta();

      // Check if followed turtle moved. Use raw (non-reactive) store refs so
      // these per-frame reads don't pay Vue Proxy / Reflect.get overhead.
      const computerId = rawWorldView.followedComputer.computerId;
      if (computerId != -1) {
        const currPos = rawWorld.computers[computerId]?.loc;
        const lastPos = rawWorldView.followedComputer.lastPos;
        if (
          currPos && lastPos &&
          (currPos.x !== lastPos.x ||
          currPos.y !== lastPos.y ||
          currPos.z !== lastPos.z)
        ) {
          rawWorldView.setCameraFocus(
            new THREE.Vector3(currPos.x, currPos.y, currPos.z)
          );
          // Write directly to raw object — lastPos is only read here, so no
          // reactive notification is needed and this avoids Proxy setter cost.
          rawWorldView.followedComputer.lastPos = currPos;
        }
      }

      cameraControls.update(delta);
      for (const el of animatedTextures) {
        el.update(delta * 1000);
      }
      requestAnimationFrame(this.animate);
      this.render();
    },
    raycast(e: any) {
      mouse.x = (e.clientX / window.innerWidth) * 2 - 1;
      mouse.y = -(e.clientY / window.innerHeight) * 2 + 1;
      raycaster.setFromCamera(mouse, camera);

      // Check entities first — they're smaller and would lose to blocks otherwise
      const entityHits = raycaster.intersectObjects(entities.children, false);
      if (entityHits.length > 0) {
        const mesh = entityHits[0].object as THREE.Mesh;
        this.worldView.hoveredEntity = (mesh as any).userData.entity;
        this.worldView.hoveredBlock = null;
        this.worldView.hoveredBlockPos = null;
        this.worldView.gotoBlockPos = null;
        return;
      }
      this.worldView.hoveredEntity = null;

      // Blocks are now merged chunk meshes (THREE.Mesh with BufferGeometry).
      // Use the face normal + hit point to recover the integer block coordinate.
      const intersects = raycaster.intersectObjects(blocks.children, false);
      for (const hit of intersects) {
        if (!hit.face) continue;
        const blockPos = this.getBlockPosFromHit(hit);
        const locString = `${blockPos.x},${blockPos.y},${blockPos.z}`;
        const block = this.world.blocks[locString];
        if (!block) continue; // transparent face or gap — keep searching
        this.worldView.hoveredBlock = block;
        this.worldView.hoveredBlockPos = blockPos;
        this.worldView.gotoBlockPos = this.getGotoBlockPosFromHit(hit);
        return;
      }
      this.worldView.hoveredBlock = null;
      this.worldView.hoveredBlockPos = null;
      this.worldView.gotoBlockPos = null;
    },
    async regenerateSceneFromBlocks() {
      const world = useWorldStore();

      // delete objects
      scene.remove.apply(scene, scene.children);
      blocks.remove.apply(blocks, blocks.children);
      entities.remove.apply(entities, entities.children);
      inventoryIndicators.remove.apply(inventoryIndicators, inventoryIndicators.children);
      inventorySprites.clear();
      this.worldView.entityMeshes = {};
      this.worldView.computerModels = {};

      // add lighting
      const directionalLight = new THREE.DirectionalLight(0xffffff, 1);
      directionalLight.position.set(1, 2, 3);
      scene.add(directionalLight);
      const directionalLight2 = new THREE.DirectionalLight(0x777777, 1);
      directionalLight2.position.set(-1, -2, -3);
      scene.add(directionalLight2);
      const ambientLight = new THREE.AmbientLight(0x404040); // soft white light
      scene.add(ambientLight);

      if (chunkManager) chunkManager.dispose();
      chunkManager = new ChunkManager(blocks, rawWorldView.fastRender);

      // Add groups to scene first so blocks appear progressively during async load.
      scene.add(blocks);
      scene.add(entities);
      scene.add(inventoryIndicators);

      // Position the camera before blocks start loading so the first rendered
      // chunks appear around a known location rather than the origin.
      if (this.worldView.selectedComputerId !== -1) {
        this.focusOnComputer(this.worldView.selectedComputerId);
      }

      // Bulk-load: partition all blocks into chunks, kick off async builds.
      await chunkManager.bulkLoad(
        world.blocks,
        (loc) => this.worldView.isBlockVisible(loc),
        rawWorldView.skipLoadYield,
      );

      // Initial visibility pass with current camera state.
      this.updateChunkVisibility();

      // Inventory indicators are cheap — add them after the bulk load.
      for (const locString in world.blocks) {
        if (world.blocks[locString].inventory) {
          this.addInventoryIndicator(locString);
        }
      }

      this.addComputers();
    },
    addInventoryIndicator(locString: string) {
      if (inventorySprites.has(locString)) return;
      const [x, y, z] = locString.split(',').map(Number);
      const sprite = new THREE.Sprite(exclamationMaterial);
      sprite.position.set(x, y + 0.9, z);
      sprite.scale.set(0.5, 0.5, 0.5);
      inventoryIndicators.add(sprite);
      inventorySprites.set(locString, sprite);
    },
    removeInventoryIndicator(locString: string) {
      const sprite = inventorySprites.get(locString);
      if (sprite) {
        inventoryIndicators.remove(sprite);
        inventorySprites.delete(locString);
      }
    },
    addBlock(locString: string, block: Block) {
      if (!this.worldView.isBlockVisible(locString)) return;
      chunkManager.addBlock(locString, block);
      if (block.inventory) {
        this.addInventoryIndicator(locString);
      } else {
        this.removeInventoryIndicator(locString);
      }
    },
    removeBlock(locString: string) {
      chunkManager.removeBlock(locString);
      this.removeInventoryIndicator(locString);
    },
    clearAllBlocks() {
      chunkManager.clearAll();
    },
    updateChunkVisibility() {
      if (!chunkManager || !camera || !cameraControls) return;
      const target = new THREE.Vector3();
      cameraControls.getTarget(target);
      chunkManager.updateVisibility(camera, target, rawWorldView.renderDistance * CHUNK_SIZE, rawWorldView.lockChunks);
    },
    addComputers() {
      for (const computerId in this.world.computers) {
        this.addComputer(computerId);
        this.updateEntities(computerId);
      }
    },
    addComputer(computerId: string) {
      const computerData = this.world.computers[computerId];
      if (!computerData?.loc) return;
      const model = turtleModel.clone();
      scene.add(model);
      this.worldView.computerModels[computerId] = model;
      model.position.set(computerData.loc.x, computerData.loc.y, computerData.loc.z);
      if (computerData.type === 'minecart') {
        model.rotation.set(0, 0, 0);
        const locString = `${computerData.loc.x},${computerData.loc.y},${computerData.loc.z}`;
        chunkManager.removeBlock(locString);
      } else {
        model.rotation.set(Math.PI / 2, 0, ((computerData.rot + 1) * Math.PI) / 2);
      }
    },
    updateComputer(computerId: string) {
      let model = this.worldView.computerModels[computerId];
      if (!model) {
        this.addComputer(computerId);
        return;
      }
      const computerData = this.world.computers[computerId];
      if (!computerData?.loc) return;
      if (computerData.type === 'minecart') {
        const oldX = Math.round(model.position.x);
        const oldY = Math.round(model.position.y);
        const oldZ = Math.round(model.position.z);
        const newX = computerData.loc.x;
        const newY = computerData.loc.y;
        const newZ = computerData.loc.z;
        if (oldX !== newX || oldY !== newY || oldZ !== newZ) {
          const oldLocString = `${oldX},${oldY},${oldZ}`;
          const oldBlock = this.world.blocks[oldLocString];
          if (oldBlock && this.worldView.isBlockVisible(oldLocString)) {
            chunkManager.addBlock(oldLocString, oldBlock);
          }
          chunkManager.removeBlock(`${newX},${newY},${newZ}`);
        }
        model.rotation.set(0, 0, 0);
      } else {
        model.rotation.set(Math.PI / 2, 0, ((computerData.rot + 1) * Math.PI) / 2);
      }
      model.position.set(computerData.loc.x, computerData.loc.y, computerData.loc.z);
      model.updateMatrix();
    },
    getEntityMaterial(name: string): THREE.MeshPhongMaterial {
      if (!entityMaterials[name]) {
        const mat = new THREE.MeshPhongMaterial({ color: 0xff8800 });
        entityMaterials[name] = mat;
        const loader = new THREE.TextureLoader();
        const world = useWorldStore();
        loader.load(
          world.textureURL + `entities/${name.replace(':', '/')}.png`,
          (texture) => {
            texture.minFilter = THREE.NearestFilter;
            texture.magFilter = THREE.NearestFilter;
            mat.map = texture;
            mat.color.setHex(0xffffff);
            mat.needsUpdate = true;
          },
          undefined,
          () => { /* no texture found — keep fallback orange */ }
        );
      }
      return entityMaterials[name];
    },
    updateEntities(computerId: string) {
      const computer = this.world.computers[computerId];
      const prefix = `${computerId}:`;

      // Remove old meshes for this computer before adding new ones
      const oldKeys = Object.keys(this.worldView.entityMeshes).filter(key => key.startsWith(prefix));
      for (const key of oldKeys) {
        const mesh = this.worldView.entityMeshes[key];
        if (mesh && mesh.parent === entities) {
          entities.remove(mesh);
        }
        delete this.worldView.entityMeshes[key];
      }

      if (!computer?.entities || !computer.loc) return;
      const origin = computer.loc;

      for (const entity of computer.entities) {
        const mat = this.getEntityMaterial(entity.name);
        const mesh = new THREE.Mesh(entityGeometry, mat);
        const wx = origin.x + entity.x;
        const wy = origin.y + entity.y;
        const wz = origin.z + entity.z;
        mesh.position.set(wx, wy, wz);
        (mesh as any).userData.entity = {
          ...entity,
          worldPos: new THREE.Vector3(wx, wy, wz),
        };
        entities.add(mesh);
        this.worldView.entityMeshes[`${prefix}${entity.id}`] = mesh;
      }
    },
    removeComputerModel(computerId: string) {
      const model = this.worldView.computerModels[computerId];
      if (model) {
        scene.remove(model);
        delete this.worldView.computerModels[computerId];
      }
    },
    setCameraFocus(target: THREE.Vector3) {
      cameraControls.moveTo(target.x, target.y, target.z, true);
    },
    focusOnComputer(computerId: number) {
      const world = useWorldStore();
      const computer = world.computers[computerId];
      if (!computer?.loc) return;
      this.setCameraFocus(
        new THREE.Vector3(computer.loc.x, computer.loc.y, computer.loc.z)
      );
    },
    addAnimatedTexture(texture: THREE.Texture) {
      animatedTextures.push(new TextureAnimator(texture, 1000 / 8));
    },
    render() {
      renderer.render(scene, camera);
    },
  },
  mounted() {
    this.initScene();
    this.animate();
    const worldView = useWorldViewStore();
    worldView.regenerateSceneFromBlocks = this.regenerateSceneFromBlocks;
    worldView.render = this.render;
    worldView.setCameraFocus = this.setCameraFocus;
    worldView.focusOnComputer = this.focusOnComputer;
    worldView.addBlock = this.addBlock;
    worldView.removeBlock = this.removeBlock;
    worldView.clearAllBlocks = this.clearAllBlocks;
    worldView.updateComputer = this.updateComputer;
    worldView.updateEntities = this.updateEntities;
    worldView.removeComputerModel = this.removeComputerModel;
    worldView.addAnimatedTexture = this.addAnimatedTexture;
    worldView.updateChunkVisibility = this.updateChunkVisibility;
  },
});
</script>
