// src/components/computers/turtles/TurtleInventory.tsx
'use client'

import { useShallow } from 'zustand/react/shallow'
import { useWorldStore } from '@/store/useWorld'
import InventorySlot from '../../inventory/InventorySlot'
import type { ItemStack } from '@/types/world'

interface Props { computerId: number }

export default function TurtleInventory({ computerId }: Props) {
  const { inv, selectedSlot } = useWorldStore(
    useShallow(s => ({ inv: (s.computers[computerId] as any)?.inv as ItemStack[] | undefined, selectedSlot: (s.computers[computerId] as any)?.selectedSlot as number | undefined }))
  )
  const invokeCommand = useWorldStore(s => s.invokeCommand)
  if (!inv) return null

  return (
    <div className="inv-grid">
      {inv.map((slot, index) => (
        <InventorySlot
          key={index + 1}
          computerId={computerId}
          invSlot={slot ?? undefined}
          slotNum={index + 1}
          isSelected={index === (selectedSlot ?? 0) - 1}
          onClick={() => invokeCommand(computerId, 'select', [index + 1])}
        />
      ))}
    </div>
  )
}

// src/components/TurtleInventory.vue
<template>
  <div class="inventory-wrapper">
    <div class="inventory-container">
      <InventorySlot
        v-for="[index, slot] in world.computers[computerId].inv.entries()"
        :key="index + 1"
        :computerId="computerId"
        :invSlot="slot"
        :slotNum="index + 1"
        :isSelected="index === world.computers[computerId].selectedSlot - 1"
        @click="
          world.sendCommand(
            computerId,
            'tapi.select(' + (index + 1).toString() + ')'
          )
        "
      />
    </div>
  </div>
</template>

<style scoped>
.inventory-container {
  height: 256px;
  width: 256px;
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  grid-gap: 3%;
  background-color: #383e42;
  color: darkgray;
}

.inventory-wrapper {
  background-color: #383e42;
  color: darkgray;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import InventorySlot from "./InventorySlot.vue";
import { useWorldStore } from "../store/useWorld";

export default defineComponent({
  setup() {
    const world = useWorldStore();
    return { world };
  },
  components: { InventorySlot },
  props: {
    computerId: {
      required: true,
      type: Number,
    },
  },
});
</script>
