// src/components/ModemPanel.vue
<template>
  <div class="modem-panel">
    <div class="modem-title">
      📡 Modem Server {{ computerId }}
      <span class="modem-status-badge" :class="world.modemServerId !== null ? 'modem-online' : 'modem-offline'">
        {{ world.modemServerId !== null ? 'online' : 'offline' }}
      </span>
    </div>

    <div class="client-section">
      <div class="section-label">
        Routing {{ clients.length }} computer{{ clients.length !== 1 ? 's' : '' }}
      </div>
      <div v-if="clients.length === 0" class="no-clients">
        No computers currently routing through this modem.
      </div>
      <div
        v-for="id in clients"
        :key="id"
        class="client-row"
        @click="selectComputer(id)"
      >
        <span class="client-type">{{ world.computers[id]?.type === 'minecart' ? 'Minecart' : 'Turtle' }}</span>
        <span class="client-id">{{ id }}</span>
        <span class="client-label">{{ world.computers[id]?.label }}</span>
      </div>
    </div>

    <LuaTerminal :computerId="computerId" />
  </div>
</template>

<style scoped>
.modem-panel {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.modem-title {
  font-size: 0.9em;
  font-weight: bold;
  color: rgb(120, 180, 240);
  display: flex;
  align-items: baseline;
  gap: 6px;
}
.modem-status-badge {
  font-size: 0.8em;
  font-weight: normal;
  letter-spacing: 0.04em;
  text-transform: uppercase;
}
.modem-online { color: rgb(80, 200, 80); }
.modem-offline { color: rgb(120, 120, 120); }
.section-label {
  font-size: 0.75em;
  color: gray;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  margin-bottom: 2px;
}
.no-clients {
  font-size: 0.8em;
  color: gray;
  font-style: italic;
}
.client-row {
  display: flex;
  gap: 6px;
  align-items: baseline;
  font-size: 0.85em;
  padding: 3px 6px;
  border-radius: 3px;
  cursor: pointer;
  color: darkgray;
}
.client-row:hover {
  background-color: rgba(255, 255, 255, 0.05);
  color: lightgray;
}
.client-type {
  color: gray;
  font-size: 0.9em;
}
.client-id {
  color: rgb(120, 180, 240);
  font-weight: bold;
  min-width: 24px;
}
.client-label {
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>

<script lang="ts">
import { defineComponent, computed } from "vue";
import { useWorldStore } from "../store/useWorld";
import { useWorldViewStore } from "../store/useWorldView";
import LuaTerminal from "./LuaTerminal.vue";

export default defineComponent({
  components: { LuaTerminal },
  props: {
    computerId: {
      required: true,
      type: Number,
    },
  },
  setup(props) {
    const world = useWorldStore();
    const worldView = useWorldViewStore();

    const clients = computed(() =>
      Object.keys(world.computers)
        .map(Number)
        .filter(id => id !== props.computerId && world.computers[id]?.via_modem)
    );

    function selectComputer(id: number) {
      worldView.selectedComputerId = id;
      worldView.followComputer(id);
    }

    return { world, worldView, clients, selectComputer };
  },
});
</script>

// components/computers/modem/ModemPanel.tsx
'use client'

import { useWorldStore } from '@/store/useWorld'
import { useWorldViewStore } from '@/store/useWorldView'
import LuaTerminal from '../LuaTerminal'

interface Props { computerId: number }

export default function ModemPanel({ computerId }: Props) {
  const computers = useWorldStore(s => s.computers)
  const modemServerId = useWorldStore(s => s.modemServerId)
  const setSelectedComputerId = useWorldViewStore(s => s.setSelectedComputerId)
  const followComputer = useWorldViewStore(s => s.followComputer)

  const clients = Object.keys(computers)
    .map(Number)
    .filter(id => id !== computerId && computers[id]?.via_modem)

  function selectComputer(id: number) {
    setSelectedComputerId(id)
    followComputer(id)
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
      <div style={{ fontSize: '0.9em', fontWeight: 'bold', color: 'rgb(120,180,240)', display: 'flex', alignItems: 'baseline', gap: 6 }}>
        📡 Modem Server {computerId}
        <span style={{ fontSize: '0.8em', fontWeight: 'normal', letterSpacing: '0.04em', textTransform: 'uppercase', color: modemServerId !== null ? 'rgb(80,200,80)' : 'rgb(120,120,120)' }}>
          {modemServerId !== null ? 'online' : 'offline'}
        </span>
      </div>

      <div>
        <div style={{ fontSize: '0.75em', color: 'gray', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 2 }}>
          Routing {clients.length} computer{clients.length !== 1 ? 's' : ''}
        </div>
        {clients.length === 0 ? (
          <div style={{ fontSize: '0.8em', color: 'gray', fontStyle: 'italic' }}>No computers currently routing through this modem.</div>
        ) : clients.map(id => (
          <div
            key={id}
            onClick={() => selectComputer(id)}
            style={{ display: 'flex', gap: 6, alignItems: 'baseline', fontSize: '0.85em', padding: '3px 6px', borderRadius: 3, cursor: 'pointer', color: 'darkgray' }}
          >
            <span style={{ color: 'gray', fontSize: '0.9em' }}>{computers[id]?.type === 'minecart' ? 'Minecart' : 'Turtle'}</span>
            <span style={{ color: 'rgb(120,180,240)', fontWeight: 'bold', minWidth: 24 }}>{id}</span>
            <span style={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{computers[id]?.label}</span>
          </div>
        ))}
      </div>

      <LuaTerminal computerId={computerId} />
    </div>
  )
}
