// src/components/OperatorRequest.vue
<template>
  <div class="operator-request">
    <button class="toggle" @click="open = !open">{{ open ? '▾' : '▸' }} Operator access</button>
    <div v-if="open">
      <a v-if="!user.isLoggedIn" class="action" href="/api/signin">Sign in</a>
      <template v-else>
        <p v-if="message" class="message">{{ message }}</p>
        <button v-else class="action" @click="request" :disabled="loading">Request access</button>
      </template>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useUserStore } from '../store/useUser';

export default defineComponent({
  setup() {
    return { user: useUserStore() };
  },
  data() {
    return {
      open: false,
      loading: false,
      message: '' as string,
    };
  },
  methods: {
    async request() {
      this.loading = true;
      const res = await fetch('/api/requestOperator', { method: 'POST' }).catch(() => null);
      if (!res) { this.message = 'Could not reach server.'; return; }
      const data = await res.json();
      if (data.result === 'ok') { this.message = 'Request submitted. An admin will review it.'; await useUserStore().fetchMe(); }
      else if (data.result === 'already_requested') this.message = 'You already have a pending request.';
      else if (data.result === 'already_operator') this.message = 'You are already an operator.';
      else this.message = 'Something went wrong.';
      this.loading = false;
    },
  },
});
</script>

<style scoped>
.operator-request {
  background: rgb(30, 30, 30);
  border: 1px solid rgb(70, 70, 70);
  border-radius: 6px;
  padding: 8px 12px;
  font-size: 0.85em;
}

.toggle {
  background: none;
  border: none;
  color: gray;
  cursor: pointer;
  font-size: 0.85em;
  padding: 0;
}

.toggle:hover {
  color: darkgray;
}

.message {
  margin: 4px 0 0 0;
  color: darkgray;
  font-style: italic;
}

.action {
  margin-top: 4px;
  padding: 3px 10px;
  border-radius: 4px;
  border: none;
  background: rgb(52, 52, 52);
  color: darkgray;
  cursor: pointer;
  font-size: 1em;
}

.action:hover:not(:disabled) {
  background: rgb(70, 70, 70);
  color: white;
}

.action:disabled {
  opacity: 0.5;
  cursor: default;
}
</style>

// src/components/overlay/OperatorRequest.tsx
'use client'

import { useState } from 'react'
import { useUserStore } from '@/store/useUser'
import { fetchWithTimeout } from '@/utils/fetchWithTimeout'

export default function OperatorRequest() {
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [message, setMessage] = useState('')
  const isLoggedIn = useUserStore(s => s.isLoggedIn)

  async function request() {
    setLoading(true)
    const res = await fetchWithTimeout('/api/requestOperator', { method: 'POST' }).catch(() => null)
    if (!res) { setMessage('Could not reach server.'); setLoading(false); return }
    const data = await res.json()
    if (data.result === 'ok') { setMessage('Request submitted. An admin will review it.'); await useUserStore.getState().fetchMe() }
    else if (data.result === 'already_requested') setMessage('You already have a pending request.')
    else if (data.result === 'already_operator') setMessage('You are already an operator.')
    else setMessage('Something went wrong.')
    setLoading(false)
  }

  const panelStyle: React.CSSProperties = { background: 'rgb(30,30,30)', border: '1px solid rgb(70,70,70)', borderRadius: 6, padding: '8px 12px', fontSize: '0.85em' }
  const toggleStyle: React.CSSProperties = { background: 'none', border: 'none', color: 'gray', cursor: 'pointer', fontSize: '0.85em', padding: 0 }
  const actionStyle: React.CSSProperties = { display: 'inline-block', marginTop: 4, padding: '3px 10px', borderRadius: 4, border: 'none', background: 'rgb(52,52,52)', color: 'darkgray', cursor: 'pointer', fontSize: '1em', textDecoration: 'none' }

  return (
    <div style={panelStyle}>
      <button onClick={() => setOpen(o => !o)} style={toggleStyle}>{open ? '▾' : '▸'} Operator access</button>
      {open && (
        <div>
          {!isLoggedIn
            ? <a href="/api/signin" style={actionStyle}>Sign in</a>
            : message
              ? <p style={{ margin: '4px 0 0 0', color: 'darkgray', fontStyle: 'italic' }}>{message}</p>
              : <button onClick={request} disabled={loading} style={{ ...actionStyle, opacity: loading ? 0.5 : 1, cursor: loading ? 'default' : 'pointer' }}>Request access</button>
          }
        </div>
      )}
    </div>
  )
}
