// src/components/RenderFilters.vue
<template>
  <div class="render-filters">
    <button class="toggle" @click="toggleOpen">{{ open ? '▾' : '▸' }} Render Filters</button>
    <div v-if="open" class="dropdown">

      <p class="file-size">World file: {{ fileSizeDisplay }}</p>

      <div class="section">
        <span class="section-label">Y</span>
        <div class="range-row">
          <input type="number" class="num-input" v-model.number="yMinLocal" min="0" max="255" @change="applyY" />
          <span class="sep">–</span>
          <input type="number" class="num-input" v-model.number="yMaxLocal" min="0" max="255" @change="applyY" />
          <button class="reset-btn" @click="resetY">Full</button>
        </div>
      </div>

      <div class="section">
        <span class="section-label">View dist</span>
        <div class="range-row">
          <input
            type="number"
            class="num-input"
            v-model.number="renderDistLocal"
            min="1"
            max="128"
            step="1"
            @change="applyRenderDist"
          />
          <span class="unit-label">chunks</span>
          <button class="reset-btn" @click="resetRenderDist">Reset</button>
        </div>
      </div>

      <div class="section">
        <span class="section-label">XZ ±</span>
        <div class="range-row">
          <input
            type="number"
            class="num-input"
            v-model.number="xzRangeLocal"
            min="1"
            placeholder="∞"
            @change="applyXZ"
          />
          <span class="unit-label">blocks</span>
          <button class="reset-btn" @click="clearXZ">Clear</button>
        </div>
        <p class="hint" v-if="worldView.computerRangeXZ !== null && worldView.selectedComputerId === -1 && !worldView.manualCenter">
          Set a center coordinate in the selector to apply XZ range.
        </p>
      </div>

      <div class="section">
        <label class="checkbox-label">
          <input type="checkbox" v-model="worldView.fastRender" @change="worldView.regenerateSceneFromBlocks()" />
          Multiworker
        </label>
        <p class="hint">Builds chunks on all CPU cores in parallel.</p>
      </div>

      <div class="section">
        <label class="checkbox-label">
          <input type="checkbox" v-model="worldView.skipLoadYield" @change="worldView.regenerateSceneFromBlocks()" />
          Skip load pauses
        </label>
        <p class="hint">Removes interactivity waits during load. Faster but may freeze UI briefly.</p>
      </div>

      <div class="section">
        <label class="checkbox-label">
          <input type="checkbox" v-model="worldView.lockChunks" @change="worldView.updateChunkVisibility()" />
          Lock chunks
        </label>
        <p class="hint">Keeps loaded chunks in memory permanently. Disabling sweeps out-of-range chunks.</p>
      </div>

      <div class="section">
        <label class="checkbox-label">
          <input type="checkbox" v-model="worldView.showOrbitMarker" @change="worldView.updateChunkVisibility()" />
          Show orbit center
        </label>
      </div>

    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useWorldViewStore } from '../store/useWorldView';
import { useUserStore } from '../store/useUser';
import { useWorldStore } from '../store/useWorld';

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

export default defineComponent({
  setup() {
    return {
      worldView: useWorldViewStore(),
      user: useUserStore(),
      world: useWorldStore(),
    };
  },
  data() {
    return {
      open: false,
      yMinLocal: 0,
      yMaxLocal: 255,
      xzRangeLocal: null as number | null,
      renderDistLocal: 12,
    };
  },
  computed: {
    fileSizeDisplay(): string {
      if (this.user.savedFileSizeBytes === null) return 'unknown';
      return formatBytes(this.user.savedFileSizeBytes);
    },
    trackedComputerLocation(): string | null {
      const id = this.worldView.selectedComputerId;
      if (id === -1 || this.worldView.computerRangeXZ === null) return null;
      const computer = this.world.computers[id];
      return computer ? `${computer.loc.x},${computer.loc.z}` : null;
    },
  },
  watch: {
    trackedComputerLocation() {
      if (this.worldView.computerRangeXZ !== null) {
        this.worldView.regenerateSceneFromBlocks();
      }
    },
  },
  emits: ['opened'],
  methods: {
    toggleOpen() {
      this.open = !this.open;
      if (this.open) this.$emit('opened');
    },
    applyY() {
      const lo = Math.max(0, Math.min(255, this.yMinLocal));
      const hi = Math.max(0, Math.min(255, this.yMaxLocal));
      this.worldView.yMin = Math.min(lo, hi);
      this.worldView.yMax = Math.max(lo, hi);
      this.worldView.regenerateSceneFromBlocks();
    },
    resetY() {
      this.yMinLocal = 0;
      this.yMaxLocal = 255;
      this.worldView.yMin = 0;
      this.worldView.yMax = 255;
      this.worldView.regenerateSceneFromBlocks();
    },
    applyXZ() {
      this.worldView.computerRangeXZ = this.xzRangeLocal && this.xzRangeLocal > 0
        ? this.xzRangeLocal
        : null;
      this.worldView.regenerateSceneFromBlocks();
    },
    clearXZ() {
      this.xzRangeLocal = null;
      this.worldView.computerRangeXZ = null;
      this.worldView.regenerateSceneFromBlocks();
    },
    applyRenderDist() {
      const v = Math.max(1, Math.min(128, this.renderDistLocal ?? 8));
      this.renderDistLocal = v;
      this.worldView.renderDistance = v;
      this.worldView.updateChunkVisibility();
    },
    resetRenderDist() {
      this.renderDistLocal = 12;
      this.worldView.renderDistance = 12;
      this.worldView.updateChunkVisibility();
    },
  },
});
</script>

<style scoped>
.render-filters {
  position: relative;
  background: rgb(30, 30, 30);
  border: 1px solid rgb(70, 70, 70);
  border-radius: 6px;
  padding: 8px 12px;
  font-size: 0.85em;
}

.dropdown {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 100;
  background: rgb(30, 30, 30);
  border: 1px solid rgb(70, 70, 70);
  border-radius: 6px;
  padding: 8px 12px;
  min-width: 180px;
  margin-top: 2px;
}

.toggle {
  background: none;
  border: none;
  color: gray;
  cursor: pointer;
  font-size: 0.85em;
  padding: 0;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.toggle:hover {
  color: darkgray;
}

.file-size {
  margin: 6px 0 8px 0;
  color: gray;
  font-size: 0.85em;
}

.section {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  margin-bottom: 6px;
}

.section-label {
  font-size: 0.8em;
  color: gray;
  white-space: nowrap;
  flex-shrink: 0;
}

.range-row {
  display: flex;
  align-items: center;
  gap: 4px;
}

.num-input {
  width: 56px;
  padding: 2px 4px;
  border-radius: 4px;
  border: 1px solid rgb(70, 70, 70);
  background: rgb(40, 40, 40);
  color: darkgray;
  font-size: 0.9em;
  text-align: center;
}

.num-input:focus {
  outline: none;
  border-color: rgb(100, 100, 100);
}

.sep {
  color: gray;
}

.unit-label {
  color: gray;
  font-size: 0.85em;
}

.reset-btn {
  padding: 2px 6px;
  border-radius: 4px;
  border: none;
  background: rgb(52, 52, 52);
  color: darkgray;
  cursor: pointer;
  font-size: 0.8em;
  margin-left: 2px;
}

.reset-btn:hover {
  background: rgb(70, 70, 70);
  color: white;
}

.hint {
  margin: 3px 0 0 0;
  color: gray;
  font-size: 0.78em;
  font-style: italic;
}

.checkbox-label {
  display: flex;
  align-items: center;
  gap: 6px;
  color: darkgray;
  cursor: pointer;
  font-size: 0.85em;
}
</style>

// src/components/overlay/RenderFilters.tsx
'use client'

import { useState, forwardRef, useImperativeHandle } from 'react'
import { useWorldViewStore } from '@/store/useWorldView'
import { useUserStore } from '@/store/useUser'
import { HeaderMenu, Checkbox } from '@/components/ui'

interface Props { onOpened?: () => void }
export interface PanelHandle { setOpen: (v: boolean) => void }

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`
}

const RenderFilters = forwardRef<PanelHandle, Props>(function RenderFilters({ onOpened }, ref) {
  const [open, setOpen] = useState(false)
  useImperativeHandle(ref, () => ({ setOpen }), [])
  const [yMinLocal, setYMinLocal] = useState(0)
  const [yMaxLocal, setYMaxLocal] = useState(255)
  const [renderDistLocal, setRenderDistLocal] = useState(12)

  const fastRender    = useWorldViewStore(s => s.fastRender)
  const skipLoadYield = useWorldViewStore(s => s.skipLoadYield)
  const lockChunks    = useWorldViewStore(s => s.lockChunks)
  const lockBlockInfo = useWorldViewStore(s => s.lockBlockInfo)
  const showOrbitMarker = useWorldViewStore(s => s.showOrbitMarker)
  const miningMode       = useWorldViewStore(s => s.miningMode)
  const simpleOcclusion  = useWorldViewStore(s => s.simpleOcclusion)
  const savedFileSizeBytes = useUserStore(s => s.savedFileSizeBytes)
  const fileSizeDisplay = savedFileSizeBytes === null ? 'unknown' : formatBytes(savedFileSizeBytes)

  function toggleMiningMode() {
    const on = !miningMode
    if (on) {
      const capped = Math.min(renderDistLocal, 4)
      setRenderDistLocal(capped)
      const { transparencyList, miningOpacityMap } = useWorldViewStore.getState()
      const seededMap = { ...miningOpacityMap }
      for (const name of transparencyList) {
        if (!(name in seededMap)) seededMap[name] = 0.3
      }
      useWorldViewStore.setState({ miningMode: true, renderDistance: capped, miningOpacityMap: seededMap })
    } else {
      useWorldViewStore.setState({ miningMode: false })
    }
    useWorldViewStore.getState().regenerateSceneFromBlocks()
  }

  function applyY() {
    const lo = Math.max(0, Math.min(255, yMinLocal))
    const hi = Math.max(0, Math.min(255, yMaxLocal))
    useWorldViewStore.setState({ yMin: Math.min(lo, hi), yMax: Math.max(lo, hi) })
    useWorldViewStore.getState().regenerateSceneFromBlocks()
  }

  function resetY() {
    setYMinLocal(0); setYMaxLocal(255)
    useWorldViewStore.setState({ yMin: 0, yMax: 255 })
    useWorldViewStore.getState().regenerateSceneFromBlocks()
  }

  function applyRenderDist() {
    const v = Math.max(1, Math.min(128, renderDistLocal ?? 8))
    setRenderDistLocal(v)
    useWorldViewStore.setState({ renderDistance: v })
    useWorldViewStore.getState().updateChunkVisibility()
  }

  function resetRenderDist() {
    setRenderDistLocal(12)
    useWorldViewStore.setState({ renderDistance: 12 })
    useWorldViewStore.getState().updateChunkVisibility()
  }

  const numInput: React.CSSProperties = { width: 58, padding: '5px 6px', fontSize: 12 }

  return (
    <HeaderMenu label="Render Filters" compact align="right">
      <div className="dropdown-section">
        <button
          className={`btn btn-compact btn-block${miningMode ? ' btn-primary' : ''}`}
          onClick={toggleMiningMode}
        >{miningMode ? 'Mining Mode: ON' : 'Mining Mode'}</button>
      </div>

      <div className="dropdown-divider" />

      <div className="dropdown-section">
        <div className="dropdown-row">
          <span className="dropdown-row-label">World file</span>
          <span className="dropdown-hint mono">{fileSizeDisplay}</span>
        </div>
        <div className="dropdown-divider" />

        <div className="dropdown-row">
          <span className="dropdown-row-label" style={{ flex: '0 0 64px' }}>Y</span>
          <input className="input input-mono" style={numInput} type="number" value={yMinLocal} min={0} max={255} onChange={e => setYMinLocal(Number(e.target.value))} onBlur={applyY} />
          <input className="input input-mono" style={numInput} type="number" value={yMaxLocal} min={0} max={255} onChange={e => setYMaxLocal(Number(e.target.value))} onBlur={applyY} />
          <button className="btn btn-compact" onClick={resetY}>Full</button>
        </div>

        <div className="dropdown-row">
          <span className="dropdown-row-label" style={{ flex: '0 0 64px' }}>View dist</span>
          <input className="input input-mono" style={numInput} type="number" value={renderDistLocal} min={1} max={128} onChange={e => setRenderDistLocal(Number(e.target.value))} onBlur={applyRenderDist} />
          <span className="dropdown-hint">chunks</span>
          <button className="btn btn-compact" onClick={resetRenderDist}>Reset</button>
        </div>

      </div>

      <div className="dropdown-divider" />

      <div className="dropdown-section">
        <Checkbox
          label="Multiworker"
          desc="Builds chunks on all CPU cores in parallel."
          checked={fastRender}
          onChange={v => { useWorldViewStore.setState({ fastRender: v }); useWorldViewStore.getState().regenerateSceneFromBlocks() }}
        />
        <Checkbox
          label="Skip load pauses"
          desc="Apply chunk geometry immediately. Loads faster but the UI may stutter; unchecked caps to 5ms/tick."
          checked={skipLoadYield}
          onChange={v => useWorldViewStore.setState({ skipLoadYield: v })}
        />
        <Checkbox
          label="Lock chunks"
          desc="Keeps loaded chunks in memory permanently. Disabling sweeps out-of-range chunks."
          checked={lockChunks}
          onChange={v => { useWorldViewStore.setState({ lockChunks: v }); useWorldViewStore.getState().updateChunkVisibility() }}
        />
        <Checkbox
          label="Block hover info"
          desc="Show block name under cursor on mouse move. Requires raycasting each frame."
          checked={!lockBlockInfo}
          onChange={v => useWorldViewStore.setState({ lockBlockInfo: !v })}
        />
        <Checkbox
          label="Alpha-cutout occlusion"
          desc="Suppresses faces between adjacent same-type foliage (like leaves), matching how glass handles seams. Reduces face count in leaf-heavy areas."
          checked={simpleOcclusion}
          onChange={v => { useWorldViewStore.setState({ simpleOcclusion: v }); useWorldViewStore.getState().regenerateSceneFromBlocks() }}
        />
        <Checkbox
          label="Show orbit center"
          checked={showOrbitMarker}
          onChange={v => { useWorldViewStore.setState({ showOrbitMarker: v }); useWorldViewStore.getState().updateChunkVisibility() }}
        />
      </div>
    </HeaderMenu>
  )
})

export default RenderFilters
